contacts = [
    {'nama': 'CITRA AYU PRADANA', 'email': 'citra.ayu969@kemenimipas.go.id'},
    {'nama': 'CITRA AYUNI GOBEL', 'email': 'citra.ayuni@kemenimipas.go.id'},
    {'nama': 'CITRA BERLY, S.H.', 'email': 'citra.berly83@kemenimipas.go.id'},
    {'nama': 'CITRA DARINI WIDAYANTI', 'email': 'citra.darini@kemenimipas.go.id'},
    {'nama': 'CITRA DEWI NOVITASARI', 'email': 'citra.dewi.novitasari92@kemenimipas.go.id'},
    {'nama': 'CITRA DEWI SAMAUN', 'email': 'citra.dewi.samaun93@kemenimipas.go.id'},
    {'nama': 'CITRA ENDRA KUSUMA', 'email': 'citra.endra@kemenimipas.go.id'},
    {'nama': 'CITRA ERA DEPY', 'email': 'citra.era@kemenimipas.go.id'},
    {'nama': 'CITRA FIRZA AZIZAH', 'email': 'citra.firza.azizah00@kemenimipas.go.id'},
    {'nama': 'CITRA HAPPY GULTOM', 'email': 'citra.happy.gultom94@kemenimipas.go.id'},
    {'nama': 'CITRA IMAN WIBISANA', 'email': 'citra.iman@kemenimipas.go.id'},
    {'nama': 'CITRA KURNIATI', 'email': 'citra.kurniati84@kemenimipas.go.id'},
    {'nama': 'CITRA LARAS MUTIARA', 'email': 'citra.laras.mutiara88@kemenimipas.go.id'},
    {'nama': 'CITRA LESTARI PUTRI, S.E., M.Si.', 'email': 'citra.lestari.putri94@kemenimipas.go.id'},
    {'nama': 'CITRA MEISHA SIMBOLON', 'email': 'citra.meisha.simbolon92@kemenimipas.go.id'},
    {'nama': 'CITRA MERINAWATI', 'email': 'citra.merinawati@kemenimipas.go.id'},
    {'nama': 'CITRA NARA SUPRIYONO PUTRI', 'email': 'citra.nara.supriyono.putri05@kemenimipas.go.id'},
    {'nama': 'CITRA NURJANAH', 'email': 'citra.nurjanah00@kemenimipas.go.id'},
    {'nama': 'CITRA NURVIRAWATI', 'email': 'citra.nurvirawati87@kemenimipas.go.id'},
    {'nama': 'CITRA NURWINDA', 'email': 'citra.nurwinda00@kemenimipas.go.id'},
    {'nama': 'CITRA PERMATASARI SIMAMORA', 'email': 'citra.permatasari.simamora94@kemenimipas.go.id'},
    {'nama': 'CITRA PRATIWI TRI LESTARI', 'email': 'citra.pratiwi.tri.lestari05@kemenimipas.go.id'},
    {'nama': 'CITRA SRI ARYANINGRUM ZAI', 'email': 'citra.sri.aryaningrum.zai99@kemenimipas.go.id'},
    {'nama': 'CITRA SUHENDRA, S.H.', 'email': 'citra.suhendra@kemenimipas.go.id'},
    {'nama': 'CITRA TRI NALURITA', 'email': 'citra.tri.nalurita96@kemenimipas.go.id'},
    {'nama': 'CITRA WULAN ASTUTI', 'email': 'citra.wulan@kemenimipas.go.id'},
    {'nama': 'CITRA WULANDARI', 'email': 'citra.wulandari@kemenimipas.go.id'},
    {'nama': 'CITRAKA DAFFA RADITYA', 'email': 'citraka.daffa.raditya05@kemenimipas.go.id'},
    {'nama': 'CITRAWATI TIRING', 'email': 'citrawati.tiring@kemenimipas.go.id'},
    {'nama': 'CITRO TAMBA', 'email': 'citro.tamba97@kemenimipas.go.id'},
    {'nama': 'CITTA AYUDITA', 'email': 'citta.ayudita97@kemenimipas.go.id'},
    {'nama': 'CIWOGALATIA', 'email': 'ciwogalatia81@kemenimipas.go.id'},
    {'nama': 'CLAODIA NARASINDHI', 'email': 'claodia.narasindhi@kemenimipas.go.id'},
    {'nama': 'CLARA MENTARI GRACIA LENGKEY', 'email': 'clara.mentari.gracia.lengkey03@kemenimipas.go.id'},
    {'nama': 'CLARA RENNY KARTIKA', 'email': 'clara.renny.kartika97@kemenimipas.go.id'},
    {'nama': 'CLARA SARAGIH', 'email': 'clara.saragih06@kemenimipas.go.id'},
    {'nama': 'CLARA URSULA OKTOVINA KADIWARU', 'email': 'clara.ursula@kemenimipas.go.id'},
    {'nama': 'CLARA VANESIA BANGUN', 'email': 'clara.vanesia.bangun96@kemenimipas.go.id'},
    {'nama': 'CLARA WIDELA, S.E.', 'email': 'clara.widela92@kemenimipas.go.id'},
    {'nama': 'CLARINTA SIMANGUNSONG', 'email': 'clarinta.simangunsong99@kemenimipas.go.id'},
    {'nama': 'CLARISA SULYOHANA HANGGAWALI', 'email': 'clarisa.sulyohana.hanggawali05@kemenimipas.go.id'},
    {'nama': 'CLARISSA AYU NUGRAHA', 'email': 'clarissa.ayu.nugraha98@kemenimipas.go.id'},
    {'nama': 'CLARISSA WIDYA PRATIWI', 'email': 'clarissa.widya.pratiwi06@kemenimipas.go.id'},
    {'nama': 'CLAUDHIA NESTI SALINDEHO', 'email': 'claudhia.nesti.salindeho94@kemenimipas.go.id'},
    {'nama': 'CLAUDIA ANDRIANI PRAMONO', 'email': 'claudia.andriani@kemenimipas.go.id'},
    {'nama': 'CLAUDIA BEBY GUSRINDA', 'email': 'claudia.beby@kemenimipas.go.id'},
    {'nama': 'CLAUDIA LAKSASMITA, S.Tr.Pas.', 'email': 'claudia.laksasmita01@kemenimipas.go.id'},
    {'nama': 'CLAUDIA MARANATHA ARUAN', 'email': 'claudia.maranatha@kemenimipas.go.id'},
    {'nama': 'CLAUDIA MARIA ELMONIA', 'email': 'claudia.maria.elmonia92@kemenimipas.go.id'},
    {'nama': 'CLAUDIA MELISSA SALHUTERU', 'email': 'claudia.melissa@kemenimipas.go.id'},
    {'nama': 'CLAUDIA OLIVIA SAMBERI, S.I.Kom', 'email': 'claudia.olivia.samberi98@kemenimipas.go.id'},
    {'nama': 'CLAUDIA URSULA VIOLENT OCTRICYA', 'email': 'claudia.ursula@kemenimipas.go.id'},
    {'nama': 'CLAUDIO FABRIZIO MALIANGKAY', 'email': 'claudio.fabrizio.maliangkay96@kemenimipas.go.id'},
    {'nama': 'CLAUDIO FERNANDO BAITANU', 'email': 'claudio.fernando@kemenimipas.go.id'},
    {'nama': 'CLAUDIUS LANDO', 'email': 'claudius.lando98@kemenimipas.go.id'},
    {'nama': 'CLAUDIUS PRASETYO TETONG', 'email': 'claudius.prasetyo.tetong00@kemenimipas.go.id'},
    {'nama': 'CLAUDIYANA FITRIAH', 'email': 'claudiyana.fitriah@kemenimipas.go.id'},
    {'nama': 'CLAUDYA GEOFINA GENDITA', 'email': 'claudya.geofina@kemenimipas.go.id'},
    {'nama': 'CLAUDYA VIRGINIA REA', 'email': 'claudya.virginia.reaia.rea96@kemenimipas.go.id'},
    {'nama': 'CLEINE GAVRILA DELMORA ADAM', 'email': 'cleine.gavrila.delmora.adam06@kemenimipas.go.id'},
    {'nama': 'CLEMENCY GUNAWAN', 'email': 'clemency.gunawan77@kemenimipas.go.id'},
    {'nama': 'CLIF SEBASTIAN DJEDDIN', 'email': 'clif.sebastian@kemenimipas.go.id'},
    {'nama': 'CLIFORD THEOFANI LANGI', 'email': 'cliford.theofani.langi95@kemenimipas.go.id'},
    {'nama': 'CLINTON ODY FOLSEN AMBARITA', 'email': 'clinton.ody.folsen.ambarita95@kemenimipas.go.id'},
    {'nama': 'CLINTON PANDAPOTAN LUBIS', 'email': 'clinton.pandapotan.lubis05@kemenimipas.go.id'},
    {'nama': 'COK RADITYA', 'email': 'Cok.Raditya@kemenimipas.go.id'},
    {'nama': 'COKORDA GDE PRABAWA DIPUTRA', 'email': 'cokorda.gde@kemenimipas.go.id'},
    {'nama': 'COKORDA GEDE BAGUS DHARMARUPAWAN, SH', 'email': 'cokorda.gede@kemenimipas.go.id'},
    {'nama': 'COKORDA ISTRI EKA DILA SAFITRI, S.M.', 'email': 'cokorda.istri@kemenimipas.go.id'},
    {'nama': 'COKORDA WISNU MAHA ADITYA', 'email': 'Cokorda.Wisnu@kemenimipas.go.id'},
    {'nama': 'COKRO SETYOWIBOWO', 'email': 'cokro.setyowibowo@kemenimipas.go.id'},
    {'nama': 'COKY BOY SYAH', 'email': 'coky.boy.syah68@kemenimipas.go.id'},
    {'nama': 'COKY NGOLU CHRISTOFFEL MANULLANG', 'email': 'coky.ngolu@kemenimipas.go.id'},
    {'nama': 'COMI HENDARISWATI', 'email': 'comi.hendariswati@kemenimipas.go.id'},
    {'nama': 'CONIA AZKADINA', 'email': 'conia.azkadina03@kemenimipas.go.id'},
    {'nama': 'I WAYAN PRASETYA LENCANA', 'email': 'contact.lencanaprasetya@kemenimipas.go.id'},
    {'nama': 'COOKY MS SIMANJUNTAK', 'email': 'Cookysimanjuntak@kemenimipas.go.id'},
    {'nama': 'CORESY PETRA HEIN TANATY', 'email': 'coresy.petra.hein.tanaty93@kemenimipas.go.id'},
    {'nama': 'CORI FRENTINA TAMPUBOLON, AM.Keb', 'email': 'Corifrentina@kemenimipas.go.id'},
    {'nama': 'CORLIN WENNO', 'email': 'corlin.wenno79@kemenimipas.go.id'},
    {'nama': 'CORNELIS APRIAN ABINENO', 'email': 'cornelis.aprian.abineno92@kemenimipas.go.id'},
    {'nama': 'CORNELIUS AGATHA GEA', 'email': 'cornelius.agatha.gea99@kemenimipas.go.id'},
    {'nama': 'CORNELIUS BATU', 'email': 'cornelius.batu@kemenimipas.go.id'},
    {'nama': 'CORNELIUS EDON', 'email': 'cornelius.edon84@kemenimipas.go.id'},
    {'nama': 'CORRIE FITRIAH', 'email': 'corrie.fitriah@kemenimipas.go.id'},
    {'nama': 'CORRY ALIFIANA DIRGANTARI', 'email': 'corry.alifiana.dirgantari02@kemenimipas.go.id'},
    {'nama': 'CORRYNA ALLEN', 'email': 'corryna.allen@kemenimipas.go.id'},
    {'nama': 'CORY ANGGARA', 'email': 'cory.anggara98@kemenimipas.go.id'},
    {'nama': 'CORY PALUPI', 'email': 'cory.palupi94@kemenimipas.go.id'},
    {'nama': '-. COSMAS JOHANES NEKO, -', 'email': 'cosmas.johanes.neko03@kemenimipas.go.id'},
    {'nama': 'CRESCENTIANUS CATUR APRIYANTO Amd.Im., SH., M.Hum', 'email': 'crescentianus.catur@kemenimipas.go.id'},
    {'nama': 'CRILLY AVELY WONGKAR', 'email': 'crilly.avely@kemenimipas.go.id'},
    {'nama': 'CRIONY BAYUWENI WABANG', 'email': 'criony.bayuweni.wabang99@kemenimipas.go.id'},
    {'nama': 'CRISMAN HANEYANTON SIMANUNGKALIT', 'email': 'crisman.haneyanton.simanungkalit96@kemenimipas.go.id'},
    {'nama': 'CRISMANTO PARULI SAMOSIR', 'email': 'crismanto.paruli@kemenimipas.go.id'},
    {'nama': 'CRIST YOEL MANIHURUK', 'email': 'crist.yoel.manihuruk02@kemenimipas.go.id'},
    {'nama': 'CRISTHINE MALIANDI', 'email': 'cristhine.maliandi@kemenimipas.go.id'},
    {'nama': 'CRISTI NORIET SUMENDA', 'email': 'cristi.noriet@kemenimipas.go.id'},
    {'nama': 'CRISTIAN GIDION MUNTHE', 'email': 'cristian.gidion.munthe06@kemenimipas.go.id'},
    {'nama': 'CRISTIAN H.P. SIALLAGAN', 'email': 'cristian.h.p.siallagan97@kemenimipas.go.id'},
    {'nama': 'CRISTIAN PRADANA', 'email': 'cristian.pradana96@kemenimipas.go.id'},
    {'nama': 'CRISTIAN RIZKY AGUS MARPAUNG', 'email': 'cristian.rizky.agus.marpaung00@kemenimipas.go.id'},
    {'nama': 'CRISTIANDO ROMA PARASIAN', 'email': 'cristiando.roma@kemenimipas.go.id'},
    {'nama': "CRISTIANTO PACE ANDERSON TA'EK", 'email': 'cristianto.pace.anderson.taek95@kemenimipas.go.id'},
    {'nama': 'CRISTIN BLESSY BIRINGAN', 'email': 'cristin.blessy@kemenimipas.go.id'},
    {'nama': 'CRISTINA ENTE', 'email': 'cristina.ente@kemenimipas.go.id'},
    {'nama': 'CRISTO GAIZKA KANALUNG', 'email': 'cristo.gaizka.kanalung01@kemenimipas.go.id'},
    {'nama': 'CRISTO R.P SIMANJUNTAK', 'email': 'cristo.r.p.simanjuntak03@kemenimipas.go.id'},
    {'nama': 'CRISTOFHER ALFONSO LESILOLO', 'email': 'cristofher.alfonso.lesilolo00@kemenimipas.go.id'},
    {'nama': 'CRISTOPEL GULTOM', 'email': 'cristopel.gultom@kemenimipas.go.id'},
    {'nama': 'CRISTOPEL SILABAN', 'email': 'cristopel.silaban04@kemenimipas.go.id'},
    {'nama': 'CRISTY M.SIMARMATA', 'email': 'cristy.m.simarmata06@kemenimipas.go.id'},
    {'nama': 'CRISYE CAROLIN HARIANJA', 'email': 'crisye.carolin@kemenimipas.go.id'},
    {'nama': 'CRYSTAL GREEN', 'email': 'crystal.green90@kemenimipas.go.id'},
    {'nama': 'CUCU JUBAEDAH', 'email': 'cucu.jubaedah82@kemenimipas.go.id'},
    {'nama': 'CUCU NURYANA', 'email': 'cucu.nuryana94@kemenimipas.go.id'},
    {'nama': 'CUCU SUPRIATNA', 'email': 'cucu.supriatna69@kemenimipas.go.id'},
    {'nama': 'CUN SUDIHARTO', 'email': 'Cun.Sudiharto@kemenimipas.go.id'},
    {'nama': 'CUT AINAL MARDHIAH', 'email': 'cut.ainal.mardhiah75@kemenimipas.go.id'},
    {'nama': 'CUT AMELIA ARUMI, S.H', 'email': 'cut.amelia.arumi82@kemenimipas.go.id'},
    {'nama': 'CUT ANA DARMAWAN', 'email': 'Cut.Ana@kemenimipas.go.id'},
    {'nama': 'CUT ANIS SYAFA', 'email': 'cut.anis.syafa99@kemenimipas.go.id'},
    {'nama': 'CUT ARINA FAUZA, A.Md., S.E.', 'email': 'cut.arina.fauza90@kemenimipas.go.id'},
    {'nama': 'CUT AURORA ANASTASIA', 'email': 'cut.aurora.anastasia@kemenimipas.go.id'},
    {'nama': 'CUT DINI MANDASARI', 'email': 'cut.dini@kemenimipas.go.id'},
    {'nama': 'CUT ELIZA ANGGRAINI', 'email': 'cut.eliza@kemenimipas.go.id'},
    {'nama': 'CUT ERIKA INDRIYANI', 'email': 'cut.erika.indriyani81@kemenimipas.go.id'},
    {'nama': 'CUT FARA MEUTIA', 'email': 'cut.fara.meutia98@kemenimipas.go.id'},
    {'nama': 'CUT FARIDAH', 'email': 'cut.faridah@kemenimipas.go.id'},
    {'nama': 'CUT HADAYA SYAKIRAH', 'email': 'cut.hadaya.syakirah05@kemenimipas.go.id'},
    {'nama': 'CUT HUSNA CHALIDA ZULFA', 'email': 'cut.husna.chalida.zulfa00@kemenimipas.go.id'},
    {'nama': 'CUT INTAN KEUMALA', 'email': 'cut.intan.keumala94@kemenimipas.go.id'},
    {'nama': 'CUT IRMA FITRIKA', 'email': 'cut.irma.fitrika75@kemenimipas.go.id'},
    {'nama': 'CUT LIZA SAHRA', 'email': 'cut.liza.sahra94@kemenimipas.go.id'},
    {'nama': 'CUT LUTPIANTI AYU ROSIAH', 'email': 'cut.lutpianti@kemenimipas.go.id'},
    {'nama': 'CUT MAYA IRNA', 'email': 'cut.maya.irna89@kemenimipas.go.id'},
    {'nama': 'CUT MEURAH KHALID', 'email': 'cut.meurah.khalid69@kemenimipas.go.id'},
    {'nama': 'CUT NAZWA SAHIRA', 'email': 'cut.nazwa.sahira05@kemenimipas.go.id'},
    {'nama': 'CUT NOVITASARI', 'email': 'cut.novitasari92@kemenimipas.go.id'},
    {'nama': 'CUT NUR AMNA, A.Md', 'email': 'cut.nur@kemenimipas.go.id'},
    {'nama': 'CUT PUTROE GAMBANG, S.H', 'email': 'cut.putroe.gambang87@kemenimipas.go.id'},
    {'nama': 'CUT RAUDLATUL JANNAH TS', 'email': 'cut.raudlatul@kemenimipas.go.id'},
    {'nama': 'CUT RISKA AINY', 'email': 'cut.riska.ainy99@kemenimipas.go.id'},
    {'nama': 'NYAK CUT SAKARIMA RAHMAH', 'email': 'Cut.Sakarima@kemenimipas.go.id'},
    {'nama': 'CUT SRI BAHAGIANI TS', 'email': 'cut.sri.bahagiani.ts85@kemenimipas.go.id'},
    {'nama': 'CUT SUATIKA', 'email': 'cut.suatika@kemenimipas.go.id'},
    {'nama': 'CUT TRISCA ANDAYANI', 'email': 'cut.trisca.andayani77@kemenimipas.go.id'},
    {'nama': 'CUT VIADNA VIRA', 'email': 'cut.viadna.vira90@kemenimipas.go.id'},
    {'nama': 'CUT VIEGHA HUMAIRA KHAIRUNNISA', 'email': 'cut.viegha.humaira.khairunnisa04@kemenimipas.go.id'},
    {'nama': 'CUT YARA ANDAMA', 'email': 'cut.yara.andama95@kemenimipas.go.id'},
    {'nama': 'CUT YESSI ANDRIANI', 'email': 'cut.yessi@kemenimipas.go.id'},
    {'nama': 'CUT YUNITA SARTIFA', 'email': 'cut.yunita.sartifa91@kemenimipas.go.id'},
    {'nama': 'CYNDI PERMATA SARI, S.Tr.Pas', 'email': 'cyndi.permata.sari98@kemenimipas.go.id'},
    {'nama': 'CYNDY FATIKHAH SARI', 'email': 'cyndy.fatikhah.sari04@kemenimipas.go.id'},
    {'nama': 'CYNTHIA FITRIANI', 'email': 'cynthia.fitriani96@kemenimipas.go.id'},
    {'nama': 'CYNTHIA HAYUWIRDHANI', 'email': 'cynthia.hayuwirdhani03@kemenimipas.go.id'},
    {'nama': 'CYNTHIA KIOK ALEXANDER', 'email': 'cynthia.kiok@kemenimipas.go.id'},
    {'nama': 'CYNTHIA RAMADHANITA SY', 'email': 'cynthia.ramadhanita@kemenimipas.go.id'},
    {'nama': 'CYNTIA DWI LESTARI', 'email': 'cyntia.dwi.lestari98@kemenimipas.go.id'},
    {'nama': 'CYNTIA FERGININGRUM', 'email': 'cyntia.ferginingrum@kemenimipas.go.id'},
    {'nama': 'CYNTIA, S.S', 'email': 'cyntia@kemenimipas.go.id'},
    {'nama': 'CYNTYA ANGGI SIANTURI', 'email': 'cyntya.anggi.sianturi97@kemenimipas.go.id'},
    {'nama': 'D E D I', 'email': 'd.e.d.i88@kemenimipas.go.id'},
    {'nama': 'D. S. JUANBERO DUMEDA', 'email': 'd.s.juanbero.dumeda01@kemenimipas.go.id'},
    {'nama': 'D YANETH PARULIAN LIMBONG', 'email': 'd.yaneth.parulian.limbong93@kemenimipas.go.id'},
    {'nama': 'DADAN ANUGRAH RAMDHAN', 'email': 'dadan.anugrah@kemenimipas.go.id'},
    {'nama': 'DADAN DANIAL', 'email': 'dadan.danial72@kemenimipas.go.id'},
    {'nama': 'DADAN FIRMANSYAH', 'email': 'dadan.firmansyah91@kemenimipas.go.id'},
    {'nama': 'DADAN GUNAWAN', 'email': 'dadan.gunawan@kemenimipas.go.id'},
    {'nama': 'DADAN HERDIANA', 'email': 'dadan.herdiana826@kemenimipas.go.id'},
    {'nama': 'DADAN HERDIANA', 'email': 'dadan.herdiana95@kemenimipas.go.id'},
    {'nama': 'DADAN HERMAWAN', 'email': 'dadan.hermawan78@kemenimipas.go.id'},
    {'nama': 'DADAN JUNAEDI', 'email': 'dadan.junaedi@kemenimipas.go.id'},
    {'nama': 'DADAN MAHMUD DJAJADISASTRA', 'email': 'dadan.mahmud.djajadisastra68@kemenimipas.go.id'},
    {'nama': 'DADAN MOHAMMAD RAMDAN', 'email': 'dadan.mohammad.ramdan96@kemenimipas.go.id'},
    {'nama': 'DADAN RULY NERE', 'email': 'dadan.ruly.nere82@kemenimipas.go.id'},
    {'nama': 'DADAN SETIA GUMELAR', 'email': 'dadan.setia@kemenimipas.go.id'},
    {'nama': 'DADAN WARDANA', 'email': 'dadan.wardana94@kemenimipas.go.id'},
    {'nama': 'DADAN', 'email': 'dadan70@kemenimipas.go.id'},
    {'nama': 'DADANG ADI PATIANUM', 'email': 'dadang.adi@kemenimipas.go.id'},
    {'nama': 'DADANG ASFAR', 'email': 'dadang.asfar90@kemenimipas.go.id'},
    {'nama': 'DADANG BAGUS SETYAWAN', 'email': 'dadang.bagus.setyawan90@kemenimipas.go.id'},
    {'nama': 'DADANG FIRMANSYAH', 'email': 'dadang.firmansyah@kemenimipas.go.id'},
    {'nama': 'DADANG HIDAYAT', 'email': 'dadang.hidayat70@kemenimipas.go.id'},
    {'nama': 'DADANG IRAWAN', 'email': 'dadang.irawan80@kemenimipas.go.id'},
    {'nama': 'DADANG JAYAATMANEGARA', 'email': 'dadang.jayaatmanegara89@kemenimipas.go.id'},
    {'nama': 'DADANG KURNIA', 'email': 'dadang.kurnia86@kemenimipas.go.id'},
    {'nama': 'DADANG KURNIAWAN', 'email': 'dadang.kurniawan86@kemenimipas.go.id'},
    {'nama': 'DADANG KUSUMA WIJAYA', 'email': 'dadang.kusuma.wijaya95@kemenimipas.go.id'},
    {'nama': 'DADANG MUNANDAR', 'email': 'dadang.munandar@kemenimipas.go.id'},
    {'nama': 'DADANG RAIS SAPUTRO', 'email': 'dadang.rais@kemenimipas.go.id'},
    {'nama': 'DADANG RAMADHAN AKBAR', 'email': 'dadang.ramadhan@kemenimipas.go.id'},
    {'nama': 'DADANG RIESMOKO', 'email': 'dadang.riesmoko84@kemenimipas.go.id'},
    {'nama': 'DADANG SAPUTRA', 'email': 'dadang.saputra71@kemenimipas.go.id'},
    {'nama': 'DADANG SISWANTO', 'email': 'dadang.siswanto79@kemenimipas.go.id'},
    {'nama': 'DADANG SUDRAJAT', 'email': 'dadang.sudrajat81@kemenimipas.go.id'},
    {'nama': 'DADANG SUHANDA', 'email': 'dadang.suhanda71@kemenimipas.go.id'},
    {'nama': 'DADANG SUHERLAN', 'email': 'Dadang.Suherlan@kemenimipas.go.id'},
    {'nama': 'DADANG SUMARDI', 'email': 'dadang.sumardi70@kemenimipas.go.id'},
    {'nama': 'DADANG SUPRIADI', 'email': 'dadang.supriadi69@kemenimipas.go.id'},
    {'nama': 'DADANG SURAHMAN', 'email': 'dadang.surahman95@kemenimipas.go.id'},
    {'nama': 'DADANG TRI BASKORO', 'email': 'dadang.tri.baskoro98@kemenimipas.go.id'},
    {'nama': 'DADANG TRIHATMOKO', 'email': 'dadang.trihatmoko@kemenimipas.go.id'},
    {'nama': 'DADANG TRIO ZULKARNAIN', 'email': 'dadang.trio.zulkarnain91@kemenimipas.go.id'},
    {'nama': 'DADANG YULIANTO', 'email': 'dadang.yulianto82@kemenimipas.go.id'},
    {'nama': 'DADDY RAMDHAN', 'email': 'daddy.ramdhan@kemenimipas.go.id'},
    {'nama': 'DADE ACHMAD AKTAMA', 'email': 'dade.achmad.aktama99@kemenimipas.go.id'},
    {'nama': 'DADI HENDARDI', 'email': 'dadi.hendardi00@kemenimipas.go.id'},
    {'nama': 'DADI KURNIAWAN', 'email': 'dadi.kurniawan83@kemenimipas.go.id'},
    {'nama': 'DADI SUTARDI', 'email': 'dadi.sutardi73@kemenimipas.go.id'},
    {'nama': 'DADIK TIPO HANANTO', 'email': 'dadik.tipo.hananto93@kemenimipas.go.id'},
    {'nama': 'DADING JAYAHADIKUSUMA', 'email': 'dading.jayahadikusuma@kemenimipas.go.id'},
    {'nama': 'DADY GUSNAWAN', 'email': 'Dady.Gusnawan@kemenimipas.go.id'},
    {'nama': 'DAELI PURWANTO', 'email': 'daeli.purwanto87@kemenimipas.go.id'},
    {'nama': 'DAENG ANTARRESTU', 'email': 'daeng.antarrestu77@kemenimipas.go.id'},
    {'nama': 'DAENG ARDIAN SAPUTRA', 'email': 'daeng.ardian.saputra94@kemenimipas.go.id'},
    {'nama': 'DAENI WAHYOUDIE', 'email': 'daeni.wahyoudie82@kemenimipas.go.id'},
    {'nama': 'DAEVFI APRIAN WAHYOUDIE', 'email': 'daevfi.aprian@kemenimipas.go.id'},
    {'nama': 'DAFA DINULHAK', 'email': 'dafa.dinulhak99@kemenimipas.go.id'},
    {'nama': 'DAFA ILHAMDIKA MOZA PRATAMA', 'email': 'dafa.ilhamdika.moza.pratama06@kemenimipas.go.id'},
    {'nama': 'DAFA NURHIDAYAT', 'email': 'dafa.nurhidayat06@kemenimipas.go.id'},
    {'nama': 'DAFA RENOLD JORDI', 'email': 'dafa.renold.jordi05@kemenimipas.go.id'},
    {'nama': 'DAFFA ABYAN NUGRAHANTO', 'email': 'daffa.abyan.nugrahanto06@kemenimipas.go.id'},
    {'nama': 'DAFFA ALIEF BAIHAQI', 'email': 'daffa.alief.baihaqi01@kemenimipas.go.id'},
    {'nama': 'DAFFA ANDALAS SURYA', 'email': 'daffa.andalas.surya01@kemenimipas.go.id'},
    {'nama': 'DAFFA ANUGRAH YASA PUTRA', 'email': 'daffa.anugrah.yasa.putra01@kemenimipas.go.id'},
    {'nama': 'DAFFA BAGOS MARSEKAL', 'email': 'daffa.bagos.marsekal03@kemenimipas.go.id'},
    {'nama': 'DAFFA CAHYA SABELA', 'email': 'daffa.cahya.sabela04@kemenimipas.go.id'},
    {'nama': 'DAFFA DWI RIANSYAH', 'email': 'daffa.dwi.riansyah03@kemenimipas.go.id'},
    {'nama': 'DAFFA DZAKY ADI SAKHA', 'email': 'daffa.dzaky.adi.sakha01@kemenimipas.go.id'},
    {'nama': 'DAFFA FAHRUL ROZY LUBIS', 'email': 'daffa.fahrul.rozy.lubis03@kemenimipas.go.id'},
    {'nama': 'DAFFA ICHSAN NOVRIANSYA', 'email': 'daffa.ichsan.novriansya99@kemenimipas.go.id'},
    {'nama': 'DAFFA IFTIKHAR', 'email': 'daffa.iftikhar@kemenimipas.go.id'},
    {'nama': 'DAFFA MAYANG LESTARI', 'email': 'daffa.mayang.lestari05@kemenimipas.go.id'},
    {'nama': 'DAFFA NUR FAUZAN', 'email': 'daffa.nur.fauzan00@kemenimipas.go.id'},
    {'nama': 'DAFFA NURRIZKY BLONGKOD', 'email': 'daffa.nurrizky.blongkod01@kemenimipas.go.id'},
    {'nama': 'DAFFA PRATAMA', 'email': 'daffa.pratama99@kemenimipas.go.id'},
    {'nama': 'DAFFA PUTRA DARMAWAN', 'email': 'daffa.putra.darmawan03@kemenimipas.go.id'},
    {'nama': 'DAFFA RIZKY RAMADHANI', 'email': 'daffa.rizky.ramadhani99@kemenimipas.go.id'},
    {'nama': 'DAFFA SETIAWAN', 'email': 'daffa.setiawan04@kemenimipas.go.id'},
    {'nama': 'DAFFA WICAKSONO', 'email': 'daffa.wicaksono05@kemenimipas.go.id'},
    {'nama': 'DAFFA YUDHISTIRA ALIF PAHLEVI', 'email': 'daffa.yudhistira.alif.pahlevi00@kemenimipas.go.id'},
    {'nama': 'NAUFAL DAFFA FERNALDY', 'email': 'daffafernaldy2002@gmail.com'},
    {'nama': 'DAFFARA ARSYAHITA PUTRI', 'email': 'daffara.arsyahita.putri01@kemenimipas.go.id'},
    {'nama': 'MUHAMMAD DAFFA RIVANO PASHA', 'email': 'daffarivano9b@gmail.com'},
    {'nama': 'DAFID ANTONI', 'email': 'dafid.antoni76@kemenimipas.go.id'},
    {'nama': 'DAFIDTRIA RAGIL PAMUNGKAS', 'email': 'dafidtria.ragil.pamungkas02@kemenimipas.go.id'},
    {'nama': 'DAFINAH HASHIFAH, S.Tr.Pas', 'email': 'dafinah.hashifah99@kemenimipas.go.id'},
    {'nama': 'DAFIT AGUSTARI', 'email': 'dafit.agustari86@kemenimipas.go.id'},
    {'nama': 'DAFIT ANDRIAN', 'email': 'dafit.andrian99@kemenimipas.go.id'},
    {'nama': 'DAFIT PRASETYA ALFAZAR', 'email': 'dafit.prasetya.alfazar01@kemenimipas.go.id'},
    {'nama': 'DAFIT PRIANGGA YUDHI', 'email': 'dafit.priangga.yudhi98@kemenimipas.go.id'},
    {'nama': 'DAFRIJON', 'email': 'dafrijon77@kemenimipas.go.id'},
    {'nama': 'DAGMAR MAMORI', 'email': 'dagmar.mamori93@kemenimipas.go.id'},
    {'nama': 'DAHARMAN JAYADI', 'email': 'daharman.jayadi69@kemenimipas.go.id'},
    {'nama': 'DAHLAN ANGGODA', 'email': 'dahlan.anggoda@kemenimipas.go.id'},
    {'nama': 'DAHLAN ARRIDHO', 'email': 'dahlan.arridho00@kemenimipas.go.id'},
    {'nama': 'DAHLAN DAMANIK', 'email': 'dahlan.damanik@kemenimipas.go.id'},
    {'nama': 'DAHLAN FAUZI LUBIS', 'email': 'dahlan.fauzi.lubis94@kemenimipas.go.id'},
    {'nama': 'DAHLAN HIDAYAT', 'email': 'dahlan.hidayat93@kemenimipas.go.id'},
    {'nama': 'DAHLAN RUMAU', 'email': 'dahlan.rumau@kemenimipas.go.id'},
    {'nama': 'DAHLAN', 'email': 'dahlan89@kemenimipas.go.id'},
    {'nama': 'DAHLAN', 'email': 'dahlan91@kemenimipas.go.id'},
    {'nama': 'DAHLIA MAHDALENI', 'email': 'dahlia.mahdaleni00@kemenimipas.go.id'},
    {'nama': 'DAHLIA MURNI', 'email': 'dahlia.murni@kemenimipas.go.id'},
    {'nama': 'DAHLIA PERTIWI SURYANI', 'email': 'dahlia.pertiwi@kemenimipas.go.id'},
    {'nama': 'DAHLIA, S.H., M.H.', 'email': 'dahlia@kemenimipas.go.id'},
    {'nama': 'DAHLIA', 'email': 'dahlia91@kemenimipas.go.id'},
    {'nama': 'DAHLIANA', 'email': 'dahliana00@kemenimipas.go.id'},
    {'nama': 'DAHLIYA MAHARANI', 'email': 'dahliya.maharani@kemenimipas.go.id'},
    {'nama': 'DAHNIA RAMADHANI', 'email': 'dahnia.ramadhani@kemenimipas.go.id'},
    {'nama': 'DAHNIA SANDRINA', 'email': 'dahnia.sandrina05@kemenimipas.go.id'},
    {'nama': 'DAHNIAL JAKA ADITIA', 'email': 'dahnial.jaka.aditia90@kemenimipas.go.id'},
    {'nama': 'DHANIEL SANDY PUTRA PAMUNGKAS', 'email': 'dahnielsandy95@icloud.com'},
    {'nama': 'DAHONO SUKO', 'email': 'dahono.suko@kemenimipas.go.id'},
    {'nama': 'DAHRONI', 'email': 'dahroni@kemenimipas.go.id'},
    {'nama': 'DAHRUL MANALU', 'email': 'dahrul.manalu90@kemenimipas.go.id'},
    {'nama': 'DAHRUL', 'email': 'dahrul93@kemenimipas.go.id'},
    {'nama': "DA'I RAFLI PRAKASA WINATA", 'email': 'dai.rafli.prakasa.winata02@kemenimipas.go.id'},
    {'nama': 'DAIRIBI', 'email': 'dairibi80@kemenimipas.go.id'},
    {'nama': 'DAKSA BIRAWA RASENDRIYA', 'email': 'daksa.birawa.rasendriya03@kemenimipas.go.id'},
    {'nama': 'DALAS MIGUNA', 'email': 'dalas.miguna05@kemenimipas.go.id'},
    {'nama': 'FANDALEN SITUMORANG', 'email': 'dalensit23@gmail.com'},
    {'nama': 'DALIANSYAH SARAGIH', 'email': 'daliansyah.saragih@kemenimipas.go.id'},
    {'nama': 'DALIFA HAYAT', 'email': 'dalifa.hayat@kemenimipas.go.id'},
    {'nama': 'DALIL MAAFI', 'email': 'dalil.maafi00@kemenimipas.go.id'},
    {'nama': 'DALILAH AMNI SIREGAR', 'email': 'dalilah.amni.siregar06@kemenimipas.go.id'},
    {'nama': 'DALIMIN, SH', 'email': 'dalimin69@kemenimipas.go.id'},
    {'nama': 'DALISYADI ADIPURNA', 'email': 'dalisyadi.adipurna@kemenimipas.go.id'},
    {'nama': 'DALRISMAN', 'email': 'dalrisman79@kemenimipas.go.id'},
    {'nama': 'DALWIN HERSON NENOHAI', 'email': 'dalwin.herson@kemenimipas.go.id'},
    {'nama': 'DAMAI ADI PRAYITNO', 'email': 'damai.adi.prayitno93@kemenimipas.go.id'},
    {'nama': 'DAMAIYANTO', 'email': 'damaiyanto92@kemenimipas.go.id'},
    {'nama': 'DAMAN GREGORIUS MANIK', 'email': 'daman.gregorius.manik94@kemenimipas.go.id'},
    {'nama': 'DAMAR AL-FAZRIN', 'email': 'damar.alfazrin05@kemenimipas.go.id'},
    {'nama': 'DAMAR BAGUS PRATIKNO', 'email': 'damar.bagus@kemenimipas.go.id'},
    {'nama': 'DAMAR RIZKI RAMADHAN', 'email': 'damar.rizki@kemenimipas.go.id'},
    {'nama': 'DAMAR ULUNG BINTARA SANTOSA', 'email': 'damar.ulung.bintara.santosa04@kemenimipas.go.id'},
    {'nama': 'DAMARA AGRIVA NAINGGOLAN', 'email': 'damara.agriva.nainggolan02@kemenimipas.go.id'},
    {'nama': 'DAMARDJATI RANGGA PRAMONO', 'email': 'damardjati.rangga.pramono04@kemenimipas.go.id'},
    {'nama': 'DAMARJATI RAMADHAN', 'email': 'damarjati.ramadhan04@kemenimipas.go.id'},
    {'nama': 'DAMAS KRESNA SAPUTRA', 'email': 'damas.kresna.saputra03@kemenimipas.go.id'},
    {'nama': 'DAMAS PRIHANDOKO', 'email': 'damas.prihandoko@kemenimipas.go.id'},
    {'nama': 'DAMASKUS APOLOS NATUN', 'email': 'damaskus.apolos.natun97@kemenimipas.go.id'},
    {'nama': 'DAMAYANTI MARZUKI', 'email': 'damayanti.marzuki89@kemenimipas.go.id'},
    {'nama': 'DAMAYANTI', 'email': 'damayanti@kemenimipas.go.id'},
    {'nama': 'DAME ELISA PRIMA', 'email': 'dame.elisa.prima91@kemenimipas.go.id'},
    {'nama': 'DAMEI ERMAN HARDINASTA.D.', 'email': 'damei.erman.hardinasta.d95@kemenimipas.go.id'},
    {'nama': 'DAMERIA NAINGGOLAN', 'email': 'dameria.nainggolan@kemenimipas.go.id'},
    {'nama': 'DAMERIA SIREGAR', 'email': 'dameria.siregar@kemenimipas.go.id'},
    {'nama': 'drg.. DAMERIA TARIGAN, M.Kes.', 'email': 'dameria.tarigan69@kemenimipas.go.id'},
    {'nama': 'DAMEULI YESSI CLARA SAMOSIR', 'email': 'dameuli.yessi.clara.samosir03@kemenimipas.go.id'},
    {'nama': 'DAMHURI', 'email': 'damhuri67@kemenimipas.go.id'},
    {'nama': 'DAMIAN DE VEUSTER M. DOPO', 'email': 'damian.de.veuster.m.dopo91@kemenimipas.go.id'},
    {'nama': 'DAMIAN DESMONDA LASE', 'email': 'damian.desmonda.lase00@kemenimipas.go.id'},
    {'nama': 'DAMIANA ENDAH APRIYANTI, A.Md', 'email': 'damiana.endah.apriyanti89@kemenimipas.go.id'},
    {'nama': 'DAMIANUS ARDHYNA BINTARA', 'email': 'damianus.ardhyna@kemenimipas.go.id'},
    {'nama': 'DAMIL NUGRAWAN SUCI', 'email': 'damil.nugrawansuci@kemenimipas.go.id'},
    {'nama': 'DAMIRA SUWENITA SEBAYANG', 'email': 'damira.suwenita.sebayang90@kemenimipas.go.id'},
    {'nama': 'DAMKI WAHONGAN', 'email': 'damki.wahongan@kemenimipas.go.id'},
    {'nama': 'DAMPA BUHATMA', 'email': 'dampa.buhatma89@kemenimipas.go.id'},
    {'nama': 'DAMRI', 'email': 'damri70@kemenimipas.go.id'},
    {'nama': 'DAMSI AFRIDA TRAPEN', 'email': 'damsi.afrida.trapen00@kemenimipas.go.id'},
    {'nama': 'DAMSYAH', 'email': 'damsyah69@kemenimipas.go.id'},
    {'nama': 'DANA ALYA UTAMI', 'email': 'dana.alya.utami02@kemenimipas.go.id'},
    {'nama': 'DANA PRADANA', 'email': 'dana.pradana92@kemenimipas.go.id'},
    {'nama': 'DANA WARDANA', 'email': 'dana.wardana@kemenimipas.go.id'},
    {'nama': 'DANA WEDAD ROMANZA', 'email': 'dana.wedad.romanza02@kemenimipas.go.id'},
    {'nama': 'DANAN SETIYANTO', 'email': 'danan.setiyanto83@kemenimipas.go.id'},
    {'nama': 'DANANG AGUNG PRIHATIN', 'email': 'danang.agung837@kemenimipas.go.id'},
    {'nama': 'DANANG ANDRIYANTO', 'email': 'danang.andriyanto@kemenimipas.go.id'},
    {'nama': 'DANANG ARIFIANTO', 'email': 'danang.arifianto@imigrasi.go.id'},
    {'nama': 'DANANG ARIYANTO', 'email': 'danang.ariyanto@kemenimipas.go.id'},
    {'nama': 'DANANG ARY ARDIYANSAH', 'email': 'danang.ary.ardiyansah87@kemenimipas.go.id'},
    {'nama': 'DANANG ARYA WIDYATMAKA', 'email': 'danang.arya87@kemenimipas.go.id'},
    {'nama': 'DANANG ARYADIRAJA', 'email': 'danang.aryadiraja@kemenimipas.go.id'},
    {'nama': 'DANANG ARYO HARYONO, S.Tr.Pas.', 'email': 'danang.aryo.haryono00@kemenimipas.go.id'},
    {'nama': 'DANANG CRISMON PRADANA', 'email': 'danang.crismon.pradana98@kemenimipas.go.id'},
    {'nama': 'DANANG DWI HARYADI', 'email': 'danang.dwi.haryadi88@kemenimipas.go.id'},
    {'nama': 'DANANG DWI ARIFAI', 'email': 'danang.dwi@kemenimipas.go.id'},
    {'nama': 'DANANG EKA PUTRA', 'email': 'danang.eka.putra94@kemenimipas.go.id'},
    {'nama': 'DANANG EKA SAPUTRA', 'email': 'danang.eka.saputra97@kemenimipas.go.id'},
    {'nama': 'DANANG EKA BINTARA', 'email': 'danang.ekabintara@kemenimipas.go.id'},
    {'nama': 'DANANG EKO PRABOWO', 'email': 'danang.eko.prabowo94@kemenimipas.go.id'},
    {'nama': 'DANANG EKO PRASETYO', 'email': 'danang.eko@kemenimipas.go.id'},
    {'nama': 'DANANG IRAWAN', 'email': 'danang.irawan98@kemenimipas.go.id'},
    {'nama': 'DANANG WAHYU NUR ISLAM', 'email': 'danang.islam@kemenimipas.go.id'},
    {'nama': 'DANANG JOYO', 'email': 'danang.joyo98@kemenimipas.go.id'},
    {'nama': 'DANANG KRISDIYANTO', 'email': 'danang.krisdiyanto@kemenimipas.go.id'},
    {'nama': 'DANANG KURNIYANTO', 'email': 'danang.kurniyanto94@kemenimipas.go.id'},
    {'nama': 'DANANG MAHENDRA BAGASKARA', 'email': 'danang.mahendra.bagaskara98@kemenimipas.go.id'},
    {'nama': 'DANANG MAKMUR HADI', 'email': 'danang.makmur@kemenimipas.go.id'},
    {'nama': 'DANANG PANDU WINOTO', 'email': 'Danang.Pandu@kemenimipas.go.id'},
    {'nama': 'DANANG PRASETYO NUGROHO', 'email': 'danang.prasetyo.nugroho05@kemenimipas.go.id'},
    {'nama': 'DANANG PRASETYO UTOMO, S.H', 'email': 'danang.prasetyo@kemenimipas.go.id'},
    {'nama': 'DANANG PRIYO SAMBODO', 'email': 'danang.priyo.sambodo88@kemenimipas.go.id'},
    {'nama': 'DANANG PRIYONO', 'email': 'danang.priyono84@kemenimipas.go.id'},
    {'nama': 'DANANG PURBOWO', 'email': 'danang.purbowo80@kemenimipas.go.id'},
    {'nama': 'DANANG RAHMAN KURNIAWAN', 'email': 'danang.rahman.kurniawan01@kemenimipas.go.id'},
    {'nama': 'DANANG SAPUTRO', 'email': 'danang.saputro83@kemenimipas.go.id'},
    {'nama': 'DANANG SATRIO KINASIH SUSETYO', 'email': 'danang.satrio.kinasih.susetyo00@kemenimipas.go.id'},
    {'nama': 'DANANG SEPTIANTO', 'email': 'danang.septianto91@kemenimipas.go.id'},
    {'nama': 'DANANG SETIAWAN SAPUTRO', 'email': 'danang.setiawan.saputro05@kemenimipas.go.id'},
    {'nama': 'DANANG SETIAWAN', 'email': 'danang.setiawan90@kemenimipas.go.id'},
    {'nama': 'DANANG SETIAWAN', 'email': 'danang.setiawan93@kemenimipas.go.id'},
    {'nama': 'DANANG SIHINGGUSTI', 'email': 'danang.sihinggusti98@kemenimipas.go.id'},
    {'nama': 'DANANG TRI ATMAJA', 'email': 'danang.tri.atmaja01@kemenimipas.go.id'},
    {'nama': 'DANANG TRI ATMAJA', 'email': 'danang.tri.atmaja89@kemenimipas.go.id'},
    {'nama': 'DANANG TRIANTORO', 'email': 'danang.triantoro03@kemenimipas.go.id'},
    {'nama': 'DANANG TRIYANTO', 'email': 'danang.triyanto80@kemenimipas.go.id'},
    {'nama': 'DANANG WAHYU WIBOWO, S.Ak.', 'email': 'danang.wahyu@kemenimipas.go.id'},
    {'nama': 'DANANG WIJANARKO', 'email': 'danang.wijanarko@kemenimipas.go.id'},
    {'nama': 'DANANG WIJANARKO', 'email': 'danang.wijanarko83@kemenimipas.go.id'},
    {'nama': 'DANANG WIJAYA', 'email': 'danang.wijaya89@kemenimipas.go.id'},
    {'nama': 'DANANG WISNU SANTOSO, S.Tr.Pas', 'email': 'danang.wisnu.santoso00@kemenimipas.go.id'},
    {'nama': 'DANANG YOGI OKFARI SANDI', 'email': 'danang.yogi.okfari.sandi92@kemenimipas.go.id'},
    {'nama': 'DANANJAYA AJIE PRATAMA', 'email': 'dananjaya.ajie.pratama93@kemenimipas.go.id'},
    {'nama': 'DANANTO WIBOWO, S.H.', 'email': 'dananto.wibowo@kemenimipas.go.id'},
    {'nama': 'DANAR ANGGIT RAHARJO', 'email': 'danar.anggit.raharjo90@kemenimipas.go.id'},
    {'nama': 'DANAR DONO', 'email': 'danar.dono92@kemenimipas.go.id'},
    {'nama': 'DANAR KURNIA RAMADANU', 'email': 'danar.kurnia.ramadanu02@kemenimipas.go.id'},
    {'nama': 'DANAR PANDU HIDAYAT', 'email': 'danar.pandu.hidayat04@kemenimipas.go.id'},
    {'nama': 'DANASTRI CIPTANINGRUM', 'email': 'danastri.ciptaningrum@kemenimipas.go.id'},
    {'nama': 'DANDI AL FAJAR', 'email': 'dandi.al.fajar98@kemenimipas.go.id'},
    {'nama': 'DANDI ARIYANTO', 'email': 'dandi.ariyanto99@kemenimipas.go.id'},
    {'nama': 'DANDI DANU BRATA', 'email': 'dandi.danu.brata@kemenimipas.go.id'},
    {'nama': 'DANDI FITRAH MAULANA', 'email': 'dandi.fitrah.maulana02@kemenimipas.go.id'},
    {'nama': 'DANDI JANWARSAH', 'email': 'dandi.janwarsah00@kemenimipas.go.id'},
    {'nama': 'DANDI KURNIAWAN', 'email': 'dandi.kurniawan98@kemenimipas.go.id'},
    {'nama': 'DANDI S. MASANG', 'email': 'dandi.masang@kemenimipas.go.id'},
    {'nama': 'DANDI PERMANA', 'email': 'dandi.permana@kemenimipas.go.id'},
    {'nama': 'DANDI PRATAMA HUTAGALUNG', 'email': 'dandi.pratama.hutagalung96@kemenimipas.go.id'},
    {'nama': 'DANDI VIRGIALDO DAMARA', 'email': 'dandi.virgialdo.damara98@kemenimipas.go.id'},
    {'nama': 'DANDI PRASETIYO KUSUMA AJI', 'email': 'dandiprasetiyo@gmail.com'},
    {'nama': 'DANDUN KUSUMA YUDHA', 'email': 'dandun.kusuma@kemenimipas.go.id'},
    {'nama': 'DANDUNG KENCONO', 'email': 'dandung.kencono91@kemenimipas.go.id'},
    {'nama': 'DANDY AGUNG PRATAMA', 'email': 'dandy.agung.pratama91@kemenimipas.go.id'},
    {'nama': 'DANDY ANDRIAN NOORYANTO', 'email': 'dandy.andrian.nooryanto87@kemenimipas.go.id'},
    {'nama': 'DANDY ARIEF PRASETYO, A.Md.Kep', 'email': 'dandy.arief.prasetyo93@kemenimipas.go.id'},
    {'nama': 'DANDY ATTA FAWZY', 'email': 'dandy.atta.fawzy99@kemenimipas.go.id'},
    {'nama': 'DANDY DARMAWAN Z', 'email': 'dandy.darmawan@kemenimipas.go.id'},
    {'nama': 'DANDY DIMAS YUDHISTIRA', 'email': 'dandy.dimas.yudhistira98@kemenimipas.go.id'},
    {'nama': 'DANDY HERLAMBANG', 'email': 'dandy.herlambang@kemenimipas.go.id'},
    {'nama': 'DANDY HERNANDA', 'email': 'dandy.hernanda01@kemenimipas.go.id'},
    {'nama': 'DANDY LAZUARDY', 'email': 'Dandy.Lazuardy@kemenimipas.go.id'},
    {'nama': 'DANDY MUHAMMAD IRZANI', 'email': 'dandy.muhammad.irzani98@kemenimipas.go.id'},
    {'nama': 'I GEDE DANDY SAPUTRA', 'email': 'dandy.saputra@kemenimipas.go.id'},
    {'nama': 'DANDY SATYAGRAHA BURHAN WIRADINATA', 'email': 'dandy.satyagraha.burhan.wiradinata93@kemenimipas.go.id'},
    {'nama': 'DANDY SETIAWAN HUSIN', 'email': 'dandy.setiawan.husin79@kemenimipas.go.id'},
    {'nama': 'DANDY SETYAWAN', 'email': 'dandy.setyawan03@kemenimipas.go.id'},
    {'nama': 'DANDY TRI KURNIAWAN ASLAM', 'email': 'dandy.tri.kurniawan.aslam06@kemenimipas.go.id'},
    {'nama': 'DANDY WAHYU PRATAMA', 'email': 'dandy.wahyu.pratama92@kemenimipas.go.id'},
    {'nama': 'DANEL ANDREAN BOY SUKI', 'email': 'danel.andrean.boy.suki03@kemenimipas.go.id'},
    {'nama': 'DANELIS RONALDO WORABAY', 'email': 'danelis.ronaldo.worabay00@kemenimipas.go.id'},
    {'nama': 'DANELLA SIANTURI', 'email': 'danella.sianturi98@kemenimipas.go.id'},
    {'nama': 'DANELLA ZULKARNAIN', 'email': 'danella.zulkarnain96@kemenimipas.go.id'},
    {'nama': 'DANENDRA APTAQUINNA TIROATMAJA', 'email': 'danendra.aptaquinna.tiroatmaja03@kemenimipas.go.id'},
    {'nama': 'DANER CHRISTY SIGILIPU', 'email': 'daner.christy@kemenimipas.go.id'},
    {'nama': 'DANG RAHMAN', 'email': 'dang.rahman95@kemenimipas.go.id'},
    {'nama': 'DANI ABUZAR', 'email': 'dani.abuzar06@kemenimipas.go.id'},
    {'nama': 'DANI ANJASMARA', 'email': 'dani.anjasmara94@kemenimipas.go.id'},
    {'nama': 'DANI APRIANTO', 'email': 'dani.aprianto80@kemenimipas.go.id'},
    {'nama': 'DANI ARDIANSYAH', 'email': 'dani.ardiansyah98@kemenimipas.go.id'},
    {'nama': 'DANI ARMANDO LUMBAN GAOL', 'email': 'dani.armando.lumban.gaol99@kemenimipas.go.id'},
    {'nama': 'DANI CANDRA PRATAMA', 'email': 'Dani.Candra@kemenimipas.go.id'},
    {'nama': 'DANI DIYAULHAQ', 'email': 'dani.diyaulhaq93@kemenimipas.go.id'},
    {'nama': 'DANI DWI ABIDIRA', 'email': 'dani.dwi.abidira92@kemenimipas.go.id'},
    {'nama': 'DANI EFENDI', 'email': 'dani.efendi@kemenimipas.go.id'},
    {'nama': 'DANI EKA OKTAVIAN', 'email': 'dani.eka.oktavian98@kemenimipas.go.id'},
    {'nama': 'DANI EKO PRASETIYO', 'email': 'dani.eko.prasetiyo99@kemenimipas.go.id'},
    {'nama': 'DANI FAISHAL AKRAM', 'email': 'dani.faishal.akram02@kemenimipas.go.id'},
    {'nama': 'DANI FATUROHMAN', 'email': 'dani.faturohman@kemenimipas.go.id'},
    {'nama': 'DANI HARIWIJAYA', 'email': 'dani.hariwijaya88@kemenimipas.go.id'},
    {'nama': 'DANI HUTABARAT', 'email': 'dani.hutabarat02@kemenimipas.go.id'},
    {'nama': 'DANI ILHAM HIDAYAT', 'email': 'dani.ilham@kemenimipas.go.id'},
    {'nama': 'DANI IRAWAN', 'email': 'dani.irawan@kemenimipas.go.id'},
    {'nama': 'DANI KAMANDAKA', 'email': 'dani.kamandaka03@kemenimipas.go.id'},
    {'nama': 'DANI KURNIANTO PRATAMA', 'email': 'dani.kurnianto.pratama79@kemenimipas.go.id'},
    {'nama': 'DANI KURNIAWAN', 'email': 'dani.kurniawan93@kemenimipas.go.id'},
    {'nama': 'DANI KURNIAWAN', 'email': 'dani.kurniawan981@kemenimipas.go.id'},
    {'nama': 'DANI MAIDA ANDIKA', 'email': 'dani.maida.andika94@kemenimipas.go.id'},
    {'nama': 'DANI MALIK', 'email': 'dani.malik01@kemenimipas.go.id'},
    {'nama': 'DANI MUHAMAD YACHYA', 'email': 'dani.muhamad.yachya77@kemenimipas.go.id'},
    {'nama': 'DANI MULIAWATI IRIANA SUTARYANTO', 'email': 'dani.muliawati@kemenimipas.go.id'},
    {'nama': 'DANI NURCAHYADI', 'email': 'dani.nurcahyadi03@kemenimipas.go.id'},
    {'nama': 'DANI PRAKASA', 'email': 'dani.prakasa@kemenimipas.go.id'},
    {'nama': 'DANI PRAMUDYA SAPUTRA', 'email': 'dani.pramudya.saputra02@kemenimipas.go.id'},
    {'nama': 'DANI PRASETYA HADI', 'email': 'dani.prasetya@kemenimipas.go.id'},
    {'nama': 'DANI PRASTIYO', 'email': 'dani.prastiyo98@kemenimipas.go.id'},
    {'nama': 'DANI RACHMAT SANTOSO', 'email': 'dani.rachmat.santoso99@kemenimipas.go.id'},
    {'nama': 'DANI RAMADHANI', 'email': 'dani.ramadhani99@kemenimipas.go.id'},
    {'nama': 'DANI RAMDANI', 'email': 'dani.ramdani94@kemenimipas.go.id'},
    {'nama': 'DANI RENWARIN', 'email': 'dani.renwarin90@kemenimipas.go.id'},
    {'nama': 'DANI RIDWAN', 'email': 'dani.ridwan79@kemenimipas.go.id'},
    {'nama': 'DANI SETIA', 'email': 'dani.setia79@kemenimipas.go.id'},
    {'nama': 'DANI SETIAJI', 'email': 'dani.setiaji@kemenimipas.go.id'},
    {'nama': 'DANI SUKARTONO NABABAN', 'email': 'dani.sukartono@kemenimipas.go.id'},
    {'nama': 'DANI WINATA ABDUL ROHIM', 'email': 'dani.winata.abdul.rohim92@kemenimipas.go.id'},
    {'nama': 'DANI YEKTI RAHAJENG', 'email': 'dani.yekti@kemenimipas.go.id'},
    {'nama': 'DANIA AKHMAD', 'email': 'dania.akhmad89@kemenimipas.go.id'},
    {'nama': 'DANIAL SAHIB', 'email': 'danial.sahib92@kemenimipas.go.id'},
    {'nama': 'DANIAR NEYRA DESTYA', 'email': 'daniar.neyra@kemenimipas.go.id'},
    {'nama': 'DANIEL AGUS PURWANTO', 'email': 'daniel.agus.purwanto97@kemenimipas.go.id'},
    {'nama': 'DANIEL AGUSTINUS', 'email': 'Daniel.Agustinus@kemenimipas.go.id'},
    {'nama': 'DANIEL ALDIANTA', 'email': 'daniel.aldianta01@kemenimipas.go.id'},
    {'nama': 'DANIEL ANANDA ARDIANSYAH', 'email': 'daniel.ananda.ardiansyah01@kemenimipas.go.id'},
    {'nama': 'DANIEL ANGGI SITORUS', 'email': 'daniel.anggi.sitorus03@kemenimipas.go.id'},
    {'nama': 'DANIEL ANUGERAH PASARIBU', 'email': 'daniel.anugerah@kemenimipas.go.id'},
    {'nama': 'DANIEL ARIS MARULI TUA PASARIBU', 'email': 'daniel.aris.maruli.tua.pasaribu90@kemenimipas.go.id'},
    {'nama': 'DANIEL ARUAN', 'email': 'daniel.aruan80@kemenimipas.go.id'},
    {'nama': 'DANIEL ASMON, SH', 'email': 'daniel.asmon@kemenimipas.go.id'},
    {'nama': 'DANIEL B. J. KREY', 'email': 'daniel.b.j.krey99@kemenimipas.go.id'},
    {'nama': 'DANIEL BAGAS SETYAWAN', 'email': 'daniel.bagas.setyawan92@kemenimipas.go.id'},
    {'nama': 'DANIEL BAKTIAR SITUMORANG', 'email': 'daniel.baktiar.situmorang98@kemenimipas.go.id'},
    {'nama': 'DANIEL BERKAT DAMAI NDRAHA', 'email': 'daniel.berkat@kemenimipas.go.id'},
    {'nama': 'DANIEL BERNANRIVO GONZALES', 'email': 'daniel.bernanrivo.gonzales94@kemenimipas.go.id'},
    {'nama': 'DANIEL BONARA', 'email': 'daniel.bonara71@kemenimipas.go.id'},
    {'nama': 'DANIEL CHARLES', 'email': 'daniel.charles@kemenimipas.go.id'},
    {'nama': 'DANIEL CHRISMANTO SIMATUPANG', 'email': 'daniel.chrismanto@kemenimipas.go.id'},
    {'nama': 'DANIEL CHRISTIAN RICARDO SINAGA', 'email': 'daniel.christian.ricardo.sinaga03@kemenimipas.go.id'},
    {'nama': 'DANIEL CITA WARISMAN NADEAK, S.H', 'email': 'daniel.cita.warisman.nadeak90@kemenimipas.go.id'},
    {'nama': 'DANIEL CRISTOPER SUHARTO', 'email': 'daniel.cristoper.suharto05@kemenimipas.go.id'},
    {'nama': 'DANIEL DEGAI', 'email': 'daniel.degai86@kemenimipas.go.id'},
    {'nama': 'DANIEL DEO KANDA SITUMORANG', 'email': 'daniel.deo.kanda.situmorang00@kemenimipas.go.id'},
    {'nama': 'DANIEL DRIKTUS TARIDISAN', 'email': 'daniel.driktus@kemenimipas.go.id'},
    {'nama': 'DANIEL DWI PUTRA MANIK', 'email': 'daniel.dwi.putra.manik01@kemenimipas.go.id'},
    {'nama': 'DANIEL FERNANDO GULTOM', 'email': 'daniel.fernando.gultom01@kemenimipas.go.id'},
    {'nama': 'DANIEL FERNANDO HUTAPEA', 'email': 'daniel.fernando.hutapea93@kemenimipas.go.id'},
    {'nama': 'DANIEL FERRY SETYAWAN', 'email': 'daniel.ferry.setyawan89@kemenimipas.go.id'},
    {'nama': 'DANIEL FREDERIK MINGGUS MAKANUAY', 'email': 'daniel.frederik.minggus.makanuay99@kemenimipas.go.id'},
    {'nama': 'DANIEL GANINTA SITEPU', 'email': 'daniel.ganinta.sitepu73@kemenimipas.go.id'},
    {'nama': 'DANIEL GILBERTH WAMBRAUW', 'email': 'daniel.gilberth.wambrauw99@kemenimipas.go.id'},
    {'nama': 'DANIEL GINTING', 'email': 'daniel.ginting94@kemenimipas.go.id'},
    {'nama': 'DANIEL IMANUEL MERE', 'email': 'daniel.imanuel.mere00@kemenimipas.go.id'},
    {'nama': 'DANIEL ITAAR', 'email': 'daniel.itaar@kemenimipas.go.id'},
    {'nama': 'DANIEL JAWAK', 'email': 'daniel.jawak03@kemenimipas.go.id'},
    {'nama': 'DANIEL JHON W SIHOMBING', 'email': 'Daniel.Jhon@kemenimipas.go.id'},
    {'nama': 'DANIEL JOSES SAHESE', 'email': 'daniel.joses.sahese00@kemenimipas.go.id'},
    {'nama': 'DANIEL JUNIVER SIAHAAN', 'email': 'daniel.juniver@kemenimipas.go.id'},
    {'nama': 'DANIEL KEVIN PAKPAHAN', 'email': 'daniel.kevin.pakpahan98@kemenimipas.go.id'},
    {'nama': 'DANIEL KOLLOH', 'email': 'daniel.kolloh85@kemenimipas.go.id'},
    {'nama': 'DANIEL KRISTIANTO', 'email': 'daniel.kristianto@kemenimipas.go.id'},
    {'nama': 'DANIEL KRISTIANTO', 'email': 'daniel.kristianto84@kemenimipas.go.id'},
    {'nama': 'DANIEL LELEWA', 'email': 'daniel.lelewa@kemenimipas.go.id'},
    {'nama': 'DANIEL LEONARDO SURBAKTI', 'email': 'daniel.leonardo.surbakti98@kemenimipas.go.id'},
    {'nama': 'DANIEL MAMBAYA', 'email': 'daniel.mambaya@kemenimipas.go.id'},
    {'nama': 'DANIEL MANALU', 'email': 'daniel.manalu97@kemenimipas.go.id'},
    {'nama': 'DANIEL MANAN KASTANYA', 'email': 'daniel.manan@kemenimipas.go.id'},
    {'nama': 'DANIEL SP MARBUN', 'email': 'daniel.marbun@kemenimipas.go.id'},
    {'nama': 'DANIEL MARCHUS PANJAITAN', 'email': 'daniel.marchus.panjaitan98@kemenimipas.go.id'},
    {'nama': 'DANIEL MARGONO SIRAIT', 'email': 'daniel.margono.sirait94@kemenimipas.go.id'},
    {'nama': 'DANIEL MARPAUNG', 'email': 'daniel.marpaung92@kemenimipas.go.id'},
    {'nama': 'DANIEL MARSAHALA SILITONGA', 'email': 'daniel.marsahala.silitonga02@kemenimipas.go.id'},
    {'nama': 'DANIEL MARTIN SINAGA', 'email': 'daniel.martin.sinaga92@kemenimipas.go.id'},
    {'nama': 'DANIEL MAUWA', 'email': 'Daniel.mauwa@kemenimipas.go.id'},
    {'nama': 'DANIEL MURA', 'email': 'daniel.mura@kemenimipas.go.id'},
    {'nama': 'DANIEL NAIBAHO', 'email': 'daniel.naibaho02@kemenimipas.go.id'},
    {'nama': 'DANIEL NIKSON WAYOI', 'email': 'daniel.nikson.wayoi99@kemenimipas.go.id'},
    {'nama': 'DANIEL NOVALDO', 'email': 'daniel.novaldo01@kemenimipas.go.id'},
    {'nama': 'DANIEL OKTOVIANUS MANO', 'email': 'daniel.oktovianus.mano94@kemenimipas.go.id'},
    {'nama': 'DANIEL OLOAN PUTRA SIMAMORA', 'email': 'daniel.oloan@kemenimipas.go.id'},
    {'nama': 'DANIEL PABUNTANG', 'email': 'daniel.pabuntang80@kemenimipas.go.id'},
    {'nama': 'DANIEL PAKA', 'email': 'daniel.paka96@kemenimipas.go.id'},
    {'nama': 'DANIEL PANCA OKTOBENY', 'email': 'daniel.panca.oktobeny92@kemenimipas.go.id'},
    {'nama': 'DANIEL PANGIHUTAN', 'email': 'daniel.pangihutan98@kemenimipas.go.id'},
    {'nama': 'DANIEL PARASIAN PAKPAHAN', 'email': 'daniel.parasian@kemenimipas.go.id'},
    {'nama': 'DANIEL PARULIAN MARTIN LUMBANTOBING', 'email': 'daniel.parulian.martin.lumbantobing02@kemenimipas.go.id'},
    {'nama': 'Daniel Paul Renhard ', 'email': 'daniel.paul.renhard03@kemenimipas.go.id'},
    {'nama': 'DANIEL PAULUS CARLO BARBIER', 'email': 'daniel.paulus@kemenimipas.go.id'},
    {'nama': 'DANIEL PERDAMENTA SEMBIRING', 'email': 'daniel.perdamenta.sembiring01@kemenimipas.go.id'},
    {'nama': 'DANIEL PRAWINANDA', 'email': 'daniel.prawinanda99@kemenimipas.go.id'},
    {'nama': 'DANIEL PUTRA', 'email': 'daniel.putra@kemenimipas.go.id'},
    {'nama': 'DANIEL RAHMADANI', 'email': 'daniel.rahmadani86@kemenimipas.go.id'},
    {'nama': 'DANIEL RICHARDO SIMANJUNTAK', 'email': 'daniel.richardo.simanjuntak99@kemenimipas.go.id'},
    {'nama': 'DANIEL RIZKYAWAN', 'email': 'daniel.rizkyawan01@kemenimipas.go.id'},
    {'nama': 'DANIEL ROBERTO ANIE', 'email': 'daniel.roberto@kemenimipas.go.id'},
    {'nama': 'DANIEL RONALDO', 'email': 'daniel.ronaldo@kemenimipas.go.id'},
    {'nama': 'DANIEL RUDOLF SORONTOU', 'email': 'daniel.rudolf@kemenimipas.go.id'},
    {'nama': 'DANIEL SAPUTRA SITORUS', 'email': 'daniel.saputra.sitorus96@kemenimipas.go.id'},
    {'nama': 'DANIEL SARAGIH', 'email': 'daniel.saragih96@kemenimipas.go.id'},
    {'nama': 'DANIEL SEHAT SIPAYUNG', 'email': 'daniel.sehat.sipayung06@kemenimipas.go.id'},
    {'nama': 'DANIEL SERAN', 'email': 'daniel.seran86@kemenimipas.go.id'},
    {'nama': 'DANIEL SIANTURI', 'email': 'daniel.sianturi87@kemenimipas.go.id'},
    {'nama': 'DANIEL SITINDAON S.H.', 'email': 'daniel.sitindaon@kemenimipas.go.id'},
    {'nama': 'DANIEL STEFANUS JHONI POYK', 'email': 'daniel.stefanus.jhoni.poyk77@kemenimipas.go.id'},
    {'nama': 'DANIEL SURBAKTI, S.H.', 'email': 'daniel.surbakti88@kemenimipas.go.id'},
    {'nama': 'DANIEL SUTANTO PUTRA', 'email': 'daniel.sutanto@kemenimipas.go.id'},
    {'nama': 'DANIEL SYALOOM LUAS SILITONGA', 'email': 'daniel.syaloom.luas.silitonga03@kemenimipas.go.id'},
    {'nama': 'DANIEL TAMPUBOLON', 'email': 'daniel.tampubolon96@kemenimipas.go.id'},
    {'nama': 'DANIEL TEDY PATTUDJU', 'email': 'daniel.tedy.pattudju85@kemenimipas.go.id'},
    {'nama': 'DANIEL TUA REYVALDO SIAHAAN', 'email': 'daniel.tua@kemenimipas.go.id'},
    {'nama': 'DANIEL VINCENT', 'email': 'daniel.vincent92@kemenimipas.go.id'},
    {'nama': 'DANIEL VOLMER DOLOKSARIBU', 'email': 'daniel.volmer@kemenimipas.go.id'},
    {'nama': 'DANIEL WAMBRAUW', 'email': 'Daniel.Wambrauw@kemenimipas.go.id'},
    {'nama': 'DANIEL ZENO ALRIANTONO', 'email': 'daniel.zeno.alriantono00@kemenimipas.go.id'},
    {'nama': 'DANIEL', 'email': 'daniel02@kemenimipas.go.id'},
    {'nama': 'DANIELD JAKOBSON SIMANJUNTAK', 'email': 'danield.jakobson@kemenimipas.go.id'},
    {'nama': 'DANIEL HASIBUAN', 'email': 'danielhasibuan@kemenimipas.go.id'},
    {'nama': 'DANIELI MENDROFA, S.Tr.Im.', 'email': 'danieli.mendrofa00@kemenimipas.go.id'},
    {'nama': 'DANIELTA WINNER BARUS', 'email': 'danielta.winner.barus01@kemenimipas.go.id'},
    {'nama': 'DANI HIDAYAT LUBIS', 'email': 'danihidayatlubis@kemenimipas.go.id'},
    {'nama': 'DANIK PURBAYA', 'email': 'danik.purbaya@kemenimipas.go.id'},
    {'nama': 'DANIK SRI WARDANI', 'email': 'danik.sri.wardani91@kemenimipas.go.id'},
    {'nama': 'DANIL DANIAL', 'email': 'danil.danial@kemenimipas.go.id'},
    {'nama': 'DANIL FERDIANSYAH, S.H', 'email': 'danil.ferdiansyah@kemenimipas.go.id'},
    {'nama': 'M DANIL KUSNANDI', 'email': 'danil.kusnandi@kemenimipas.go.id'},
    {'nama': 'DANIL MANGKAHUANA', 'email': 'danil.mangkahuana90@kemenimipas.go.id'},
    {'nama': 'DANIL MUSAKKIR', 'email': 'danil.musakkir@kemenimipas.go.id'},
    {'nama': 'DANIL NUGROHO', 'email': 'danil.nugroho86@kemenimipas.go.id'},
    {'nama': 'DANIL RACHMAN', 'email': 'danil.rachman@kemenimipas.go.id'},
    {'nama': 'DANIL SEPTIA KASMI', 'email': 'danil.septia.kasmi94@kemenimipas.go.id'},
    {'nama': 'DANIL SEPTIAN PUTRA', 'email': 'danil.septian@kemenimipas.go.id'},
    {'nama': 'DANIL YULIANA', 'email': 'danil.yuliana@kemenimipas.go.id'},
    {'nama': 'DANILO GERAL LAWA', 'email': 'danilo.geral.lawa97@kemenimipas.go.id'},
    {'nama': 'DANILSON', 'email': 'danilson89@kemenimipas.go.id'},
    {'nama': 'Daning Eka Pratiwi', 'email': 'daning.eka.pratiwi96@kemenimipas.go.id'},
    {'nama': 'DANIS PASKAH', 'email': 'danis.paskah86@kemenimipas.go.id'},
    {'nama': 'DANIWIHARYA IDRIS', 'email': 'daniwiharya.idris@kemenimipas.go.id'},
    {'nama': 'DANNAR FARDIAN AFFANDI', 'email': 'dannar.fardian.affandi96@kemenimipas.go.id'},
    {'nama': 'DANNI FERDIANSYAH PRASETYA', 'email': 'danni.ferdiansyah@kemenimipas.go.id'},
    {'nama': 'DANNI RONALDO SIMAMORA', 'email': 'danni.ronaldo@kemenimipas.go.id'},
    {'nama': 'DANNI SASTRIATI SIHOMBING', 'email': 'danni.sastriati.sihombing92@kemenimipas.go.id'},
    {'nama': 'DANNU PRIYANTO', 'email': 'dannu.priyanto@kemenimipas.go.id'},
    {'nama': 'DANNY ARIANA', 'email': 'danny.ariana@kemenimipas.go.id'},
    {'nama': 'DANNY BAHAR', 'email': 'danny.bahar@kemenimipas.go.id'},
    {'nama': 'DANNY DWI KURNIANTO', 'email': 'danny.dwi.kurnianto93@kemenimipas.go.id'},
    {'nama': 'DANNY EKA SAPUTRA', 'email': 'danny.eka.saputra90@kemenimipas.go.id'},
    {'nama': 'DANNY FERIANTO', 'email': 'danny.ferianto81@kemenimipas.go.id'},
    {'nama': 'DANNY PERMANA TARIGAN', 'email': 'danny.permana@kemenimipas.go.id'},
    {'nama': 'DANNY SATYA BRATA', 'email': 'danny.satya@kemenimipas.go.id'},
    {'nama': 'DANNY TRISTIANTO', 'email': 'danny.tristianto93@kemenimipas.go.id'},
    {'nama': 'DANNY YUDHA PRATAMA', 'email': 'danny.yudha.pratama91@kemenimipas.go.id'},
    {'nama': 'DANNYEL', 'email': 'dannyel99@kemenimipas.go.id'},
    {'nama': 'DANNY INDRA MARTOHAP MANULLANG', 'email': 'dannyindra.martohapmanullang@kemenimipas.go.id'},
    {'nama': 'DANO FAUJAN SYAIFUDIN', 'email': 'dano.faujan.syaifudin05@kemenimipas.go.id'},
    {'nama': 'DANRES SIBURIAN', 'email': 'danres.siburian@kemenimipas.go.id'},
    {'nama': 'DANTE HAEKAL ARDIYANTO', 'email': 'dante.haekal.ardiyanto04@kemenimipas.go.id'},
    {'nama': 'DANTI NURSAMSI', 'email': 'danti.nursamsi91@kemenimipas.go.id'},
    {'nama': 'DANU ANGGA SASONO', 'email': 'danu.angga.sasono84@kemenimipas.go.id'},
    {'nama': 'DANU ARDIAN SAPUTRA', 'email': 'danu.ardian@kemenimipas.go.id'},
    {'nama': 'DANU ARDIYANTO', 'email': 'danu.ardiyanto89@kemenimipas.go.id'},
    {'nama': 'DANU ARI WIBOWO', 'email': 'danu.ari.wibowo92@kemenimipas.go.id'},
    {'nama': 'DANU DEWANTORO', 'email': 'danu.dewantoro92@kemenimipas.go.id'},
    {'nama': 'DANU DWI PAMUNGKAS, S.I.Kom', 'email': 'danu.dwi@kemenimipas.go.id'},
    {'nama': 'DANU EKA WARDANA', 'email': 'danu.eka@kemenimipas.go.id'},
    {'nama': 'DANU FAJAR KURNIAWAN', 'email': 'danu.fajar@kemenimipas.go.id'},
    {'nama': 'DANU FIRMANSYAH', 'email': 'danu.firmansyah04@kemenimipas.go.id'},
    {'nama': 'DANU IHSAN ADLIYAN SUPRASNA', 'email': 'danu.ihsan.adliyan.suprasna99@kemenimipas.go.id'},
    {'nama': 'DANU MARDAYANSYAH', 'email': 'danu.mardayansyah04@kemenimipas.go.id'},
    {'nama': 'DANU NUR FAZRI', 'email': 'danu.nur.fazri94@kemenimipas.go.id'},
    {'nama': 'DANU PRAMUSINTA', 'email': 'Danu.pramusinta@kemenimipas.go.id'},
    {'nama': 'DANU PRASMUDIA REBOWO', 'email': 'danu.prasmudia.rebowo04@kemenimipas.go.id'},
    {'nama': 'DANU PRAWITA', 'email': 'danu.prawita@kemenimipas.go.id'},
    {'nama': 'DANU SATRIO HARYANTO', 'email': 'danu.satrio@kemenimipas.go.id'},
    {'nama': 'DANU SERMUMES', 'email': 'danu.sermumes94@kemenimipas.go.id'},
    {'nama': 'DANU SUHADA', 'email': 'danu.suhada98@kemenimipas.go.id'},
    {'nama': 'DANU TRI SETYAWAN', 'email': 'danu.tri.setyawan96@kemenimipas.go.id'},
    {'nama': 'DANU UJI WASONO', 'email': 'danu.uji.wasono83@kemenimipas.go.id'},
    {'nama': 'DANU UMBORO', 'email': 'danu.umboro81@kemenimipas.go.id'},
    {'nama': 'DANUAR RIZKI PRAYUDA', 'email': 'danuar.rizki.prayuda99@kemenimipas.go.id'},
    {'nama': 'DANUR TRI GONGGO', 'email': 'danur.tri.gonggo99@kemenimipas.go.id'},
    {'nama': 'DANVY DIANA NURFILAH RAHMAN', 'email': 'danvy.diana@kemenimipas.go.id'},
    {'nama': 'DANY ANDRIANTO', 'email': 'dany.andrianto90@kemenimipas.go.id'},
    {'nama': 'DANY ASTRIANTO', 'email': 'dany.astrianto@kemenimipas.go.id'},
    {'nama': 'DANY DWI WANTORO', 'email': 'dany.dwi@kemenimipas.go.id'},
    {'nama': 'DANY FADILAH RAMDHANY, S.H', 'email': 'dany.fadilah@kemenimipas.go.id'},
    {'nama': 'DANY FERDIYANTO', 'email': 'dany.ferdiyanto85@kemenimipas.go.id'},
    {'nama': 'DANY FRITSIAN RADJAB', 'email': 'dany.fritsian@kemenimipas.go.id'},
    {'nama': 'DANY HILMI AMRULLAH', 'email': 'dany.hilmi.amrullah98@kemenimipas.go.id'},
    {'nama': 'DANY INDRIANTO', 'email': 'dany.indrianto@kemenimipas.go.id'},
    {'nama': 'DANY IRAWAN', 'email': 'dany.irawan91@kemenimipas.go.id'},
    {'nama': 'DANY LUZA PRIHATMAJA', 'email': 'dany.luza@kemenimipas.go.id'},
    {'nama': 'DANY MARSA SAL SABILA', 'email': 'dany.marsa.sal.sabila01@kemenimipas.go.id'},
    {'nama': 'DANY PRIHADI', 'email': 'dany.prihadi00@kemenimipas.go.id'},
    {'nama': 'DANY RAHMAN', 'email': 'dany.rahman@kemenimipas.go.id'},
    {'nama': 'DANY RIZKI SETIAWAN', 'email': 'dany.rizki.setiawan94@kemenimipas.go.id'},
    {'nama': 'DANY SETIAWAN', 'email': 'dany.setiawan@kemenimipas.go.id'},
    {'nama': 'DANY TRISUNU', 'email': 'Dany.Trisunu@kemenimipas.go.id'},
    {'nama': 'DAONI SINAGA, A.Md', 'email': 'daoni.sinaga@kemenimipas.go.id'},
    {'nama': 'DAPEN HC UTAMA', 'email': 'dapen.hc.utama00@kemenimipas.go.id'},
    {'nama': 'DAPENDRA SAPUTRA', 'email': 'dapendra.saputra92@kemenimipas.go.id'},
    {'nama': 'DAPIT TAUFIQ GINTING', 'email': 'dapit.taufiq@kemenimipas.go.id'},
    {'nama': 'DAPOT PARULIAN SITIO', 'email': 'dapot.parulian@kemenimipas.go.id'},
    {'nama': 'DAPRIL', 'email': 'dapril96@kemenimipas.go.id'},
    {'nama': 'DARA GAUTAMA MEILINA', 'email': 'dara.gautama.meilina00@kemenimipas.go.id'},
    {'nama': 'DARA ISLAMI, S.E', 'email': 'dara.islami@kemenimipas.go.id'},
    {'nama': 'DARA MERITIKA', 'email': 'dara.meritika@kemenimipas.go.id'},
    {'nama': 'DARA PUSPITASARI', 'email': 'dara.puspitasari@kemenimipas.go.id'},
    {'nama': 'DARASHIVA MAHARANI', 'email': 'darashiva.maharani99@kemenimipas.go.id'},
    {'nama': 'DARDAK', 'email': 'dardak69@kemenimipas.go.id'},
    {'nama': 'DARHAM', 'email': 'darham94@kemenimipas.go.id'},
    {'nama': 'DARI AULIA QITAL', 'email': 'dari.qital@kemenimipas.go.id'},
    {'nama': 'DARIA SUHARYONO', 'email': 'daria.suharyono@kemenimipas.go.id'},
    {'nama': 'DARIL SAHENDRA', 'email': 'daril.sahendra01@kemenimipas.go.id'}
]
