contacts = [
    {'nama': 'CATUR SATRIA PAMUNGKAS', 'email': 'catur.satria.pamungkas94@kemenimipas.go.id'},
    {'nama': 'CATUR SETIA AJI', 'email': 'catur.setia.aji97@kemenimipas.go.id'},
    {'nama': 'CATUR SINGGIH PAMUNGKAS', 'email': 'catur.singgih.pamungkas93@kemenimipas.go.id'},
    {'nama': 'CATUR SUGIHARTO', 'email': 'catur.sugiharto@kemenimipas.go.id'},
    {'nama': 'CATUR SUSANINGSIH', 'email': 'catur.susaningsih@kemenimipas.go.id'},
    {'nama': 'CATUR TOMI PAMUNGKAS', 'email': 'catur.tomi.pamungkas99@kemenimipas.go.id'},
    {'nama': 'CATUR WIJANARKO', 'email': 'catur.wijanarko97@kemenimipas.go.id'},
    {'nama': 'CATUR WULANDARI', 'email': 'catur.wulandari92@kemenimipas.go.id'},
    {'nama': 'CATUR YOSSI OLIVIA', 'email': 'catur.yossi.olivia05@kemenimipas.go.id'},
    {'nama': 'CATUR YUDA SETIAWAN', 'email': 'catur.yuda.setiawan86@kemenimipas.go.id'},
    {'nama': 'CATUR YULIWIRANTO', 'email': 'catur.yuliwiranto@kemenimipas.go.id'},
    {'nama': 'CATUR IMAM PRIATMOKO', 'email': 'caturimam.priatmoko@kemenimipas.go.id'},
    {'nama': 'CATURINA CITRA ANUGRAH, SH', 'email': 'caturina.citra@kemenimipas.go.id'},
    {'nama': 'CAVEN JONATHAN', 'email': 'caven.jonathan@kemenimipas.go.id'},
    {'nama': 'CAVIERELL STEVANUS KABAIKAN', 'email': 'cavierell.stevanus.kabaikan05@kemenimipas.go.id'},
    {'nama': 'CAVIN MATTHEU RAPHAEL RAJAGUKGUK', 'email': 'cavin.mattheu.raphael.rajagukguk05@kemenimipas.go.id'},
    {'nama': 'CAYADI', 'email': 'cayadi98@kemenimipas.go.id'},
    {'nama': 'CECE RUDI HARTONO', 'email': 'cece.rudi.hartono68@kemenimipas.go.id'},
    {'nama': 'CECE SOPYANDI', 'email': 'cece.sopyandi@kemenimipas.go.id'},
    {'nama': 'CECEP ADE KUSWARA', 'email': 'cecep.ade@kemenimipas.go.id'},
    {'nama': 'CECEP BAGJA GINANJAR', 'email': 'cecep.bagja.ginanjar98@kemenimipas.go.id'},
    {'nama': 'CECEP CANDRA RAHAYU', 'email': 'cecep.candra@kemenimipas.go.id'},
    {'nama': 'CECEP HENDRA', 'email': 'cecep.hendra87@kemenimipas.go.id'},
    {'nama': 'CECEP MUHAMAD ARDIANTO', 'email': 'cecep.muhamad.ardianto92@kemenimipas.go.id'},
    {'nama': 'CECEP PURNAMA', 'email': 'cecep.purnama92@kemenimipas.go.id'},
    {'nama': 'CECEP RUSMANA', 'email': 'cecep.rusmana77@kemenimipas.go.id'},
    {'nama': 'CECEP SARIPUDIN', 'email': 'cecep.saripudin71@kemenimipas.go.id'},
    {'nama': 'CECEP SUPRIYADI', 'email': 'cecep.supriyadi76@kemenimipas.go.id'},
    {'nama': 'CECEP SUPRIYATNA', 'email': 'cecep.supriyatna@kemenimipas.go.id'},
    {'nama': 'CECEP SUTRISNA', 'email': 'cecep.sutrisna@kemenimipas.go.id'},
    {'nama': 'CECEP TARYANA', 'email': 'cecep.taryana@kemenimipas.go.id'},
    {'nama': 'CECEP WAHYU SAPAAT', 'email': 'cecep.wahyu.sapaat94@kemenimipas.go.id'},
    {'nama': 'CECEP WIDIYANTO', 'email': 'cecep.widiyanto88@kemenimipas.go.id'},
    {'nama': 'AMAR', 'email': 'cecepamar1970@kemenimipas.go.id'},
    {'nama': 'CECILIA DWI HARYANTI PARANSI', 'email': 'cecilia.dwi.haryanti.paransi91@kemenimipas.go.id'},
    {'nama': 'CECILLIA NOVA', 'email': 'cecillia.nova91@kemenimipas.go.id'},
    {'nama': 'CECIRIUS AGIL WIDIANTARA', 'email': 'cecirius.agil.widiantara01@kemenimipas.go.id'},
    {'nama': 'CECY ANA YOSI PUTRI', 'email': 'cecy.ana.yosi.putri06@kemenimipas.go.id'},
    {'nama': 'CELIA SALSABILA', 'email': 'celia.salsabila04@kemenimipas.go.id'},
    {'nama': 'CELVIN PINEM', 'email': 'celvin.pinem@kemenimipas.go.id'},
    {'nama': 'CELVIN SATRIA WANDA', 'email': 'celvin.satria.wanda03@kemenimipas.go.id'},
    {'nama': 'CEMRENI HASTUTI', 'email': 'cemreni.hastuti@kemenimipas.go.id'},
    {'nama': 'CENA AJI RAMADHAN AL RASYID', 'email': 'cena.aji.ramadhan.al.rasyid02@kemenimipas.go.id'},
    {'nama': 'CENDRAWASINTHO', 'email': 'cendrawasintho93@kemenimipas.go.id'},
    {'nama': 'CENDY HARTININGSIH', 'email': 'cendy.hartiningsih97@kemenimipas.go.id'},
    {'nama': 'CENDY PRABOWO SURYANANDA', 'email': 'cendy.prabowo.suryananda91@kemenimipas.go.id'},
    {'nama': 'CENDY', 'email': 'cendy@kemenimipas.go.id'},
    {'nama': 'CENG RAHMAT', 'email': 'ceng.rahmat68@kemenimipas.go.id'},
    {'nama': 'CENO HERSUSETIOKARTIKO', 'email': 'ceno.hersusetiokartiko@kemenimipas.go.id'},
    {'nama': 'CEP AGUNG IRAWAN', 'email': 'cep.agung.irawan04@kemenimipas.go.id'},
    {'nama': 'CEP EKA MOH ABDULAH', 'email': 'cep.eka.moh.abdulah97@kemenimipas.go.id'},
    {'nama': 'CEPI FIKRIADI', 'email': 'cepi.fikriadi93@kemenimipas.go.id'},
    {'nama': 'CEPPI BUDI CAHYANA', 'email': 'ceppi.budi.cahyana93@kemenimipas.go.id'},
    {'nama': 'CEPY ANDIKA RAHADIAN', 'email': 'cepy.andika@kemenimipas.go.id'},
    {'nama': 'CEPY MULYAWAN', 'email': 'cepy.mulyawan@kemenimipas.go.id'},
    {'nama': 'CERI SOLEHUDIN, S.Kom', 'email': 'ceri.solehudin@kemenimipas.go.id'},
    {'nama': 'CEVELONY LIVENZIA PIERIS', 'email': 'cevelony.livenzia.pieris95@kemenimipas.go.id'},
    {'nama': 'CHABELLA RELSA VINANDA THOMAS', 'email': 'chabella.relsa.vinanda.thomas96@kemenimipas.go.id'},
    {'nama': 'CHADARYATI', 'email': 'chadaryati@kemenimipas.go.id'},
    {'nama': 'CHADEX YOHA SURYA NUGRAHA', 'email': 'chadex.yoha@kemenimipas.go.id'},
    {'nama': 'M. CHAEDIR FURQAAN', 'email': 'chaedir.furqaan@kemenimipas.go.id'},
    {'nama': 'CHAERIL ANWAR', 'email': 'chaeril.anwar84@kemenimipas.go.id'},
    {'nama': 'CHAERUL AKHZAN MUHAMMAD TAMSIL', 'email': 'chaerul.akhzan.muhammad.tamsil02@kemenimipas.go.id'},
    {'nama': 'CHAERUL ASWAR', 'email': 'chaerul.aswar99@kemenimipas.go.id'},
    {'nama': 'CHAERUL FAHMI', 'email': 'Chaerul.fahmi@kemenimipas.go.id'},
    {'nama': 'CHAERUL IRFAN', 'email': 'chaerul.irfan85@kemenimipas.go.id'},
    {'nama': 'CHAERUL SEPTIAN CANDRA', 'email': 'chaerul.septian.candra97@kemenimipas.go.id'},
    {'nama': 'CHAERUL UMAM', 'email': 'chaerul.umam01@kemenimipas.go.id'},
    {'nama': 'CHAERUL UMAWAN', 'email': 'chaerul.umawan00@kemenimipas.go.id'},
    {'nama': 'CHAERUNISSA AMAR EKANANDA', 'email': 'chaerunissa.amar.ekananda00@kemenimipas.go.id'},
    {'nama': 'CHAERUNNISA IBRAHIM', 'email': 'chaerunnisa.ibrahim99@kemenimipas.go.id'},
    {'nama': 'CHAFIZAH NUR DIANTARI', 'email': 'chafizah.nur.diantari97@kemenimipas.go.id'},
    {'nama': 'CHAHYO RAHMADIYANTO', 'email': 'chahyo.rahmadiyanto00@kemenimipas.go.id'},
    {'nama': 'CHAIDIR ALI', 'email': 'chaidir.ali93@kemenimipas.go.id'},
    {'nama': 'CHAIDIR ARSYADI', 'email': 'chaidir.arsyadi96@kemenimipas.go.id'},
    {'nama': 'CHAIDIR ASWAR', 'email': 'chaidir.aswar96@kemenimipas.go.id'},
    {'nama': 'CHAIDIR RAHMAN', 'email': 'chaidir.rahman83@kemenimipas.go.id'},
    {'nama': 'CHAIDIR', 'email': 'chaidir85@kemenimipas.go.id'},
    {'nama': 'CHAIRAN HUSEIN USEMAHU', 'email': 'chairan.husein.usemahu05@kemenimipas.go.id'},
    {'nama': 'CHAIRANI RAMADAN', 'email': 'chairani.ramadan@kemenimipas.go.id'},
    {'nama': 'CHAIRI', 'email': 'chairi88@kemenimipas.go.id'},
    {'nama': 'CHAIRIL AKBAR', 'email': 'chairil.akbar99@kemenimipas.go.id'},
    {'nama': 'CHAIRIL ANWAR', 'email': 'chairil.anwar862@kemenimipas.go.id'},
    {'nama': 'CHAIRIL ANWAR', 'email': 'chairil.anwar955@kemenimipas.go.id'},
    {'nama': 'CHAIRIL AZMY', 'email': 'chairil.azmy98@kemenimipas.go.id'},
    {'nama': 'CHAIRIL MEIVANDRI ADLAN TANJUNG', 'email': 'chairil.meivandri@kemenimipas.go.id'},
    {'nama': 'CHAIRIL MUSLIMIN', 'email': 'chairil.muslimin72@kemenimipas.go.id'},
    {'nama': 'CHAIRIN AKHYAR', 'email': 'chairin.akhyar02@kemenimipas.go.id'},
    {'nama': 'CHAIRINA INDOMAN, S.Pd, M.Si.', 'email': 'chairina.indoman89@kemenimipas.go.id'},
    {'nama': 'CHAIRUL AFANDI', 'email': 'chairul.afandi92@kemenimipas.go.id'},
    {'nama': 'CHAIRUL AMIR TITAPELE', 'email': 'chairul.amir@kemenimipas.go.id'},
    {'nama': 'CHAIRUL AMRI PANE', 'email': 'chairul.amri@kemenimipas.go.id'},
    {'nama': 'CHAIRUL ANAM', 'email': 'chairul.anam@kemenimipas.go.id'},
    {'nama': 'CHAIRUL ANWAR', 'email': 'chairul.anwar05@kemenimipas.go.id'},
    {'nama': 'CHAIRUL ANWAR', 'email': 'chairul.anwar701@kemenimipas.go.id'},
    {'nama': 'CHAIRUL ANWAR', 'email': 'chairul.anwar94@kemenimipas.go.id'},
    {'nama': 'CHAIRUL ARIFIN', 'email': 'chairul.arifin02@kemenimipas.go.id'},
    {'nama': 'CHAIRUL AZMI POHAN', 'email': 'chairul.azmi.pohan00@kemenimipas.go.id'},
    {'nama': 'CHAIRUL AZMI', 'email': 'chairul.azmi94@kemenimipas.go.id'},
    {'nama': 'CHAIRUL AZWAR SIREGAR, S.H.', 'email': 'chairul.azwar.siregar85@kemenimipas.go.id'},
    {'nama': 'CHAIRUL EFENDI', 'email': 'chairul.efendi98@kemenimipas.go.id'},
    {'nama': 'CHAIRUL HADI', 'email': 'chairul.hadi@kemenimipas.go.id'},
    {'nama': 'CHAIRUL HUDA AHMAD', 'email': 'chairul.huda.ahmad89@kemenimipas.go.id'},
    {'nama': 'CHAIRUL ICHSAN', 'email': 'chairul.ichsan99@kemenimipas.go.id'},
    {'nama': 'CHAIRUL MALIK', 'email': 'chairul.malik02@kemenimipas.go.id'},
    {'nama': 'CHAIRUL RIJAL', 'email': 'chairul.rijal00@kemenimipas.go.id'},
    {'nama': 'CHAIRUL RIZA M', 'email': 'chairul.riza.m97@kemenimipas.go.id'},
    {'nama': 'CHAIRUL ROZI LUBIS, S.E.', 'email': 'chairul.rozi@kemenimipas.go.id'},
    {'nama': 'CHAIRUL SALEH', 'email': 'chairul.saleh69@kemenimipas.go.id'},
    {'nama': 'CHAIRUL SALEH', 'email': 'chairul.saleh81@kemenimipas.go.id'},
    {'nama': 'CHAIRUL UMAM RAMADHAN', 'email': 'chairul.umam.ramadhan93@kemenimipas.go.id'},
    {'nama': 'CHAIRUL UMAM', 'email': 'chairul.umam89@kemenimipas.go.id'},
    {'nama': 'CHAIRULY', 'email': 'chairuly87@kemenimipas.go.id'},
    {'nama': 'CHAIRUNISA HUMAIRA', 'email': 'chairunisa.humaira03@kemenimipas.go.id'},
    {'nama': 'CHAIRUNISA', 'email': 'chairunisa99@kemenimipas.go.id'},
    {'nama': 'CHAIRUNNAS, S.H.', 'email': 'chairunnas92@kemenimipas.go.id'},
    {'nama': 'CHAIRUNNISA SAMSIA', 'email': 'chairunnisa.samsia00@kemenimipas.go.id'},
    {'nama': 'CHAIRUNNISA', 'email': 'chairunnisa90@kemenimipas.go.id'},
    {'nama': 'CHAIRUNNISA', 'email': 'chairunnisa95@kemenimipas.go.id'},
    {'nama': 'CHAIRUNNISYA', 'email': 'chairunnisya02@kemenimipas.go.id'},
    {'nama': 'CHAIRUR RISKI', 'email': 'chairur.riski95@kemenimipas.go.id'},
    {'nama': 'CHAKTI WIBOWO', 'email': 'chakti.wibowo90@kemenimipas.go.id'},
    {'nama': 'CHALID KURNIAWAN NOERDA', 'email': 'chalid.kurniawan@kemenimipas.go.id'},
    {'nama': 'CHALIDAH NURIAH', 'email': 'chalidah.nuriah78@kemenimipas.go.id'},
    {'nama': 'CHALISTA AQILAH IDELIA', 'email': 'chalista.aqilah.idelia06@kemenimipas.go.id'},
    {'nama': 'CHALVIN ERICSON MASSU', 'email': 'chalvin.ericson.massu96@kemenimipas.go.id'},
    {'nama': 'CHAMIM ABDURAHMAN', 'email': 'chamim.abdurahman93@kemenimipas.go.id'},
    {'nama': '-. CHAN FRANSISCO SARAGIH, -', 'email': 'chan.fransisco.saragih03@kemenimipas.go.id'},
    {'nama': 'CHANDI', 'email': 'chandi95@kemenimipas.go.id'},
    {'nama': 'CHANDRA ADE PRATAMA', 'email': 'chandra.ade.pratama98@kemenimipas.go.id'},
    {'nama': 'CHANDRA ADI PURNAMA', 'email': 'chandra.adi@kemenimipas.go.id'},
    {'nama': 'CHANDRA ADITYA PERMANA', 'email': 'chandra.aditya.permana02@kemenimipas.go.id'},
    {'nama': 'CHANDRA AGUNG', 'email': 'chandra.agung84@kemenimipas.go.id'},
    {'nama': 'CHANDRA AGUS PRIANTOKO', 'email': 'chandra.agus.priantoko80@kemenimipas.go.id'},
    {'nama': 'CHANDRA AGUSTAMA PUTRA', 'email': 'chandra.agustama.putra89@kemenimipas.go.id'},
    {'nama': 'CHANDRA ALICIA PUTRI DJU', 'email': 'chandra.alicia.putri.dju99@kemenimipas.go.id'},
    {'nama': 'CHANDRA BAGUS SATRIAWAN', 'email': 'chandra.bagus.satriawan86@kemenimipas.go.id'},
    {'nama': 'CHANDRA CANIAGO', 'email': 'chandra.caniago@kemenimipas.go.id'},
    {'nama': 'CHANDRA DEWI YULIYANTI', 'email': 'chandra.dewi.yuliyanti78@kemenimipas.go.id'},
    {'nama': 'CHANDRA DIKY TRIYONO', 'email': 'chandra.diky.triyono95@kemenimipas.go.id'},
    {'nama': 'CHANDRA EKA ASPRILLA', 'email': 'chandra.eka.asprilla94@kemenimipas.go.id'},
    {'nama': 'CHANDRA EKA MULYA', 'email': 'chandra.eka.mulya81@kemenimipas.go.id'},
    {'nama': 'CHANDRA GERALD TUHUTERU', 'email': 'chandra.gerald.tuhuteru89@kemenimipas.go.id'},
    {'nama': 'CHANDRA GUNAWAN WAIRISAL', 'email': 'chandra.gunawan.wairisal97@kemenimipas.go.id'},
    {'nama': 'CHANDRA HADINATA', 'email': 'chandra.hadinata@kemenimipas.go.id'},
    {'nama': 'CHANDRA HALIM', 'email': 'chandra.halim05@kemenimipas.go.id'},
    {'nama': 'CHANDRA HASUDUNGAN LUMBAN GAOL', 'email': 'chandra.hasudungan@kemenimipas.go.id'},
    {'nama': 'CHANDRA HERU IRAWAN', 'email': 'chandra.heru.irawan98@kemenimipas.go.id'},
    {'nama': 'CHANDRA HOTMANDUS TURNIP', 'email': 'chandra.hotmandus@kemenimipas.go.id'},
    {'nama': 'CHANDRA IDAYANI', 'email': 'chandra.idayani69@kemenimipas.go.id'},
    {'nama': 'CHANDRA IRAWAN', 'email': 'Chandra.Irawan@kemenimipas.go.id'},
    {'nama': 'CHANDRA KIRANA', 'email': 'chandra.kirana86@kemenimipas.go.id'},
    {'nama': 'CHANDRA KUMALA', 'email': 'chandra.kumala90@kemenimipas.go.id'},
    {'nama': 'CHANDRA KURNIA RAMADHAN', 'email': 'chandra.kurnia.ramadhan95@kemenimipas.go.id'},
    {'nama': 'CHANDRA KURNIA PRATAMA', 'email': 'chandra.kurniapratama@kemenimipas.go.id'},
    {'nama': 'CHANDRA KUSUMA DEWI', 'email': 'chandra.kusuma.dewi88@kemenimipas.go.id'},
    {'nama': 'CHANDRA KUSUMA', 'email': 'chandra.kusuma86@kemenimipas.go.id'},
    {'nama': 'CHANDRA LUHUR PUSPITADI', 'email': 'chandra.luhur@kemenimipas.go.id'},
    {'nama': 'CHANDRA MAHESA', 'email': 'chandra.mahesa@kemenimipas.go.id'},
    {'nama': 'CHANDRA NUR DIANSYAH', 'email': 'chandra.nur.diansyah89@kemenimipas.go.id'},
    {'nama': 'A. CHANDRA NUR HAFID', 'email': 'chandra.nur905@kemenimipas.go.id'},
    {'nama': 'CHANDRA PRAMANA PUTRA', 'email': 'chandra.pramana.putra92@kemenimipas.go.id'},
    {'nama': 'CHANDRA PRANELIUS SURBAKTI', 'email': 'chandra.pranelius@kemenimipas.go.id'},
    {'nama': 'CHANDRA RANTESALU', 'email': 'chandra.rantesalu@kemenimipas.go.id'},
    {'nama': 'CHANDRA SAHAT LUMBANTORUAN', 'email': 'chandra.sahat.lumbantoruan93@kemenimipas.go.id'},
    {'nama': 'CHANDRA SETIAWAN', 'email': 'Chandra.setiawan@kemenimipas.go.id'},
    {'nama': 'CHANDRA SUDARTO', 'email': 'chandra.sudarto@kemenimipas.go.id'},
    {'nama': 'CHANDRA SUJANA', 'email': 'chandra.sujana95@kemenimipas.go.id'},
    {'nama': 'CHANDRA SULISTIA', 'email': 'chandra.sulistia87@kemenimipas.go.id'},
    {'nama': 'CHANDRA SUPRIANSYAH', 'email': 'chandra.supriansyah@kemenimipas.go.id'},
    {'nama': 'CHANDRA SUSPARA ISWAHYUDI', 'email': 'chandra.suspara.iswahyudi94@kemenimipas.go.id'},
    {'nama': 'CHANDRA SYAHPUTRA TARIGAN', 'email': 'Chandra.Syahputra@kemenimipas.go.id'},
    {'nama': 'CHANDRA TIDANARKO', 'email': 'chandra.tidanarko98@kemenimipas.go.id'},
    {'nama': 'CHANDRA TOGATOROP', 'email': 'chandra.togatorop91@kemenimipas.go.id'},
    {'nama': 'CHANDRA UTAMA', 'email': 'Chandra.Utama@kemenimipas.go.id'},
    {'nama': 'CHANDRA WAHYU SATRIA ADIBRATA', 'email': 'chandra.wahyu.satria.adibrata91@kemenimipas.go.id'},
    {'nama': 'CHANDRA WIBAWA CAKTI', 'email': 'chandra.wibawa.cakti95@kemenimipas.go.id'},
    {'nama': 'CHANDRA WIBISONO', 'email': 'chandra.wibisono@kemenimipas.go.id'},
    {'nama': 'CHANDRA WIHARTO', 'email': 'chandra.wiharto@kemenimipas.go.id'},
    {'nama': 'CHANDRA WILIYAMAN', 'email': 'chandra.wiliyaman94@kemenimipas.go.id'},
    {'nama': 'CHANDRA YADI', 'email': 'chandra.yadi@kemenimipas.go.id'},
    {'nama': 'CHANDRA YANTO', 'email': 'chandra.yanto74@kemenimipas.go.id'},
    {'nama': 'CHANDRA ZAKARIA GINTING', 'email': 'chandra.zakaria@kemenimipas.go.id'},
    {'nama': 'CHANDRA', 'email': 'chandra85@kemenimipas.go.id'},
    {'nama': 'CHANDRAN LESTYONO', 'email': 'Chandran.Lestyono@kemenimipas.go.id'},
    {'nama': 'CHANDRIKA ERLA ANGGRIAWAN', 'email': 'chandrika.erla.anggriawan85@kemenimipas.go.id'},
    {'nama': 'CHANDY WILLIAM ELIA NIAN', 'email': 'chandy.william.elia.nian98@kemenimipas.go.id'},
    {'nama': 'CHANISA', 'email': 'chanisa04@kemenimipas.go.id'},
    {'nama': 'CHANTIKA APRILLIA PRATIWI', 'email': 'chantika.aprillia.pratiwi00@kemenimipas.go.id'},
    {'nama': 'CHANTIKA BELINDA PUTRI', 'email': 'chantika.belinda.putri03@kemenimipas.go.id'},
    {'nama': 'CHARAGHITA PROBO YUANTORO', 'email': 'charaghita.probo@kemenimipas.go.id'},
    {'nama': 'CHARANDHI MAHENDRA', 'email': 'charandhi.mahendra97@kemenimipas.go.id'},
    {'nama': 'CHARELDO SATORI, S.H', 'email': 'chareldo.satori@kemenimipas.go.id'},
    {'nama': 'CHARINADIKA TINANG AGUNG PRABOWO', 'email': 'charinadika.tinang.agung.prabowo97@kemenimipas.go.id'},
    {'nama': 'CHARIS HIDAYAT', 'email': 'charis.hidayat90@kemenimipas.go.id'},
    {'nama': 'CHARIS JULIO WIANDRA KAHIKING', 'email': 'charis.julio.wiandra.kahiking02@kemenimipas.go.id'},
    {'nama': 'CHARIS MUNANZAR', 'email': 'charis.munanzar80@kemenimipas.go.id'},
    {'nama': 'CHARIS MUZAMIL', 'email': 'charis.muzamil72@kemenimipas.go.id'},
    {'nama': 'CHARISMA INTAN ENGGAR PANJARIKA', 'email': 'charisma.intan.enggar.panjarika00@kemenimipas.go.id'},
    {'nama': 'CHARISMA VIDYANATA', 'email': 'charisma.vidyanata99@kemenimipas.go.id'},
    {'nama': 'CAHYO HARI UTOMO', 'email': 'chariutomo@kemenimipas.go.id'},
    {'nama': 'CHARLA SUCI NASIA', 'email': 'charla.suci.nasia00@kemenimipas.go.id'},
    {'nama': 'CHARLES ANOM PUTRA GULO', 'email': 'charles.anom@kemenimipas.go.id'},
    {'nama': 'CHARLES CHRISTIAN', 'email': 'Charles.christian@kemenimipas.go.id'},
    {'nama': 'CHARLES FERNANDES', 'email': 'charles.fernandes83@kemenimipas.go.id'},
    {'nama': 'CHARLES FRANSISKUS SIGA', 'email': 'charles.fransiskus.siga99@kemenimipas.go.id'},
    {'nama': 'CHARLES GERD WARELLA', 'email': 'charles.gerd.warella92@kemenimipas.go.id'},
    {'nama': 'CHARLES HENDRIK UROF', 'email': 'charles.hendrik.urof77@kemenimipas.go.id'},
    {'nama': 'CHARLES KORWA', 'email': 'charles.korwa83@kemenimipas.go.id'},
    {'nama': 'CHARLES NOYA', 'email': 'charles.noya@kemenimipas.go.id'},
    {'nama': 'CHARLES SIHITE', 'email': 'charles.sihite70@kemenimipas.go.id'},
    {'nama': 'CHARLES SOLEMAN OPIT', 'email': 'Charles.soleman@kemenimipas.go.id'},
    {'nama': 'CHARLES TALAN', 'email': 'charles.talan96@kemenimipas.go.id'},
    {'nama': 'CHARLI MARTOHAP LUMBAN BATU', 'email': 'charli.martohap.lumban.batu95@kemenimipas.go.id'},
    {'nama': 'CHARLIE FENLIE KOLINUG', 'email': 'charlie.fenlie@kemenimipas.go.id'},
    {'nama': 'CHARLIE RYNALDO NALLE', 'email': 'charlie.rynaldo@kemenimipas.go.id'},
    {'nama': 'CHARLOS MERU BENI', 'email': 'charlos.meru.beni91@kemenimipas.go.id'},
    {'nama': 'CHARLOS ROBERTUS NGAZO', 'email': 'charlos.robertus.ngazo02@kemenimipas.go.id'},
    {'nama': 'CHARLY HUBLE SALUBONGGA', 'email': 'charly.huble@kemenimipas.go.id'},
    {'nama': 'CHARLY IMELDA DA COSTA', 'email': 'charly.imelda.da.costa71@kemenimipas.go.id'},
    {'nama': 'CHARLY OCTOENAS HUTAGALUNG', 'email': 'charly.octoenas.hutagalung92@kemenimipas.go.id'},
    {'nama': 'CHARMEN HILMAN', 'email': 'charmen.hilman82@kemenimipas.go.id'},
    {'nama': 'CHAROLINA ELISABETH BALIBA, S.HI', 'email': 'charolina.elisabeth@kemenimipas.go.id'},
    {'nama': 'CHAROLINA EYDET', 'email': 'charolina.eydet@kemenimipas.go.id'},
    {'nama': 'CHASBULAH RASID', 'email': 'chasbulah.rasid90@kemenimipas.go.id'},
    {'nama': 'CHATERINE IRENE FRANS', 'email': 'chaterine.irene@kemenimipas.go.id'},
    {'nama': 'CHAYA DWI ARIYANTO', 'email': 'chaya.dwi@kemenimipas.go.id'},
    {'nama': 'CHAYATUL MUFLICHA SARI', 'email': 'chayatul.muflicha@kemenimipas.go.id'},
    {'nama': '-. CHAYSAR TRIANDI ELSYA, -', 'email': 'chaysar.triandi.elsya99@kemenimipas.go.id'},
    {'nama': 'CHELNYSIA MIRANDA AULIA', 'email': 'chelnyauliaa@gmail.com'},
    {'nama': 'CHELSA ISMAEL', 'email': 'chelsa.ismael@kemenimipas.go.id'},
    {'nama': 'CHELSEA AERLYA SHEVA AZZAHRA', 'email': 'chelsea.aerlya.sheva.azzahra06@kemenimipas.go.id'},
    {'nama': 'CHELSEA FILLY MANIALUP', 'email': 'chelsea.filly.manialup06@kemenimipas.go.id'},
    {'nama': 'CHELSEA GRACELYA TAMBA', 'email': 'chelsea.gracelya.tamba06@kemenimipas.go.id'},
    {'nama': 'CHELSY WARUNNA MANGGALATUNG', 'email': 'chelsy.warunna.manggalatung99@kemenimipas.go.id'},
    {'nama': 'CHELVIN DEWANTORO', 'email': 'chelvin.dewantoro@kemenimipas.go.id'},
    {'nama': 'CHEP YANUAR AKBAR, S.H.', 'email': 'chep.yanuar@kemenimipas.go.id'},
    {'nama': 'CHEPI BURHANNURDIN', 'email': 'chepi.burhannurdin97@kemenimipas.go.id'},
    {'nama': 'CHEPPY WAHYUDI REYHAN', 'email': 'cheppy.wahyudi.reyhan97@kemenimipas.go.id'},
    {'nama': 'CHERENT MAJESTY CHRISTY PASCA SUGIYANTO PUTRI', 'email': 'cherent.majesty.christy.pasca.sugiyanto.putri03@kemenimipas.go.id'},
    {'nama': 'CHERGIO GIANO PAULO JERAMU', 'email': 'chergio.giano@kemenimipas.go.id'},
    {'nama': 'CHERIANI ADENA BALE DOTO', 'email': 'cheriani.adena.bale.doto93@kemenimipas.go.id'},
    {'nama': 'CHERLISPEN SINAMBELA', 'email': 'cherlispen.sinambela86@kemenimipas.go.id'},
    {'nama': 'CHERLY PUTRI VIVIANI', 'email': 'cherly.putri.viviani05@kemenimipas.go.id'},
    {'nama': 'CHERLY WIDIANITA', 'email': 'cherly.widianita@kemenimipas.go.id'},
    {'nama': 'CHERYVA IRGI FITRIANSYAH', 'email': 'cheryva.irgi.fitriansyah00@kemenimipas.go.id'},
    {'nama': 'CHESSA ADNI INTIFADA', 'email': 'chessa.adni.intifada97@kemenimipas.go.id'},
    {'nama': 'CHESYA NINA LARASANY LOMBOK', 'email': 'chesya.lombok@kemenimipas.go.id'},
    {'nama': 'CHESYANTIO ABRAHAM SIBOLD LOMBOK', 'email': 'chesyantio.abraham.sibold.lombok01@kemenimipas.go.id'},
    {'nama': 'CHEZAR KORLEFURA', 'email': 'chezar.korlefura@kemenimipas.go.id'},
    {'nama': 'CHICCO AHMAD MUTTAQIN', 'email': 'chicco.ahmad@kemenimipas.go.id'},
    {'nama': 'CHICO SETYO ASMORO', 'email': 'chico.setyo.asmoro91@kemenimipas.go.id'},
    {'nama': 'CHINTIA AYU FIRDAUSI HERLI', 'email': 'chientia.ayu@kemenimipas.go.id'},
    {'nama': 'CHIKA ARDHINA PUTRI ANDRIYANI', 'email': 'chika.ardhina.putri.andriyani02@kemenimipas.go.id'},
    {'nama': 'CHIKA PANJI ARDIANSYAH', 'email': 'chika.panji.ardiansyah93@kemenimipas.go.id'},
    {'nama': 'CHIKA SYNTHIA PITALOKA', 'email': 'chika.synthia.pitaloka04@kemenimipas.go.id'},
    {'nama': 'CHIKITA PUTRI LIANI', 'email': 'chikita.putri.liani95@kemenimipas.go.id'},
    {'nama': 'CHILCEN KILAT SOANG', 'email': 'chilcen.kilat.soang94@kemenimipas.go.id'},
    {'nama': 'CHINDI CLEOFATRA, S.H', 'email': 'chindi.cleofatra93@kemenimipas.go.id'},
    {'nama': 'CHINDY GRAFIDIA LARASATI HARAHAP', 'email': 'chindy.grafidia.larasati.harahap90@kemenimipas.go.id'},
    {'nama': ' CHINDY SIFFRI P SITUMORANG', 'email': 'chindy.siffri.p.situmorang93@kemenimipas.go.id'},
    {'nama': 'CHINTIA DWI PUTRI', 'email': 'chintia.dwi.putri@kemenimipas.go.id'},
    {'nama': 'CHINTIA PERMATASARI', 'email': 'chintia.permatasari00@kemenimipas.go.id'},
    {'nama': 'CHINTIA WINDA FATIKA', 'email': 'chintia.winda.fatika02@kemenimipas.go.id'},
    {'nama': 'CHINTYA HERDIYATI AMANDA', 'email': 'chintya.herdiyati.amanda93@kemenimipas.go.id'},
    {'nama': 'CHINTYA LASERA', 'email': 'chintya.lasera93@kemenimipas.go.id'},
    {'nama': 'CHINTYA NAOMI', 'email': 'chintya.naomi98@kemenimipas.go.id'},
    {'nama': 'CHINTYA ROMAITO SIAHAAN', 'email': 'chintya.romaito.siahaan02@kemenimipas.go.id'},
    {'nama': 'CHIPTONO HADIBROTO KETAREN', 'email': 'chiptono.hadibroto.ketaren96@kemenimipas.go.id'},
    {'nama': 'CHIRIONI SOINDEMI', 'email': 'chirioni.soindemi97@kemenimipas.go.id'},
    {'nama': 'CHISMAH KUDUS', 'email': 'chismah.kudus79@kemenimipas.go.id'},
    {'nama': 'CHIZA EVRINA AMADEA', 'email': 'chiza.evrina@kemenimipas.go.id'},
    {'nama': 'CHOIROTUL AMALIA', 'email': 'choirotul.amalia00@kemenimipas.go.id'},
    {'nama': 'CHOIRUL ANAM', 'email': 'choirul.anam@kemenimipas.go.id'},
    {'nama': 'CHOIRUL ANAM', 'email': 'choirul.anam00@kemenimipas.go.id'},
    {'nama': 'CHOIRUL ANAS HADI PUTRA', 'email': 'choirul.anas.hadi.putra95@kemenimipas.go.id'},
    {'nama': 'CHOIRUL ANAS', 'email': 'choirul.anas95@kemenimipas.go.id'},
    {'nama': 'CHOIRUL ANWAR', 'email': 'choirul.anwar96@kemenimipas.go.id'},
    {'nama': 'CHOIRUL HERMAWAN', 'email': 'choirul.hermawan@kemenimipas.go.id'},
    {'nama': 'CHOIRUL MUSLIMAH, S. H.', 'email': 'choirul.muslimah97@kemenimipas.go.id'},
    {'nama': 'CHOIRUL SEKAR ALAM', 'email': 'choirul.sekar.alam88@kemenimipas.go.id'},
    {'nama': 'CHOIRUL UMAM', 'email': 'choirul.umam95@kemenimipas.go.id'},
    {'nama': 'CHOIRUL', 'email': 'choirul67@kemenimipas.go.id'},
    {'nama': 'CHOLIDAH JUANITA NONI FIDMATAN', 'email': 'cholidah.juanita@kemenimipas.go.id'},
    {'nama': 'CHOLIS SEPTIAN', 'email': 'cholis.septian85@kemenimipas.go.id'},
    {'nama': 'CHONI OKTAVIAN ULLYANGGRAENI', 'email': 'choni.oktavian@kemenimipas.go.id'},
    {'nama': 'CHORNELIA YASHELA UTAMA', 'email': 'chornelia.yashela.utama00@kemenimipas.go.id'},
    {'nama': 'CHOUZIN ASRORI', 'email': 'chouzin.asrori92@kemenimipas.go.id'},
    {'nama': 'CHOYRIN KUDUS', 'email': 'choyrin.kudus84@kemenimipas.go.id'},
    {'nama': 'CHRAYEN WILLY ANDERSEN GONI', 'email': 'chrayen.willy@kemenimipas.go.id'},
    {'nama': 'CHRECENTY MELANIA', 'email': 'chrecenty.melania82@kemenimipas.go.id'},
    {'nama': 'CHRESTI CHOESNI', 'email': 'chresti.choesni95@kemenimipas.go.id'},
    {'nama': 'CHRIESTIANS DARMA BAKTI', 'email': 'chriestians.darma.bakti98@kemenimipas.go.id'},
    {'nama': 'CHRIS AGUNG FERDINAND KATZUYA FANGIDAE', 'email': 'chris.agung.ferdinand.katzuya.fangidae96@kemenimipas.go.id'},
    {'nama': 'CHRIS CHORINT VINCENT BERIMAN', 'email': 'chris.chorint.vincent.beriman05@kemenimipas.go.id'},
    {'nama': 'CHRIS DEAN PRATAMA PUTRA', 'email': 'chris.dean.pratama.putra01@kemenimipas.go.id'},
    {'nama': 'CHRIS EVER MARDHITA', 'email': 'chris.ever.mardhita92@kemenimipas.go.id'},
    {'nama': 'CHRIS SETIO WARDOYO', 'email': 'chris.setio.wardoyo88@kemenimipas.go.id'},
    {'nama': 'CHRISFID FIDRIANUS KALUNDANG', 'email': 'chrisfid.fidrianus.kalundang00@kemenimipas.go.id'},
    {'nama': 'CHRISKI JUWANDA', 'email': 'chriski.juwanda91@kemenimipas.go.id'},
    {'nama': 'CHRISLANDO PERDI VERNANDO IHALAUW', 'email': 'chrislando.perdi.vernando.ihalauw02@kemenimipas.go.id'},
    {'nama': 'CHRISLY LADY', 'email': 'chrisly.lady@kemenimipas.go.id'},
    {'nama': 'CHRISMANSYAH SINAGA', 'email': 'chrismansyah.sinaga94@kemenimipas.go.id'},
    {'nama': 'CHRISMELDY MARFEL ANGELO LAPE', 'email': 'chrismeldy.marfel.angelo.lape03@kemenimipas.go.id'},
    {'nama': 'CHRISMON BINSAR PARDAMEAN', 'email': 'chrismon.binsar.pardamean98@kemenimipas.go.id'},
    {'nama': 'CHRISNA DAVIDTIO ASSA', 'email': 'chrisna.davidtio.assa01@kemenimipas.go.id'},
    {'nama': 'CHRISNA DESTANDRI SANGGELORANG', 'email': 'chrisna.destandri.sanggelorang04@kemenimipas.go.id'},
    {'nama': 'CHRISNA ERLANGGA', 'email': 'chrisna.erlangga00@kemenimipas.go.id'},
    {'nama': 'CHRISNAWAN PAKATANA LATHI', 'email': 'chrisnawan.pakatana.lathi88@kemenimipas.go.id'},
    {'nama': 'CHRISOSTOMUS PRINCE ANGEL KIRWELAKUBUN', 'email': 'chrisostomus.prince.angel.kirwelakubun02@kemenimipas.go.id'},
    {'nama': 'CHRISPINUS WOLTER SIGAR', 'email': 'chrispinus.wolter@kemenimipas.go.id'},
    {'nama': 'CHRISSANTONO PAKPAHAN', 'email': 'chrissantono.pakpahan98@kemenimipas.go.id'},
    {'nama': 'CHRIST EVAN MORA DOELI. S', 'email': 'christ.evan@kemenimipas.go.id'},
    {'nama': 'CHRIST INGGREET ANGKASA PUTRI', 'email': 'christ.inggreet@kemenimipas.go.id'},
    {'nama': 'CHRIST ISACC ADHY RIHI', 'email': 'christ.isacc@kemenimipas.go.id'},
    {'nama': 'CHRIST PALAPESSY', 'email': 'christ.palapessy@kemenimipas.go.id'},
    {'nama': 'CHRIST SANDY ANUGRAH GINTING', 'email': 'christ.sandy.anugrah.ginting92@kemenimipas.go.id'},
    {'nama': 'CHRIST SEPTIAN MULYONO', 'email': 'christ.septian@kemenimipas.go.id'},
    {'nama': 'CHRISTA ECHO MARAMPA`', 'email': 'christa.echo@kemenimipas.go.id'},
    {'nama': 'CHRISTAMAYA SHINTA JONO', 'email': 'christamaya.shinta.jono94@kemenimipas.go.id'},
    {'nama': 'CHRISTANTI SULISTYO', 'email': 'christanti.sulistyo70@kemenimipas.go.id'},
    {'nama': 'CHRISTANTO AGUSTIAN SIRAIT', 'email': 'christanto.agustian@kemenimipas.go.id'},
    {'nama': 'CHRISTANTO CAHYO NUGROHO', 'email': 'christanto.cahyo.nugroho86@kemenimipas.go.id'},
    {'nama': 'CHRISTANTO WIJANARKO H.', 'email': 'christanto.wijanarko@kemenkumham.go.id'},
    {'nama': 'CHRISTIAAN JANUAR TJO.E', 'email': 'christiaan.januartjoe@kemenimipas.go.id'},
    {'nama': 'CHRISTIADI', 'email': 'christiadi00@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN ADE SAPUTRA', 'email': 'christian.ade.saputra92@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN ADIPUTRA WIDHARTA', 'email': 'christian.adiputra.widharta91@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN ALEXANDER CHARLES TUMALUN', 'email': 'christian.alexander@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN ANDREW SENDUK, SH', 'email': 'christian.andrew@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN BUDI ANTONI SITEPU, S.Tr.Pas', 'email': 'christian.budi.antoni.sitepu96@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN CARLOS LEONARDO CARANTINO MANDONSA', 'email': 'christian.carlos.leonardo.carantino.mandonsa99@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN CARLOS PARTOGI SIAHAAN', 'email': 'christian.carlos.partogi.siahaan95@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN DAMERO SITOMPUL', 'email': 'christian.damero.sitompul88@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN DELANO L. TOBING', 'email': 'christian.delano.l.tobing87@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN DIZA SAPUTRA', 'email': 'christian.diza.saputra99@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN HABRI WONGKAR', 'email': 'christian.habri@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN HAGANTHA SINULINGGA', 'email': 'christian.hagantha.sinulingga98@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN HUTAMA PUTRA', 'email': 'christian.hutama.putra89@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN IMMANUEL HASUDUNGAN', 'email': 'christian.immanuel@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN IMMANUEL GARRY TAMPUBOLON', 'email': 'christian.immanuel963@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN JUNIOR SALHUTERU', 'email': 'christian.junior.salhuteru02@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN N. KIPPUW, A.Md.Te', 'email': 'christian.kippuw@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN LEFRAN SADUK', 'email': 'christian.lefran.saduk99@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN LUCKY PRASETYO', 'email': 'christian.lucky.prasetyo06@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN MAHARDHIKA CATUR YONAS SEPTIANTO', 'email': 'christian.mahardhika.catur.yonas.septianto85@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN MARCELO WELEM IWANGGIN', 'email': 'christian.marcelo.welem.iwanggin02@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN NATANAEL MAMAHIT', 'email': 'christian.natanael@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN NATANAEL TARIGAN', 'email': 'christian.natanael956@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN N. M. RUMATARAI', 'email': 'christian.nm@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN PATRIOT PUTRA LAOLI', 'email': 'christian.patriot.putra.laoli95@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN PENNA', 'email': 'christian.penna@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN PRANTIGO', 'email': 'christian.prantigo@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN RAMSEN', 'email': 'christian.ramsen05@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN SHANDY VIRLANDO', 'email': 'christian.shandy@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN SINAGA', 'email': 'christian.sinaga@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN SITUMORANG', 'email': 'christian.situmorang98@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN TELAUMBANUA', 'email': 'christian.telaumbanua94@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN TURNIP', 'email': 'christian.turnip93@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN YONATHAN LOKAS', 'email': 'christian.yonathan@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN', 'email': 'christian80@kemenimipas.go.id'},
    {'nama': 'CHRISTIANA RATNANINGSIH', 'email': 'christiana.ratnaningsih72@kemenimipas.go.id'},
    {'nama': 'CHRISTIANA SUMARAH PRASETYANINGTYAS', 'email': 'christiana.sumarahprasetyaningtyas@kemenimipas.go.id'},
    {'nama': 'CHRISTIANA YULIANI', 'email': 'christiana.yuliani81@kemenimipas.go.id'},
    {'nama': 'CHRISTIAN DAVIDSON JERMIAS SIWU, S.H.', 'email': 'christiandavidson.jermiassiwu@kemenimipas.go.id'},
    {'nama': 'CHRISTIANI MARBUN', 'email': 'christiani.marbun92@kemenimipas.go.id'},
    {'nama': 'CHRISTIANI NATALIA SOLANG', 'email': 'christiani.natalia@kemenimipas.go.id'},
    {'nama': 'CHRISTIANI PASKA MANYAMBOUW', 'email': 'christiani.paska.manyambouw05@kemenimipas.go.id'},
    {'nama': 'CHRISTIANI SARIRA', 'email': 'christiani.sarira82@kemenimipas.go.id'},
    {'nama': 'CHRISTIANO R. PURUKAN', 'email': 'christiano.r.purukan95@kemenimipas.go.id'},
    {'nama': 'CHRISTIANTO PUTRA PATTIPEILOHY', 'email': 'christianto.putra.pattipeilohy05@kemenimipas.go.id'},
    {'nama': 'CHRISTIANUS ALLEXANDRO LOGO', 'email': 'christianus.allexandro.logo99@kemenimipas.go.id'},
    {'nama': 'CHRISTIANUS', 'email': 'christianus83@kemenimipas.go.id'},
    {'nama': 'CHRISTIEN AGUSTA MSIREN, S.Si', 'email': 'christien.agusta.msiren88@kemenimipas.go.id'},
    {'nama': 'CHRISTIN ARIYANTI SANTOSO', 'email': 'christin.ariyanti.santoso93@kemenimipas.go.id'},
    {'nama': 'CHRISTIN MARGARETA TANGWAL', 'email': 'christin.margareta@kemenimipas.go.id'},
    {'nama': 'CHRISTIN SARI', 'email': 'christin.sari@kemenimipas.go.id'},
    {'nama': 'CHRISTINA DAMAYANTI ANUGRAHENI', 'email': 'christina.damayanti.anugraheni99@kemenimipas.go.id'},
    {'nama': 'CHRISTINA DWI RATNA MANDALA SARI, A.Md.', 'email': 'christina.dwi@kemenimipas.go.id'},
    {'nama': 'CHRISTINA LENDENTARIANG', 'email': 'christina.lendentariang@kemenimipas.go.id'},
    {'nama': 'CHRISTINA MATITAPUTTY', 'email': 'christina.matitaputty@kemenimipas.go.id'},
    {'nama': 'CHRISTINA', 'email': 'christina99@kemenimipas.go.id'},
    {'nama': 'CHRISTINE ALFRIDA N. JANGKUP', 'email': 'christine.alfrida.n.jangkup96@kemenimipas.go.id'},
    {'nama': 'CHRISTINE ANGELIKA PURBA', 'email': 'christine.angelika.purba99@kemenimipas.go.id'},
    {'nama': 'CHRISTINE DORA ZANDRIK', 'email': 'christine.dora.zandrik95@kemenimipas.go.id'},
    {'nama': 'CHRISTINE GRACE TAMALAWE', 'email': 'christine.grace.tamalawe97@kemenimipas.go.id'},
    {'nama': 'CHRISTINE I.F. NUSSY', 'email': 'christine.i.f.nussy95@kemenimipas.go.id'},
    {'nama': 'CHRISTINE INGKE AMELIA SOMPOTAN', 'email': 'christine.ingke.amelia.sompotan86@kemenimipas.go.id'},
    {'nama': 'CHRISTINE NATALIA HASUGIAN', 'email': 'christine.natalia91@kemenimipas.go.id'},
    {'nama': 'CHRISTINE SABATINI TAMBUNAN', 'email': 'christine.sabatinitambunan@kemenimipas.go.id'},
    {'nama': 'CHRISTIPOL JOSEPH TALLUTA', 'email': 'christipol.joseph@kemenimipas.go.id'},
    {'nama': 'CHRISTISA JEREMY KARO SEKALI', 'email': 'christisa.jeremy.karo.sekali05@kemenimipas.go.id'},
    {'nama': 'CHRISTISON ISAAK MENDOPMA', 'email': 'christison.isaak@kemenimipas.go.id'},
    {'nama': 'CHRISTMAS J M SALAMENA', 'email': 'christmas.salamena@kemenimipas.go.id'},
    {'nama': 'CHRISTO VICTOR NIXON TOAR', 'email': 'christo.victor@kemenimipas.go.id'},
    {'nama': 'CHRISTODEO KUSUMA WIJAYA', 'email': 'christodeo.kusuma@kemenimipas.go.id'},
    {'nama': 'CHRISTOFEL HARAITONA', 'email': 'christofel.haraitona02@kemenimipas.go.id'},
    {'nama': 'CHRISTOFEL MICHAEL WAHANI', 'email': 'christofel.michael.wahani98@kemenimipas.go.id'},
    {'nama': 'CHRISTOFEL PATRIKS UMBOH', 'email': 'christofel.patriks@kemenimipas.go.id'},
    {'nama': 'CHRISTOFER JAYA ZEBUA', 'email': 'christofer.jaya.zebua00@kemenimipas.go.id'},
    {'nama': 'CHRISTOFFEL EDWARD PINANGKAAN, A.Md', 'email': 'christoffel.edward@kemenimipas.go.id'},
    {'nama': 'GILBERTH CHRISTOFFEL', 'email': 'christoffelgilberth@gmail.com'},
    {'nama': 'CHRISTOFFER DWIPUTRA SIANIPAR', 'email': 'christoffer.dwiputra.sianipar88@kemenimipas.go.id'},
    {'nama': 'CHRISTOFORUS MALIK LEIN', 'email': 'christoforus.malik.lein05@kemenimipas.go.id'},
    {'nama': 'CHRISTOPEL MARAMPA ANDILOLO', 'email': 'christopel.marampa.andilolo91@kemenimipas.go.id'},
    {'nama': 'CHRISTOPEL SITOMPUL', 'email': 'christopel.sitompul97@kemenimipas.go.id'},
    {'nama': 'CHRISTOPER A.M.PASARIBU', 'email': 'christoper.a.m.pasaribu05@kemenimipas.go.id'},
    {'nama': '-. CHRISTOPER JUAN RISKI PANJAITAN, -', 'email': 'christoper.juan.riski.panjaitan03@kemenimipas.go.id'},
    {'nama': 'CHRISTOPER', 'email': 'christoper93@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHER AGUSTINUS SILABAN', 'email': 'christopher.agustinus@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHER APRILIO SHEW MARBUN', 'email': 'christopher.aprilio@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHER DYLAN SIALLAGAN', 'email': 'christopher.dylan.siallagan02@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHER FITZGERALD MASSIE', 'email': 'christopher.fitzgerald@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHER MANATAP PURBA', 'email': 'christopher.manatap@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHER SEPTIAN NAINGGOLAN', 'email': 'christopher.septian@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHER TIMOTI TARIGAN', 'email': 'christopher.timoti.tarigan02@kemenimipas.go.id'},
    {'nama': 'CHRISTOPHORUS SANCHA DOMINGGU', 'email': 'christophorus.sancha.dominggu88@kemenimipas.go.id'},
    {'nama': 'CHRISTY JOZEF THENU', 'email': 'christy.jozef@kemenimipas.go.id'},
    {'nama': 'CHRISTY VICTORY POLII', 'email': 'christy.victory@kemenimipas.go.id'},
    {'nama': 'CHRISWANTO SIALLAGAN', 'email': 'chriswanto.siallagan97@kemenimipas.go.id'},
    {'nama': 'CHRISYO MAATITA', 'email': 'chrisyo.maatita96@kemenimipas.go.id'},
    {'nama': 'CHRYSTIAN ADI SAPUTRA', 'email': 'chrystian.adi.saputra99@kemenimipas.go.id'},
    {'nama': 'CHRYSTIAN SILAS SOMBANG', 'email': 'chrystian.silas.sombang00@kemenimipas.go.id'},
    {'nama': 'CHRYSTOFEL MANAEK NADEAK', 'email': 'chrystofel.manaek@kemenimipas.go.id'},
    {'nama': 'CHUCIANTY AYU SRIBANON', 'email': 'chucianty.ayu.sribanon92@kemenimipas.go.id'},
    {'nama': 'CHUFRANSYAH HAKIKI SIMAMORA', 'email': 'chufransyah.hakiki.simamora91@kemenimipas.go.id'},
    {'nama': 'CHURUL ISTICHOMAH', 'email': 'churul.istichomah@kemenimipas.go.id'},
    {'nama': 'CHUSNUL ARIFIN RASUANDAR', 'email': 'chusnul.arifin@kemenimipas.go.id'},
    {'nama': 'CHUSNUL MA`ARIF RANDA BUNGA', 'email': 'chusnul.ma`arif.randa.bunga92@kemenimipas.go.id'},
    {'nama': 'CHUSNUL MAULANA ROFIQ KELIOBAS', 'email': 'chusnul.maulana.rofiq.keliobas95@kemenimipas.go.id'},
    {'nama': 'CHUSNUL WIJAYANTI', 'email': 'chusnul.wijayanti@kemenimipas.go.id'},
    {'nama': 'CHYNDI LAUDHEA', 'email': 'chyndi.laudhea@kemenimipas.go.id'},
    {'nama': 'CHYNTIA ANDREAN', 'email': 'chyntia.andrean93@kemenimipas.go.id'},
    {'nama': 'CHYNTIA DEVI', 'email': 'chyntia.devi@kemenimipas.go.id'},
    {'nama': 'CHYNTIA IDHA AYU SANTIKA, S.Ikom', 'email': 'chyntia.idha@kemenimipas.go.id'},
    {'nama': 'CHYNTIA LEKATOMPESSY', 'email': 'chyntia.lekatompessy83@kemenimipas.go.id'},
    {'nama': 'CHYNTIA PEBRIANA DEWI', 'email': 'chyntia.pebriana@kemenimipas.go.id'},
    {'nama': 'CHYNTIA MONICA SITANGGANG', 'email': 'chyntiamonica@kemenimipas.go.id'},
    {'nama': 'CICI ALWIDA', 'email': 'cici.alwida@kemenimipas.go.id'},
    {'nama': 'CICI APRIYANTI', 'email': 'cici.apriyanti86@kemenimipas.go.id'},
    {'nama': 'CICI WIDIAN SARI, S.IP.', 'email': 'cici.widian.sari93@kemenimipas.go.id'},
    {'nama': 'CICI WIJAYA WAHID', 'email': 'cici.wijaya.wahid92@kemenimipas.go.id'},
    {'nama': 'CICIH KURNIASIH', 'email': 'cicih.kurniasih73@kemenimipas.go.id'},
    {'nama': 'CICILIA SETYAWATI', 'email': 'cicilia.setyawati@kemenimipas.go.id'},
    {'nama': 'CICILIA SRI WIJAYANTI, S.Sos.', 'email': 'cicilia.sri@kemenimipas.go.id'},
    {'nama': 'CICILIA TRIYUNITA SARI', 'email': 'cicilia.triyunita.sari92@kemenimipas.go.id'},
    {'nama': 'CIDY ARDHIAN PUTRA', 'email': 'cidy.ardhian.putra98@kemenimipas.go.id'},
    {'nama': 'CIKAL BAGASTHARA ARFANDY', 'email': 'cikal.bagasthara.arfandy04@kemenimipas.go.id'},
    {'nama': 'CINDE SALSABIIL', 'email': 'cinde.salsabiil00@kemenimipas.go.id'},
    {'nama': 'CINDI ALPINA', 'email': 'cindi.alpina01@kemenimipas.go.id'},
    {'nama': 'CINDRIYASA NUR ANBIA', 'email': 'cindriyasa.nur@kemenimipas.go.id'},
    {'nama': 'CINDY ALDONNA PRATAMA', 'email': 'cindy.aldonna@kemenimipas.go.id'},
    {'nama': 'CINDY AMELIA BR LIMBONG', 'email': 'cindy.amelia.br.limbong05@kemenimipas.go.id'},
    {'nama': 'CINDY ANGGRAINI', 'email': 'cindy.anggraini@kemenimipas.go.id'},
    {'nama': 'CINDY AULIA PEBRIANI', 'email': 'cindy.aulia.pebriani05@kemenimipas.go.id'},
    {'nama': 'CINDY CHRISTI PANGALILA', 'email': 'cindy.christi.pangalila86@kemenimipas.go.id'},
    {'nama': 'CINDY CISILIA HASUGIAN', 'email': 'cindy.cisilia.hasugian04@kemenimipas.go.id'},
    {'nama': 'CINDY DEWI YANTI', 'email': 'cindy.dewi@kemenimipas.go.id'},
    {'nama': 'CINDY EKA SALSABILLAH JUFRI', 'email': 'cindy.eka.salsabillah.jufri00@kemenimipas.go.id'},
    {'nama': 'CINDY FEBRIANTY', 'email': 'cindy.febrianty@kemenimipas.go.id'},
    {'nama': 'CINDY IRENE PIERIS', 'email': 'cindy.irene.pieris95@kemenimipas.go.id'},
    {'nama': 'CINDY JELITA PAULUS', 'email': 'cindy.jelita.paulus98@kemenimipas.go.id'},
    {'nama': 'CINDY KRISTIANTI', 'email': 'cindy.kristianti@kemenimipas.go.id'},
    {'nama': 'CINDY PUSPITA ANGGRAINI', 'email': 'cindy.puspita@kemenimipas.go.id'},
    {'nama': 'CINDY TANIA', 'email': 'cindy.tania99@kemenimipas.go.id'},
    {'nama': 'CINDY TRIYANA SARI', 'email': 'cindy.triyana.sari02@kemenimipas.go.id'},
    {'nama': 'CINDY YOHANNA TAMBUNAN', 'email': 'cindy.yohanna.tambunan98@kemenimipas.go.id'},
    {'nama': 'CINDY YUMIKO KAUNANG', 'email': 'cindy.yumiko@kemenimipas.go.id'},
    {'nama': 'CINDY YUWINDA SARI BR TARIGAN', 'email': 'cindy.yuwinda.sari.br.tarigan96@kemenimipas.go.id'},
    {'nama': 'CINTA WIBOWO', 'email': 'Cinta.Wibowo@kemenimipas.go.id'},
    {'nama': 'CINTA YURI ANANDA LUBIS', 'email': 'cinta.yuri.ananda.lubis03@kemenimipas.go.id'},
    {'nama': 'CINTHIA OKTAVIA NABABAN', 'email': 'cinthia.oktavia@kemenimipas.go.id'},
    {'nama': 'CINTHIA YURIKE MAWIKERE', 'email': 'cinthia.yurike.mawikere93@kemenimipas.go.id'},
    {'nama': 'CINTIA KARTIKA DEWI', 'email': 'cintia.kartika.dewi92@kemenimipas.go.id'},
    {'nama': 'CINTOYA', 'email': 'cintoya@kemenimipas.go.id'},
    {'nama': 'CINTYA RIZKI GUSTIANE', 'email': 'cintya.rizki.gustiane03@kemenimipas.go.id'},
    {'nama': 'CINTYA SARAH LEANITA', 'email': 'cintya.sarah.leanita02@kemenimipas.go.id'},
    {'nama': 'CIPO JUNIANTO SUMBAYAK', 'email': 'cipo.junianto.sumbayak88@kemenimipas.go.id'},
    {'nama': 'CIPRIANO GOMES LELO MALI, S.H.', 'email': 'cipriano.gomes@kemenimipas.go.id'},
    {'nama': 'CIPTA ADHI PURWOKO', 'email': 'cipta.adhi.purwoko96@kemenimipas.go.id'},
    {'nama': 'CIPTA DWI SAPUTRA', 'email': 'cipta.dwi@kemenimipas.go.id'},
    {'nama': 'CIPTA HASIHOLAN NAINGGOLAN', 'email': 'cipta.hasiholan.nainggolan76@kemenimipas.go.id'},
    {'nama': 'CIPTA INDHIARTO', 'email': 'cipta.indhiarto@kemenimipas.go.id'},
    {'nama': 'CIPTA MOHAMMAD SEPTIAN', 'email': 'cipta.mohammad@kemenimipas.go.id'},
    {'nama': 'CIPTA PERDANA WIJAYA', 'email': 'cipta.perdana.wijaya90@kemenimipas.go.id'},
    {'nama': 'CIPTA PRIMA TRIHARTADI', 'email': 'cipta.prima.trihartadi86@kemenimipas.go.id'},
    {'nama': 'CIPTA WAHYU PUTRA', 'email': 'cipta.wahyu.putra00@kemenimipas.go.id'},
    {'nama': 'CIPTO EDY', 'email': 'Cipto.Edy@kemenimipas.go.id'},
    {'nama': 'CIPTO MARTONO', 'email': 'cipto.martono82@kemenimipas.go.id'},
    {'nama': 'CIPTO YUWONO', 'email': 'cipto.yuwono88@kemenimipas.go.id'},
    {'nama': 'CIPTO', 'email': 'cipto78@kemenimipas.go.id'},
    {'nama': 'CIPTO', 'email': 'cipto91@kemenimipas.go.id'},
    {'nama': 'CITA RIMBAWATI', 'email': 'cita.rimbawati94@kemenimipas.go.id'},
    {'nama': 'CITO SUMARJO', 'email': 'cito.sumarjo81@kemenimipas.go.id'},
    {'nama': 'CITRA ADHI PRADHANA', 'email': 'citra.adhi@kemenimipas.go.id'},
    {'nama': 'CITRA ADITYADEWI', 'email': 'citra.adityadewi87@kemenimipas.go.id'},
    {'nama': 'CITRA ANDIAN', 'email': 'citra.andian04@kemenimipas.go.id'},
    {'nama': 'CITRA ANNISA', 'email': 'citra.annisa@kemenimipas.go.id'},
    {'nama': 'CITRA AWANIS GHAISANI', 'email': 'citra.awanis@kemenimipas.go.id'},
    {'nama': 'CITRA AYU ROSMALA', 'email': 'citra.ayu@kemenimipas.go.id'},
    {'nama': 'CITRA AYU PRADANA', 'email': 'citra.ayu969@kemenimipas.go.id'},
    {'nama': 'CITRA AYUNI GOBEL', 'email': 'citra.ayuni@kemenimipas.go.id'},
    {'nama': 'CITRA BERLY, S.H.', 'email': 'citra.berly83@kemenimipas.go.id'},
    {'nama': 'CITRA DARINI WIDAYANTI', 'email': 'citra.darini@kemenimipas.go.id'},
    {'nama': 'CITRA DEWI NOVITASARI', 'email': 'citra.dewi.novitasari92@kemenimipas.go.id'},
    {'nama': 'CITRA DEWI SAMAUN', 'email': 'citra.dewi.samaun93@kemenimipas.go.id'},
    {'nama': 'CITRA ENDRA KUSUMA', 'email': 'citra.endra@kemenimipas.go.id'},
    {'nama': 'CITRA ERA DEPY', 'email': 'citra.era@kemenimipas.go.id'},
    {'nama': 'CITRA FIRZA AZIZAH', 'email': 'citra.firza.azizah00@kemenimipas.go.id'},
    {'nama': 'CITRA HAPPY GULTOM', 'email': 'citra.happy.gultom94@kemenimipas.go.id'},
    {'nama': 'CITRA IMAN WIBISANA', 'email': 'citra.iman@kemenimipas.go.id'},
    {'nama': 'CITRA KURNIATI', 'email': 'citra.kurniati84@kemenimipas.go.id'},
    {'nama': 'CITRA LARAS MUTIARA', 'email': 'citra.laras.mutiara88@kemenimipas.go.id'},
    {'nama': 'CITRA LESTARI PUTRI, S.E., M.Si.', 'email': 'citra.lestari.putri94@kemenimipas.go.id'},
    {'nama': 'CITRA MEISHA SIMBOLON', 'email': 'citra.meisha.simbolon92@kemenimipas.go.id'},
    {'nama': 'CITRA MERINAWATI', 'email': 'citra.merinawati@kemenimipas.go.id'},
    {'nama': 'CITRA NARA SUPRIYONO PUTRI', 'email': 'citra.nara.supriyono.putri05@kemenimipas.go.id'},
    {'nama': 'CITRA NURJANAH', 'email': 'citra.nurjanah00@kemenimipas.go.id'},
    {'nama': 'CITRA NURVIRAWATI', 'email': 'citra.nurvirawati87@kemenimipas.go.id'},
    {'nama': 'CITRA NURWINDA', 'email': 'citra.nurwinda00@kemenimipas.go.id'},
    {'nama': 'CITRA PERMATASARI SIMAMORA', 'email': 'citra.permatasari.simamora94@kemenimipas.go.id'},
    {'nama': 'CITRA PRATIWI TRI LESTARI', 'email': 'citra.pratiwi.tri.lestari05@kemenimipas.go.id'},
    {'nama': 'CITRA SRI ARYANINGRUM ZAI', 'email': 'citra.sri.aryaningrum.zai99@kemenimipas.go.id'},
    {'nama': 'CITRA SUHENDRA, S.H.', 'email': 'citra.suhendra@kemenimipas.go.id'},
    {'nama': 'CITRA TRI NALURITA', 'email': 'citra.tri.nalurita96@kemenimipas.go.id'},
    {'nama': 'CITRA WULAN ASTUTI', 'email': 'citra.wulan@kemenimipas.go.id'},
    {'nama': 'CITRA WULANDARI', 'email': 'citra.wulandari@kemenimipas.go.id'},
    {'nama': 'CITRAKA DAFFA RADITYA', 'email': 'citraka.daffa.raditya05@kemenimipas.go.id'},
    {'nama': 'CITRAWATI TIRING', 'email': 'citrawati.tiring@kemenimipas.go.id'},
    {'nama': 'CITRO TAMBA', 'email': 'citro.tamba97@kemenimipas.go.id'},
    {'nama': 'CITTA AYUDITA', 'email': 'citta.ayudita97@kemenimipas.go.id'},
    {'nama': 'CIWOGALATIA', 'email': 'ciwogalatia81@kemenimipas.go.id'},
    {'nama': 'CLAODIA NARASINDHI', 'email': 'claodia.narasindhi@kemenimipas.go.id'},
    {'nama': 'CLARA MENTARI GRACIA LENGKEY', 'email': 'clara.mentari.gracia.lengkey03@kemenimipas.go.id'},
    {'nama': 'CLARA RENNY KARTIKA', 'email': 'clara.renny.kartika97@kemenimipas.go.id'},
    {'nama': 'CLARA SARAGIH', 'email': 'clara.saragih06@kemenimipas.go.id'},
    {'nama': 'CLARA URSULA OKTOVINA KADIWARU', 'email': 'clara.ursula@kemenimipas.go.id'},
    {'nama': 'CLARA VANESIA BANGUN', 'email': 'clara.vanesia.bangun96@kemenimipas.go.id'},
    {'nama': 'CLARA WIDELA, S.E.', 'email': 'clara.widela92@kemenimipas.go.id'},
    {'nama': 'CLARINTA SIMANGUNSONG', 'email': 'clarinta.simangunsong99@kemenimipas.go.id'},
    {'nama': 'CLARISA SULYOHANA HANGGAWALI', 'email': 'clarisa.sulyohana.hanggawali05@kemenimipas.go.id'},
    {'nama': 'CLARISSA AYU NUGRAHA', 'email': 'clarissa.ayu.nugraha98@kemenimipas.go.id'},
    {'nama': 'CLARISSA WIDYA PRATIWI', 'email': 'clarissa.widya.pratiwi06@kemenimipas.go.id'},
    {'nama': 'CLAUDHIA NESTI SALINDEHO', 'email': 'claudhia.nesti.salindeho94@kemenimipas.go.id'},
    {'nama': 'CLAUDIA ANDRIANI PRAMONO', 'email': 'claudia.andriani@kemenimipas.go.id'},
    {'nama': 'CLAUDIA BEBY GUSRINDA', 'email': 'claudia.beby@kemenimipas.go.id'},
    {'nama': 'CLAUDIA LAKSASMITA, S.Tr.Pas.', 'email': 'claudia.laksasmita01@kemenimipas.go.id'},
    {'nama': 'CLAUDIA MARANATHA ARUAN', 'email': 'claudia.maranatha@kemenimipas.go.id'},
    {'nama': 'CLAUDIA MARIA ELMONIA', 'email': 'claudia.maria.elmonia92@kemenimipas.go.id'},
    {'nama': 'CLAUDIA MELISSA SALHUTERU', 'email': 'claudia.melissa@kemenimipas.go.id'},
    {'nama': 'CLAUDIA OLIVIA SAMBERI, S.I.Kom', 'email': 'claudia.olivia.samberi98@kemenimipas.go.id'},
    {'nama': 'CLAUDIA URSULA VIOLENT OCTRICYA', 'email': 'claudia.ursula@kemenimipas.go.id'},
    {'nama': 'CLAUDIO FABRIZIO MALIANGKAY', 'email': 'claudio.fabrizio.maliangkay96@kemenimipas.go.id'},
    {'nama': 'CLAUDIO FERNANDO BAITANU', 'email': 'claudio.fernando@kemenimipas.go.id'},
    {'nama': 'CLAUDIUS LANDO', 'email': 'claudius.lando98@kemenimipas.go.id'},
    {'nama': 'CLAUDIUS PRASETYO TETONG', 'email': 'claudius.prasetyo.tetong00@kemenimipas.go.id'},
    {'nama': 'CLAUDIYANA FITRIAH', 'email': 'claudiyana.fitriah@kemenimipas.go.id'},
    {'nama': 'CLAUDYA GEOFINA GENDITA', 'email': 'claudya.geofina@kemenimipas.go.id'},
    {'nama': 'CLAUDYA VIRGINIA REA', 'email': 'claudya.virginia.reaia.rea96@kemenimipas.go.id'},
    {'nama': 'CLEINE GAVRILA DELMORA ADAM', 'email': 'cleine.gavrila.delmora.adam06@kemenimipas.go.id'},
    {'nama': 'CLEMENCY GUNAWAN', 'email': 'clemency.gunawan77@kemenimipas.go.id'},
    {'nama': 'CLIF SEBASTIAN DJEDDIN', 'email': 'clif.sebastian@kemenimipas.go.id'},
    {'nama': 'CLIFORD THEOFANI LANGI', 'email': 'cliford.theofani.langi95@kemenimipas.go.id'},
    {'nama': 'CLINTON ODY FOLSEN AMBARITA', 'email': 'clinton.ody.folsen.ambarita95@kemenimipas.go.id'},
    {'nama': 'CLINTON PANDAPOTAN LUBIS', 'email': 'clinton.pandapotan.lubis05@kemenimipas.go.id'},
    {'nama': 'COK RADITYA', 'email': 'Cok.Raditya@kemenimipas.go.id'},
    {'nama': 'COKORDA GDE PRABAWA DIPUTRA', 'email': 'cokorda.gde@kemenimipas.go.id'},
    {'nama': 'COKORDA GEDE BAGUS DHARMARUPAWAN, SH', 'email': 'cokorda.gede@kemenimipas.go.id'},
    {'nama': 'COKORDA ISTRI EKA DILA SAFITRI, S.M.', 'email': 'cokorda.istri@kemenimipas.go.id'},
    {'nama': 'COKORDA WISNU MAHA ADITYA', 'email': 'Cokorda.Wisnu@kemenimipas.go.id'},
    {'nama': 'COKRO SETYOWIBOWO', 'email': 'cokro.setyowibowo@kemenimipas.go.id'},
    {'nama': 'COKY BOY SYAH', 'email': 'coky.boy.syah68@kemenimipas.go.id'},
    {'nama': 'COKY NGOLU CHRISTOFFEL MANULLANG', 'email': 'coky.ngolu@kemenimipas.go.id'},
    {'nama': 'COMI HENDARISWATI', 'email': 'comi.hendariswati@kemenimipas.go.id'},
    {'nama': 'CONIA AZKADINA', 'email': 'conia.azkadina03@kemenimipas.go.id'},
    {'nama': 'I WAYAN PRASETYA LENCANA', 'email': 'contact.lencanaprasetya@kemenimipas.go.id'},
    {'nama': 'COOKY MS SIMANJUNTAK', 'email': 'Cookysimanjuntak@kemenimipas.go.id'},
    {'nama': 'CORESY PETRA HEIN TANATY', 'email': 'coresy.petra.hein.tanaty93@kemenimipas.go.id'},
    {'nama': 'CORI FRENTINA TAMPUBOLON, AM.Keb', 'email': 'Corifrentina@kemenimipas.go.id'},
    {'nama': 'CORLIN WENNO', 'email': 'corlin.wenno79@kemenimipas.go.id'},
    {'nama': 'CORNELIS APRIAN ABINENO', 'email': 'cornelis.aprian.abineno92@kemenimipas.go.id'},
    {'nama': 'CORNELIUS AGATHA GEA', 'email': 'cornelius.agatha.gea99@kemenimipas.go.id'},
    {'nama': 'CORNELIUS BATU', 'email': 'cornelius.batu@kemenimipas.go.id'},
    {'nama': 'CORNELIUS EDON', 'email': 'cornelius.edon84@kemenimipas.go.id'},
    {'nama': 'CORRIE FITRIAH', 'email': 'corrie.fitriah@kemenimipas.go.id'},
    {'nama': 'CORRY ALIFIANA DIRGANTARI', 'email': 'corry.alifiana.dirgantari02@kemenimipas.go.id'},
    {'nama': 'CORRYNA ALLEN', 'email': 'corryna.allen@kemenimipas.go.id'},
    {'nama': 'CORY ANGGARA', 'email': 'cory.anggara98@kemenimipas.go.id'},
    {'nama': 'CORY PALUPI', 'email': 'cory.palupi94@kemenimipas.go.id'},
    {'nama': '-. COSMAS JOHANES NEKO, -', 'email': 'cosmas.johanes.neko03@kemenimipas.go.id'},
    {'nama': 'CRESCENTIANUS CATUR APRIYANTO Amd.Im., SH., M.Hum', 'email': 'crescentianus.catur@kemenimipas.go.id'},
    {'nama': 'CRILLY AVELY WONGKAR', 'email': 'crilly.avely@kemenimipas.go.id'},
    {'nama': 'CRIONY BAYUWENI WABANG', 'email': 'criony.bayuweni.wabang99@kemenimipas.go.id'},
    {'nama': 'CRISMAN HANEYANTON SIMANUNGKALIT', 'email': 'crisman.haneyanton.simanungkalit96@kemenimipas.go.id'},
    {'nama': 'CRISMANTO PARULI SAMOSIR', 'email': 'crismanto.paruli@kemenimipas.go.id'},
    {'nama': 'CRIST YOEL MANIHURUK', 'email': 'crist.yoel.manihuruk02@kemenimipas.go.id'},
    {'nama': 'CRISTHINE MALIANDI', 'email': 'cristhine.maliandi@kemenimipas.go.id'},
    {'nama': 'CRISTI NORIET SUMENDA', 'email': 'cristi.noriet@kemenimipas.go.id'},
    {'nama': 'CRISTIAN GIDION MUNTHE', 'email': 'cristian.gidion.munthe06@kemenimipas.go.id'},
    {'nama': 'CRISTIAN H.P. SIALLAGAN', 'email': 'cristian.h.p.siallagan97@kemenimipas.go.id'},
    {'nama': 'CRISTIAN PRADANA', 'email': 'cristian.pradana96@kemenimipas.go.id'},
    {'nama': 'CRISTIAN RIZKY AGUS MARPAUNG', 'email': 'cristian.rizky.agus.marpaung00@kemenimipas.go.id'},
    {'nama': 'CRISTIANDO ROMA PARASIAN', 'email': 'cristiando.roma@kemenimipas.go.id'},
    {'nama': "CRISTIANTO PACE ANDERSON TA'EK", 'email': 'cristianto.pace.anderson.taek95@kemenimipas.go.id'},
    {'nama': 'CRISTIN BLESSY BIRINGAN', 'email': 'cristin.blessy@kemenimipas.go.id'},
    {'nama': 'CRISTINA ENTE', 'email': 'cristina.ente@kemenimipas.go.id'},
    {'nama': 'CRISTO GAIZKA KANALUNG', 'email': 'cristo.gaizka.kanalung01@kemenimipas.go.id'},
    {'nama': 'CRISTO R.P SIMANJUNTAK', 'email': 'cristo.r.p.simanjuntak03@kemenimipas.go.id'},
    {'nama': 'CRISTOFHER ALFONSO LESILOLO', 'email': 'cristofher.alfonso.lesilolo00@kemenimipas.go.id'},
    {'nama': 'CRISTOPEL GULTOM', 'email': 'cristopel.gultom@kemenimipas.go.id'},
    {'nama': 'CRISTOPEL SILABAN', 'email': 'cristopel.silaban04@kemenimipas.go.id'},
    {'nama': 'CRISTY M.SIMARMATA', 'email': 'cristy.m.simarmata06@kemenimipas.go.id'},
    {'nama': 'CRISYE CAROLIN HARIANJA', 'email': 'crisye.carolin@kemenimipas.go.id'},
    {'nama': 'CRYSTAL GREEN', 'email': 'crystal.green90@kemenimipas.go.id'},
    {'nama': 'CUCU JUBAEDAH', 'email': 'cucu.jubaedah82@kemenimipas.go.id'},
    {'nama': 'CUCU NURYANA', 'email': 'cucu.nuryana94@kemenimipas.go.id'},
    {'nama': 'CUCU SUPRIATNA', 'email': 'cucu.supriatna69@kemenimipas.go.id'},
    {'nama': 'CUN SUDIHARTO', 'email': 'Cun.Sudiharto@kemenimipas.go.id'},
    {'nama': 'CUT AINAL MARDHIAH', 'email': 'cut.ainal.mardhiah75@kemenimipas.go.id'},
    {'nama': 'CUT AMELIA ARUMI, S.H', 'email': 'cut.amelia.arumi82@kemenimipas.go.id'},
    {'nama': 'CUT ANA DARMAWAN', 'email': 'Cut.Ana@kemenimipas.go.id'},
    {'nama': 'CUT ANIS SYAFA', 'email': 'cut.anis.syafa99@kemenimipas.go.id'},
    {'nama': 'CUT ARINA FAUZA, A.Md., S.E.', 'email': 'cut.arina.fauza90@kemenimipas.go.id'},
    {'nama': 'CUT AURORA ANASTASIA', 'email': 'cut.aurora.anastasia@kemenimipas.go.id'},
    {'nama': 'CUT DINI MANDASARI', 'email': 'cut.dini@kemenimipas.go.id'},
    {'nama': 'CUT ELIZA ANGGRAINI', 'email': 'cut.eliza@kemenimipas.go.id'},
    {'nama': 'CUT ERIKA INDRIYANI', 'email': 'cut.erika.indriyani81@kemenimipas.go.id'},
    {'nama': 'CUT FARA MEUTIA', 'email': 'cut.fara.meutia98@kemenimipas.go.id'},
    {'nama': 'CUT FARIDAH', 'email': 'cut.faridah@kemenimipas.go.id'},
    {'nama': 'CUT HADAYA SYAKIRAH', 'email': 'cut.hadaya.syakirah05@kemenimipas.go.id'},
    {'nama': 'CUT HUSNA CHALIDA ZULFA', 'email': 'cut.husna.chalida.zulfa00@kemenimipas.go.id'},
    {'nama': 'CUT INTAN KEUMALA', 'email': 'cut.intan.keumala94@kemenimipas.go.id'},
    {'nama': 'CUT IRMA FITRIKA', 'email': 'cut.irma.fitrika75@kemenimipas.go.id'},
    {'nama': 'CUT LIZA SAHRA', 'email': 'cut.liza.sahra94@kemenimipas.go.id'},
    {'nama': 'CUT LUTPIANTI AYU ROSIAH', 'email': 'cut.lutpianti@kemenimipas.go.id'},
    {'nama': 'CUT MAYA IRNA', 'email': 'cut.maya.irna89@kemenimipas.go.id'},
    {'nama': 'CUT MEURAH KHALID', 'email': 'cut.meurah.khalid69@kemenimipas.go.id'},
    {'nama': 'CUT NAZWA SAHIRA', 'email': 'cut.nazwa.sahira05@kemenimipas.go.id'},
    {'nama': 'CUT NOVITASARI', 'email': 'cut.novitasari92@kemenimipas.go.id'},
    {'nama': 'CUT NUR AMNA, A.Md', 'email': 'cut.nur@kemenimipas.go.id'},
    {'nama': 'CUT PUTROE GAMBANG, S.H', 'email': 'cut.putroe.gambang87@kemenimipas.go.id'},
    {'nama': 'CUT RAUDLATUL JANNAH TS', 'email': 'cut.raudlatul@kemenimipas.go.id'},
    {'nama': 'CUT RISKA AINY', 'email': 'cut.riska.ainy99@kemenimipas.go.id'},
    {'nama': 'NYAK CUT SAKARIMA RAHMAH', 'email': 'Cut.Sakarima@kemenimipas.go.id'},
    {'nama': 'CUT SRI BAHAGIANI TS', 'email': 'cut.sri.bahagiani.ts85@kemenimipas.go.id'},
    {'nama': 'CUT SUATIKA', 'email': 'cut.suatika@kemenimipas.go.id'},
    {'nama': 'CUT TRISCA ANDAYANI', 'email': 'cut.trisca.andayani77@kemenimipas.go.id'},
    {'nama': 'CUT VIADNA VIRA', 'email': 'cut.viadna.vira90@kemenimipas.go.id'},
    {'nama': 'CUT VIEGHA HUMAIRA KHAIRUNNISA', 'email': 'cut.viegha.humaira.khairunnisa04@kemenimipas.go.id'},
    {'nama': 'CUT YARA ANDAMA', 'email': 'cut.yara.andama95@kemenimipas.go.id'},
    {'nama': 'CUT YESSI ANDRIANI', 'email': 'cut.yessi@kemenimipas.go.id'},
    {'nama': 'CUT YUNITA SARTIFA', 'email': 'cut.yunita.sartifa91@kemenimipas.go.id'},
    {'nama': 'CYNDI PERMATA SARI, S.Tr.Pas', 'email': 'cyndi.permata.sari98@kemenimipas.go.id'},
    {'nama': 'CYNDY FATIKHAH SARI', 'email': 'cyndy.fatikhah.sari04@kemenimipas.go.id'},
    {'nama': 'CYNTHIA FITRIANI', 'email': 'cynthia.fitriani96@kemenimipas.go.id'},
    {'nama': 'CYNTHIA HAYUWIRDHANI', 'email': 'cynthia.hayuwirdhani03@kemenimipas.go.id'},
    {'nama': 'CYNTHIA KIOK ALEXANDER', 'email': 'cynthia.kiok@kemenimipas.go.id'},
    {'nama': 'CYNTHIA RAMADHANITA SY', 'email': 'cynthia.ramadhanita@kemenimipas.go.id'},
    {'nama': 'CYNTIA DWI LESTARI', 'email': 'cyntia.dwi.lestari98@kemenimipas.go.id'},
    {'nama': 'CYNTIA FERGININGRUM', 'email': 'cyntia.ferginingrum@kemenimipas.go.id'},
    {'nama': 'CYNTIA, S.S', 'email': 'cyntia@kemenimipas.go.id'},
    {'nama': 'CYNTYA ANGGI SIANTURI', 'email': 'cyntya.anggi.sianturi97@kemenimipas.go.id'},
    {'nama': 'D E D I', 'email': 'd.e.d.i88@kemenimipas.go.id'},
    {'nama': 'D. S. JUANBERO DUMEDA', 'email': 'd.s.juanbero.dumeda01@kemenimipas.go.id'},
    {'nama': 'D YANETH PARULIAN LIMBONG', 'email': 'd.yaneth.parulian.limbong93@kemenimipas.go.id'},
    {'nama': 'DADAN ANUGRAH RAMDHAN', 'email': 'dadan.anugrah@kemenimipas.go.id'},
    {'nama': 'DADAN DANIAL', 'email': 'dadan.danial72@kemenimipas.go.id'},
    {'nama': 'DADAN FIRMANSYAH', 'email': 'dadan.firmansyah91@kemenimipas.go.id'},
    {'nama': 'DADAN GUNAWAN', 'email': 'dadan.gunawan@kemenimipas.go.id'},
    {'nama': 'DADAN HERDIANA', 'email': 'dadan.herdiana826@kemenimipas.go.id'},
    {'nama': 'DADAN HERDIANA', 'email': 'dadan.herdiana95@kemenimipas.go.id'},
    {'nama': 'DADAN HERMAWAN', 'email': 'dadan.hermawan78@kemenimipas.go.id'},
    {'nama': 'DADAN JUNAEDI', 'email': 'dadan.junaedi@kemenimipas.go.id'},
    {'nama': 'DADAN MAHMUD DJAJADISASTRA', 'email': 'dadan.mahmud.djajadisastra68@kemenimipas.go.id'},
    {'nama': 'DADAN MOHAMMAD RAMDAN', 'email': 'dadan.mohammad.ramdan96@kemenimipas.go.id'},
    {'nama': 'DADAN RULY NERE', 'email': 'dadan.ruly.nere82@kemenimipas.go.id'},
    {'nama': 'DADAN SETIA GUMELAR', 'email': 'dadan.setia@kemenimipas.go.id'},
    {'nama': 'DADAN WARDANA', 'email': 'dadan.wardana94@kemenimipas.go.id'},
    {'nama': 'DADAN', 'email': 'dadan70@kemenimipas.go.id'},
    {'nama': 'DADANG ADI PATIANUM', 'email': 'dadang.adi@kemenimipas.go.id'},
    {'nama': 'DADANG ASFAR', 'email': 'dadang.asfar90@kemenimipas.go.id'},
    {'nama': 'DADANG BAGUS SETYAWAN', 'email': 'dadang.bagus.setyawan90@kemenimipas.go.id'},
    {'nama': 'DADANG FIRMANSYAH', 'email': 'dadang.firmansyah@kemenimipas.go.id'},
    {'nama': 'DADANG HIDAYAT', 'email': 'dadang.hidayat70@kemenimipas.go.id'},
    {'nama': 'DADANG IRAWAN', 'email': 'dadang.irawan80@kemenimipas.go.id'},
    {'nama': 'DADANG JAYAATMANEGARA', 'email': 'dadang.jayaatmanegara89@kemenimipas.go.id'},
    {'nama': 'DADANG KURNIA', 'email': 'dadang.kurnia86@kemenimipas.go.id'},
    {'nama': 'DADANG KURNIAWAN', 'email': 'dadang.kurniawan86@kemenimipas.go.id'},
    {'nama': 'DADANG KUSUMA WIJAYA', 'email': 'dadang.kusuma.wijaya95@kemenimipas.go.id'},
    {'nama': 'DADANG MUNANDAR', 'email': 'dadang.munandar@kemenimipas.go.id'},
    {'nama': 'DADANG RAIS SAPUTRO', 'email': 'dadang.rais@kemenimipas.go.id'},
    {'nama': 'DADANG RAMADHAN AKBAR', 'email': 'dadang.ramadhan@kemenimipas.go.id'},
    {'nama': 'DADANG RIESMOKO', 'email': 'dadang.riesmoko84@kemenimipas.go.id'},
    {'nama': 'DADANG SAPUTRA', 'email': 'dadang.saputra71@kemenimipas.go.id'},
    {'nama': 'DADANG SISWANTO', 'email': 'dadang.siswanto79@kemenimipas.go.id'},
    {'nama': 'DADANG SUDRAJAT', 'email': 'dadang.sudrajat81@kemenimipas.go.id'},
    {'nama': 'DADANG SUHANDA', 'email': 'dadang.suhanda71@kemenimipas.go.id'},
    {'nama': 'DADANG SUHERLAN', 'email': 'Dadang.Suherlan@kemenimipas.go.id'},
    {'nama': 'DADANG SUMARDI', 'email': 'dadang.sumardi70@kemenimipas.go.id'},
    {'nama': 'DADANG SUPRIADI', 'email': 'dadang.supriadi69@kemenimipas.go.id'},
    {'nama': 'DADANG SURAHMAN', 'email': 'dadang.surahman95@kemenimipas.go.id'},
    {'nama': 'DADANG TRI BASKORO', 'email': 'dadang.tri.baskoro98@kemenimipas.go.id'},
    {'nama': 'DADANG TRIHATMOKO', 'email': 'dadang.trihatmoko@kemenimipas.go.id'},
    {'nama': 'DADANG TRIO ZULKARNAIN', 'email': 'dadang.trio.zulkarnain91@kemenimipas.go.id'},
    {'nama': 'DADANG YULIANTO', 'email': 'dadang.yulianto82@kemenimipas.go.id'},
    {'nama': 'DADDY RAMDHAN', 'email': 'daddy.ramdhan@kemenimipas.go.id'},
    {'nama': 'DADE ACHMAD AKTAMA', 'email': 'dade.achmad.aktama99@kemenimipas.go.id'},
    {'nama': 'DADI HENDARDI', 'email': 'dadi.hendardi00@kemenimipas.go.id'},
    {'nama': 'DADI KURNIAWAN', 'email': 'dadi.kurniawan83@kemenimipas.go.id'},
    {'nama': 'DADI SUTARDI', 'email': 'dadi.sutardi73@kemenimipas.go.id'},
    {'nama': 'DADIK TIPO HANANTO', 'email': 'dadik.tipo.hananto93@kemenimipas.go.id'},
    {'nama': 'DADING JAYAHADIKUSUMA', 'email': 'dading.jayahadikusuma@kemenimipas.go.id'},
    {'nama': 'DADY GUSNAWAN', 'email': 'Dady.Gusnawan@kemenimipas.go.id'},
    {'nama': 'DAELI PURWANTO', 'email': 'daeli.purwanto87@kemenimipas.go.id'},
    {'nama': 'DAENG ANTARRESTU', 'email': 'daeng.antarrestu77@kemenimipas.go.id'},
    {'nama': 'DAENG ARDIAN SAPUTRA', 'email': 'daeng.ardian.saputra94@kemenimipas.go.id'},
    {'nama': 'DAENI WAHYOUDIE', 'email': 'daeni.wahyoudie82@kemenimipas.go.id'},
    {'nama': 'DAEVFI APRIAN WAHYOUDIE', 'email': 'daevfi.aprian@kemenimipas.go.id'},
    {'nama': 'DAFA DINULHAK', 'email': 'dafa.dinulhak99@kemenimipas.go.id'},
    {'nama': 'DAFA ILHAMDIKA MOZA PRATAMA', 'email': 'dafa.ilhamdika.moza.pratama06@kemenimipas.go.id'},
    {'nama': 'DAFA NURHIDAYAT', 'email': 'dafa.nurhidayat06@kemenimipas.go.id'},
    {'nama': 'DAFA RENOLD JORDI', 'email': 'dafa.renold.jordi05@kemenimipas.go.id'},
    {'nama': 'DAFFA ABYAN NUGRAHANTO', 'email': 'daffa.abyan.nugrahanto06@kemenimipas.go.id'},
    {'nama': 'DAFFA ALIEF BAIHAQI', 'email': 'daffa.alief.baihaqi01@kemenimipas.go.id'},
    {'nama': 'DAFFA ANDALAS SURYA', 'email': 'daffa.andalas.surya01@kemenimipas.go.id'},
    {'nama': 'DAFFA ANUGRAH YASA PUTRA', 'email': 'daffa.anugrah.yasa.putra01@kemenimipas.go.id'},
    {'nama': 'DAFFA BAGOS MARSEKAL', 'email': 'daffa.bagos.marsekal03@kemenimipas.go.id'},
    {'nama': 'DAFFA CAHYA SABELA', 'email': 'daffa.cahya.sabela04@kemenimipas.go.id'},
    {'nama': 'DAFFA DWI RIANSYAH', 'email': 'daffa.dwi.riansyah03@kemenimipas.go.id'},
    {'nama': 'DAFFA DZAKY ADI SAKHA', 'email': 'daffa.dzaky.adi.sakha01@kemenimipas.go.id'},
    {'nama': 'DAFFA FAHRUL ROZY LUBIS', 'email': 'daffa.fahrul.rozy.lubis03@kemenimipas.go.id'},
    {'nama': 'DAFFA ICHSAN NOVRIANSYA', 'email': 'daffa.ichsan.novriansya99@kemenimipas.go.id'},
    {'nama': 'DAFFA IFTIKHAR', 'email': 'daffa.iftikhar@kemenimipas.go.id'},
    {'nama': 'DAFFA MAYANG LESTARI', 'email': 'daffa.mayang.lestari05@kemenimipas.go.id'},
    {'nama': 'DAFFA NUR FAUZAN', 'email': 'daffa.nur.fauzan00@kemenimipas.go.id'},
    {'nama': 'DAFFA NURRIZKY BLONGKOD', 'email': 'daffa.nurrizky.blongkod01@kemenimipas.go.id'},
    {'nama': 'DAFFA PRATAMA', 'email': 'daffa.pratama99@kemenimipas.go.id'},
    {'nama': 'DAFFA PUTRA DARMAWAN', 'email': 'daffa.putra.darmawan03@kemenimipas.go.id'},
    {'nama': 'DAFFA RIZKY RAMADHANI', 'email': 'daffa.rizky.ramadhani99@kemenimipas.go.id'},
    {'nama': 'DAFFA SETIAWAN', 'email': 'daffa.setiawan04@kemenimipas.go.id'},
    {'nama': 'DAFFA WICAKSONO', 'email': 'daffa.wicaksono05@kemenimipas.go.id'},
    {'nama': 'DAFFA YUDHISTIRA ALIF PAHLEVI', 'email': 'daffa.yudhistira.alif.pahlevi00@kemenimipas.go.id'},
    {'nama': 'NAUFAL DAFFA FERNALDY', 'email': 'daffafernaldy2002@gmail.com'},
    {'nama': 'DAFFARA ARSYAHITA PUTRI', 'email': 'daffara.arsyahita.putri01@kemenimipas.go.id'},
    {'nama': 'MUHAMMAD DAFFA RIVANO PASHA', 'email': 'daffarivano9b@gmail.com'},
    {'nama': 'DAFID ANTONI', 'email': 'dafid.antoni76@kemenimipas.go.id'},
    {'nama': 'DAFIDTRIA RAGIL PAMUNGKAS', 'email': 'dafidtria.ragil.pamungkas02@kemenimipas.go.id'},
    {'nama': 'DAFINAH HASHIFAH, S.Tr.Pas', 'email': 'dafinah.hashifah99@kemenimipas.go.id'},
    {'nama': 'DAFIT AGUSTARI', 'email': 'dafit.agustari86@kemenimipas.go.id'},
    {'nama': 'DAFIT ANDRIAN', 'email': 'dafit.andrian99@kemenimipas.go.id'},
    {'nama': 'DAFIT PRASETYA ALFAZAR', 'email': 'dafit.prasetya.alfazar01@kemenimipas.go.id'},
    {'nama': 'DAFIT PRIANGGA YUDHI', 'email': 'dafit.priangga.yudhi98@kemenimipas.go.id'},
    {'nama': 'DAFRIJON', 'email': 'dafrijon77@kemenimipas.go.id'},
    {'nama': 'DAGMAR MAMORI', 'email': 'dagmar.mamori93@kemenimipas.go.id'},
    {'nama': 'DAHARMAN JAYADI', 'email': 'daharman.jayadi69@kemenimipas.go.id'},
    {'nama': 'DAHLAN ANGGODA', 'email': 'dahlan.anggoda@kemenimipas.go.id'},
    {'nama': 'DAHLAN ARRIDHO', 'email': 'dahlan.arridho00@kemenimipas.go.id'},
    {'nama': 'DAHLAN DAMANIK', 'email': 'dahlan.damanik@kemenimipas.go.id'},
    {'nama': 'DAHLAN FAUZI LUBIS', 'email': 'dahlan.fauzi.lubis94@kemenimipas.go.id'},
    {'nama': 'DAHLAN HIDAYAT', 'email': 'dahlan.hidayat93@kemenimipas.go.id'},
    {'nama': 'DAHLAN RUMAU', 'email': 'dahlan.rumau@kemenimipas.go.id'},
    {'nama': 'DAHLAN', 'email': 'dahlan89@kemenimipas.go.id'},
    {'nama': 'DAHLAN', 'email': 'dahlan91@kemenimipas.go.id'},
    {'nama': 'DAHLIA MAHDALENI', 'email': 'dahlia.mahdaleni00@kemenimipas.go.id'},
    {'nama': 'DAHLIA MURNI', 'email': 'dahlia.murni@kemenimipas.go.id'},
    {'nama': 'DAHLIA PERTIWI SURYANI', 'email': 'dahlia.pertiwi@kemenimipas.go.id'},
    {'nama': 'DAHLIA, S.H., M.H.', 'email': 'dahlia@kemenimipas.go.id'},
    {'nama': 'DAHLIA', 'email': 'dahlia91@kemenimipas.go.id'},
    {'nama': 'DAHLIANA', 'email': 'dahliana00@kemenimipas.go.id'},
    {'nama': 'DAHLIYA MAHARANI', 'email': 'dahliya.maharani@kemenimipas.go.id'},
    {'nama': 'DAHNIA RAMADHANI', 'email': 'dahnia.ramadhani@kemenimipas.go.id'},
    {'nama': 'DAHNIA SANDRINA', 'email': 'dahnia.sandrina05@kemenimipas.go.id'},
    {'nama': 'DAHNIAL JAKA ADITIA', 'email': 'dahnial.jaka.aditia90@kemenimipas.go.id'},
    {'nama': 'DHANIEL SANDY PUTRA PAMUNGKAS', 'email': 'dahnielsandy95@icloud.com'},
    {'nama': 'DAHONO SUKO', 'email': 'dahono.suko@kemenimipas.go.id'},
    {'nama': 'DAHRONI', 'email': 'dahroni@kemenimipas.go.id'},
    {'nama': 'DAHRUL MANALU', 'email': 'dahrul.manalu90@kemenimipas.go.id'},
    {'nama': 'DAHRUL', 'email': 'dahrul93@kemenimipas.go.id'},
    {'nama': "DA'I RAFLI PRAKASA WINATA", 'email': 'dai.rafli.prakasa.winata02@kemenimipas.go.id'},
    {'nama': 'DAIRIBI', 'email': 'dairibi80@kemenimipas.go.id'},
    {'nama': 'DAKSA BIRAWA RASENDRIYA', 'email': 'daksa.birawa.rasendriya03@kemenimipas.go.id'},
    {'nama': 'DALAS MIGUNA', 'email': 'dalas.miguna05@kemenimipas.go.id'},
    {'nama': 'FANDALEN SITUMORANG', 'email': 'dalensit23@gmail.com'},
    {'nama': 'DALIANSYAH SARAGIH', 'email': 'daliansyah.saragih@kemenimipas.go.id'},
    {'nama': 'DALIFA HAYAT', 'email': 'dalifa.hayat@kemenimipas.go.id'},
    {'nama': 'DALIL MAAFI', 'email': 'dalil.maafi00@kemenimipas.go.id'},
    {'nama': 'DALILAH AMNI SIREGAR', 'email': 'dalilah.amni.siregar06@kemenimipas.go.id'},
    {'nama': 'DALIMIN, SH', 'email': 'dalimin69@kemenimipas.go.id'},
    {'nama': 'DALISYADI ADIPURNA', 'email': 'dalisyadi.adipurna@kemenimipas.go.id'},
    {'nama': 'DALRISMAN', 'email': 'dalrisman79@kemenimipas.go.id'},
    {'nama': 'DALWIN HERSON NENOHAI', 'email': 'dalwin.herson@kemenimipas.go.id'},
    {'nama': 'DAMAI ADI PRAYITNO', 'email': 'damai.adi.prayitno93@kemenimipas.go.id'},
    {'nama': 'DAMAIYANTO', 'email': 'damaiyanto92@kemenimipas.go.id'},
    {'nama': 'DAMAN GREGORIUS MANIK', 'email': 'daman.gregorius.manik94@kemenimipas.go.id'},
    {'nama': 'DAMAR AL-FAZRIN', 'email': 'damar.alfazrin05@kemenimipas.go.id'},
    {'nama': 'DAMAR BAGUS PRATIKNO', 'email': 'damar.bagus@kemenimipas.go.id'},
    {'nama': 'DAMAR RIZKI RAMADHAN', 'email': 'damar.rizki@kemenimipas.go.id'},
    {'nama': 'DAMAR ULUNG BINTARA SANTOSA', 'email': 'damar.ulung.bintara.santosa04@kemenimipas.go.id'},
    {'nama': 'DAMARA AGRIVA NAINGGOLAN', 'email': 'damara.agriva.nainggolan02@kemenimipas.go.id'},
    {'nama': 'DAMARDJATI RANGGA PRAMONO', 'email': 'damardjati.rangga.pramono04@kemenimipas.go.id'},
    {'nama': 'DAMARJATI RAMADHAN', 'email': 'damarjati.ramadhan04@kemenimipas.go.id'},
    {'nama': 'DAMAS KRESNA SAPUTRA', 'email': 'damas.kresna.saputra03@kemenimipas.go.id'},
    {'nama': 'DAMAS PRIHANDOKO', 'email': 'damas.prihandoko@kemenimipas.go.id'},
    {'nama': 'DAMASKUS APOLOS NATUN', 'email': 'damaskus.apolos.natun97@kemenimipas.go.id'},
    {'nama': 'DAMAYANTI MARZUKI', 'email': 'damayanti.marzuki89@kemenimipas.go.id'},
    {'nama': 'DAMAYANTI', 'email': 'damayanti@kemenimipas.go.id'},
    {'nama': 'DAME ELISA PRIMA', 'email': 'dame.elisa.prima91@kemenimipas.go.id'},
    {'nama': 'DAMEI ERMAN HARDINASTA.D.', 'email': 'damei.erman.hardinasta.d95@kemenimipas.go.id'},
    {'nama': 'DAMERIA NAINGGOLAN', 'email': 'dameria.nainggolan@kemenimipas.go.id'},
    {'nama': 'DAMERIA SIREGAR', 'email': 'dameria.siregar@kemenimipas.go.id'},
    {'nama': 'drg.. DAMERIA TARIGAN, M.Kes.', 'email': 'dameria.tarigan69@kemenimipas.go.id'},
    {'nama': 'DAMEULI YESSI CLARA SAMOSIR', 'email': 'dameuli.yessi.clara.samosir03@kemenimipas.go.id'},
    {'nama': 'DAMHURI', 'email': 'damhuri67@kemenimipas.go.id'},
    {'nama': 'DAMIAN DE VEUSTER M. DOPO', 'email': 'damian.de.veuster.m.dopo91@kemenimipas.go.id'},
    {'nama': 'DAMIAN DESMONDA LASE', 'email': 'damian.desmonda.lase00@kemenimipas.go.id'},
    {'nama': 'DAMIANA ENDAH APRIYANTI, A.Md', 'email': 'damiana.endah.apriyanti89@kemenimipas.go.id'},
    {'nama': 'DAMIANUS ARDHYNA BINTARA', 'email': 'damianus.ardhyna@kemenimipas.go.id'},
    {'nama': 'DAMIL NUGRAWAN SUCI', 'email': 'damil.nugrawansuci@kemenimipas.go.id'},
    {'nama': 'DAMIRA SUWENITA SEBAYANG', 'email': 'damira.suwenita.sebayang90@kemenimipas.go.id'},
    {'nama': 'DAMKI WAHONGAN', 'email': 'damki.wahongan@kemenimipas.go.id'},
    {'nama': 'DAMPA BUHATMA', 'email': 'dampa.buhatma89@kemenimipas.go.id'},
    {'nama': 'DAMRI', 'email': 'damri70@kemenimipas.go.id'},
    {'nama': 'DAMSI AFRIDA TRAPEN', 'email': 'damsi.afrida.trapen00@kemenimipas.go.id'},
    {'nama': 'DAMSYAH', 'email': 'damsyah69@kemenimipas.go.id'},
    {'nama': 'DANA ALYA UTAMI', 'email': 'dana.alya.utami02@kemenimipas.go.id'},
    {'nama': 'DANA PRADANA', 'email': 'dana.pradana92@kemenimipas.go.id'},
    {'nama': 'DANA WARDANA', 'email': 'dana.wardana@kemenimipas.go.id'},
    {'nama': 'DANA WEDAD ROMANZA', 'email': 'dana.wedad.romanza02@kemenimipas.go.id'},
    {'nama': 'DANAN SETIYANTO', 'email': 'danan.setiyanto83@kemenimipas.go.id'},
    {'nama': 'DANANG AGUNG PRIHATIN', 'email': 'danang.agung837@kemenimipas.go.id'},
    {'nama': 'DANANG ANDRIYANTO', 'email': 'danang.andriyanto@kemenimipas.go.id'},
    {'nama': 'DANANG ARIFIANTO', 'email': 'danang.arifianto@imigrasi.go.id'},
    {'nama': 'DANANG ARIYANTO', 'email': 'danang.ariyanto@kemenimipas.go.id'},
    {'nama': 'DANANG ARY ARDIYANSAH', 'email': 'danang.ary.ardiyansah87@kemenimipas.go.id'},
    {'nama': 'DANANG ARYA WIDYATMAKA', 'email': 'danang.arya87@kemenimipas.go.id'},
    {'nama': 'DANANG ARYADIRAJA', 'email': 'danang.aryadiraja@kemenimipas.go.id'},
    {'nama': 'DANANG ARYO HARYONO, S.Tr.Pas.', 'email': 'danang.aryo.haryono00@kemenimipas.go.id'},
    {'nama': 'DANANG CRISMON PRADANA', 'email': 'danang.crismon.pradana98@kemenimipas.go.id'},
    {'nama': 'DANANG DWI HARYADI', 'email': 'danang.dwi.haryadi88@kemenimipas.go.id'},
    {'nama': 'DANANG DWI ARIFAI', 'email': 'danang.dwi@kemenimipas.go.id'},
    {'nama': 'DANANG EKA PUTRA', 'email': 'danang.eka.putra94@kemenimipas.go.id'},
    {'nama': 'DANANG EKA SAPUTRA', 'email': 'danang.eka.saputra97@kemenimipas.go.id'},
    {'nama': 'DANANG EKA BINTARA', 'email': 'danang.ekabintara@kemenimipas.go.id'},
    {'nama': 'DANANG EKO PRABOWO', 'email': 'danang.eko.prabowo94@kemenimipas.go.id'},
    {'nama': 'DANANG EKO PRASETYO', 'email': 'danang.eko@kemenimipas.go.id'},
    {'nama': 'DANANG IRAWAN', 'email': 'danang.irawan98@kemenimipas.go.id'},
    {'nama': 'DANANG WAHYU NUR ISLAM', 'email': 'danang.islam@kemenimipas.go.id'},
    {'nama': 'DANANG JOYO', 'email': 'danang.joyo98@kemenimipas.go.id'},
    {'nama': 'DANANG KRISDIYANTO', 'email': 'danang.krisdiyanto@kemenimipas.go.id'},
    {'nama': 'DANANG KURNIYANTO', 'email': 'danang.kurniyanto94@kemenimipas.go.id'},
    {'nama': 'DANANG MAHENDRA BAGASKARA', 'email': 'danang.mahendra.bagaskara98@kemenimipas.go.id'},
    {'nama': 'DANANG MAKMUR HADI', 'email': 'danang.makmur@kemenimipas.go.id'},
    {'nama': 'DANANG PANDU WINOTO', 'email': 'Danang.Pandu@kemenimipas.go.id'},
    {'nama': 'DANANG PRASETYO NUGROHO', 'email': 'danang.prasetyo.nugroho05@kemenimipas.go.id'},
    {'nama': 'DANANG PRASETYO UTOMO, S.H', 'email': 'danang.prasetyo@kemenimipas.go.id'},
    {'nama': 'DANANG PRIYO SAMBODO', 'email': 'danang.priyo.sambodo88@kemenimipas.go.id'},
    {'nama': 'DANANG PRIYONO', 'email': 'danang.priyono84@kemenimipas.go.id'},
    {'nama': 'DANANG PURBOWO', 'email': 'danang.purbowo80@kemenimipas.go.id'},
    {'nama': 'DANANG RAHMAN KURNIAWAN', 'email': 'danang.rahman.kurniawan01@kemenimipas.go.id'},
    {'nama': 'DANANG SAPUTRO', 'email': 'danang.saputro83@kemenimipas.go.id'},
    {'nama': 'DANANG SATRIO KINASIH SUSETYO', 'email': 'danang.satrio.kinasih.susetyo00@kemenimipas.go.id'},
    {'nama': 'DANANG SEPTIANTO', 'email': 'danang.septianto91@kemenimipas.go.id'},
    {'nama': 'DANANG SETIAWAN SAPUTRO', 'email': 'danang.setiawan.saputro05@kemenimipas.go.id'},
    {'nama': 'DANANG SETIAWAN', 'email': 'danang.setiawan90@kemenimipas.go.id'},
    {'nama': 'DANANG SETIAWAN', 'email': 'danang.setiawan93@kemenimipas.go.id'},
    {'nama': 'DANANG SIHINGGUSTI', 'email': 'danang.sihinggusti98@kemenimipas.go.id'},
    {'nama': 'DANANG TRI ATMAJA', 'email': 'danang.tri.atmaja01@kemenimipas.go.id'},
    {'nama': 'DANANG TRI ATMAJA', 'email': 'danang.tri.atmaja89@kemenimipas.go.id'},
    {'nama': 'DANANG TRIANTORO', 'email': 'danang.triantoro03@kemenimipas.go.id'},
    {'nama': 'DANANG TRIYANTO', 'email': 'danang.triyanto80@kemenimipas.go.id'},
    {'nama': 'DANANG WAHYU WIBOWO, S.Ak.', 'email': 'danang.wahyu@kemenimipas.go.id'},
    {'nama': 'DANANG WIJANARKO', 'email': 'danang.wijanarko@kemenimipas.go.id'},
    {'nama': 'DANANG WIJANARKO', 'email': 'danang.wijanarko83@kemenimipas.go.id'},
    {'nama': 'DANANG WIJAYA', 'email': 'danang.wijaya89@kemenimipas.go.id'},
    {'nama': 'DANANG WISNU SANTOSO, S.Tr.Pas', 'email': 'danang.wisnu.santoso00@kemenimipas.go.id'},
    {'nama': 'DANANG YOGI OKFARI SANDI', 'email': 'danang.yogi.okfari.sandi92@kemenimipas.go.id'},
    {'nama': 'DANANJAYA AJIE PRATAMA', 'email': 'dananjaya.ajie.pratama93@kemenimipas.go.id'},
    {'nama': 'DANANTO WIBOWO, S.H.', 'email': 'dananto.wibowo@kemenimipas.go.id'},
    {'nama': 'DANAR ANGGIT RAHARJO', 'email': 'danar.anggit.raharjo90@kemenimipas.go.id'},
    {'nama': 'DANAR DONO', 'email': 'danar.dono92@kemenimipas.go.id'},
    {'nama': 'DANAR KURNIA RAMADANU', 'email': 'danar.kurnia.ramadanu02@kemenimipas.go.id'},
    {'nama': 'DANAR PANDU HIDAYAT', 'email': 'danar.pandu.hidayat04@kemenimipas.go.id'},
    {'nama': 'DANASTRI CIPTANINGRUM', 'email': 'danastri.ciptaningrum@kemenimipas.go.id'},
    {'nama': 'DANDI AL FAJAR', 'email': 'dandi.al.fajar98@kemenimipas.go.id'},
    {'nama': 'DANDI ARIYANTO', 'email': 'dandi.ariyanto99@kemenimipas.go.id'},
    {'nama': 'DANDI DANU BRATA', 'email': 'dandi.danu.brata@kemenimipas.go.id'},
    {'nama': 'DANDI FITRAH MAULANA', 'email': 'dandi.fitrah.maulana02@kemenimipas.go.id'},
    {'nama': 'DANDI JANWARSAH', 'email': 'dandi.janwarsah00@kemenimipas.go.id'},
    {'nama': 'DANDI KURNIAWAN', 'email': 'dandi.kurniawan98@kemenimipas.go.id'},
    {'nama': 'DANDI S. MASANG', 'email': 'dandi.masang@kemenimipas.go.id'},
    {'nama': 'DANDI PERMANA', 'email': 'dandi.permana@kemenimipas.go.id'},
    {'nama': 'DANDI PRATAMA HUTAGALUNG', 'email': 'dandi.pratama.hutagalung96@kemenimipas.go.id'},
    {'nama': 'DANDI VIRGIALDO DAMARA', 'email': 'dandi.virgialdo.damara98@kemenimipas.go.id'},
    {'nama': 'DANDI PRASETIYO KUSUMA AJI', 'email': 'dandiprasetiyo@gmail.com'},
    {'nama': 'DANDUN KUSUMA YUDHA', 'email': 'dandun.kusuma@kemenimipas.go.id'},
    {'nama': 'DANDUNG KENCONO', 'email': 'dandung.kencono91@kemenimipas.go.id'},
    {'nama': 'DANDY AGUNG PRATAMA', 'email': 'dandy.agung.pratama91@kemenimipas.go.id'},
    {'nama': 'DANDY ANDRIAN NOORYANTO', 'email': 'dandy.andrian.nooryanto87@kemenimipas.go.id'},
    {'nama': 'DANDY ARIEF PRASETYO, A.Md.Kep', 'email': 'dandy.arief.prasetyo93@kemenimipas.go.id'},
    {'nama': 'DANDY ATTA FAWZY', 'email': 'dandy.atta.fawzy99@kemenimipas.go.id'},
    {'nama': 'DANDY DARMAWAN Z', 'email': 'dandy.darmawan@kemenimipas.go.id'},
    {'nama': 'DANDY DIMAS YUDHISTIRA', 'email': 'dandy.dimas.yudhistira98@kemenimipas.go.id'},
    {'nama': 'DANDY HERLAMBANG', 'email': 'dandy.herlambang@kemenimipas.go.id'},
    {'nama': 'DANDY HERNANDA', 'email': 'dandy.hernanda01@kemenimipas.go.id'},
    {'nama': 'DANDY LAZUARDY', 'email': 'Dandy.Lazuardy@kemenimipas.go.id'},
    {'nama': 'DANDY MUHAMMAD IRZANI', 'email': 'dandy.muhammad.irzani98@kemenimipas.go.id'},
    {'nama': 'I GEDE DANDY SAPUTRA', 'email': 'dandy.saputra@kemenimipas.go.id'},
    {'nama': 'DANDY SATYAGRAHA BURHAN WIRADINATA', 'email': 'dandy.satyagraha.burhan.wiradinata93@kemenimipas.go.id'},
    {'nama': 'DANDY SETIAWAN HUSIN', 'email': 'dandy.setiawan.husin79@kemenimipas.go.id'},
    {'nama': 'DANDY SETYAWAN', 'email': 'dandy.setyawan03@kemenimipas.go.id'},
    {'nama': 'DANDY TRI KURNIAWAN ASLAM', 'email': 'dandy.tri.kurniawan.aslam06@kemenimipas.go.id'},
    {'nama': 'DANDY WAHYU PRATAMA', 'email': 'dandy.wahyu.pratama92@kemenimipas.go.id'},
    {'nama': 'DANEL ANDREAN BOY SUKI', 'email': 'danel.andrean.boy.suki03@kemenimipas.go.id'},
    {'nama': 'DANELIS RONALDO WORABAY', 'email': 'danelis.ronaldo.worabay00@kemenimipas.go.id'},
    {'nama': 'DANELLA SIANTURI', 'email': 'danella.sianturi98@kemenimipas.go.id'},
    {'nama': 'DANELLA ZULKARNAIN', 'email': 'danella.zulkarnain96@kemenimipas.go.id'},
    {'nama': 'DANENDRA APTAQUINNA TIROATMAJA', 'email': 'danendra.aptaquinna.tiroatmaja03@kemenimipas.go.id'},
    {'nama': 'DANER CHRISTY SIGILIPU', 'email': 'daner.christy@kemenimipas.go.id'},
    {'nama': 'DANG RAHMAN', 'email': 'dang.rahman95@kemenimipas.go.id'},
    {'nama': 'DANI ABUZAR', 'email': 'dani.abuzar06@kemenimipas.go.id'},
    {'nama': 'DANI ANJASMARA', 'email': 'dani.anjasmara94@kemenimipas.go.id'},
    {'nama': 'DANI APRIANTO', 'email': 'dani.aprianto80@kemenimipas.go.id'},
    {'nama': 'DANI ARDIANSYAH', 'email': 'dani.ardiansyah98@kemenimipas.go.id'},
    {'nama': 'DANI ARMANDO LUMBAN GAOL', 'email': 'dani.armando.lumban.gaol99@kemenimipas.go.id'},
    {'nama': 'DANI CANDRA PRATAMA', 'email': 'Dani.Candra@kemenimipas.go.id'},
    {'nama': 'DANI DIYAULHAQ', 'email': 'dani.diyaulhaq93@kemenimipas.go.id'},
    {'nama': 'DANI DWI ABIDIRA', 'email': 'dani.dwi.abidira92@kemenimipas.go.id'},
    {'nama': 'DANI EFENDI', 'email': 'dani.efendi@kemenimipas.go.id'},
    {'nama': 'DANI EKA OKTAVIAN', 'email': 'dani.eka.oktavian98@kemenimipas.go.id'},
    {'nama': 'DANI EKO PRASETIYO', 'email': 'dani.eko.prasetiyo99@kemenimipas.go.id'},
    {'nama': 'DANI FAISHAL AKRAM', 'email': 'dani.faishal.akram02@kemenimipas.go.id'},
    {'nama': 'DANI FATUROHMAN', 'email': 'dani.faturohman@kemenimipas.go.id'},
    {'nama': 'DANI HARIWIJAYA', 'email': 'dani.hariwijaya88@kemenimipas.go.id'},
    {'nama': 'DANI HUTABARAT', 'email': 'dani.hutabarat02@kemenimipas.go.id'},
    {'nama': 'DANI ILHAM HIDAYAT', 'email': 'dani.ilham@kemenimipas.go.id'},
    {'nama': 'DANI IRAWAN', 'email': 'dani.irawan@kemenimipas.go.id'},
    {'nama': 'DANI KAMANDAKA', 'email': 'dani.kamandaka03@kemenimipas.go.id'},
    {'nama': 'DANI KURNIANTO PRATAMA', 'email': 'dani.kurnianto.pratama79@kemenimipas.go.id'},
    {'nama': 'DANI KURNIAWAN', 'email': 'dani.kurniawan93@kemenimipas.go.id'},
    {'nama': 'DANI KURNIAWAN', 'email': 'dani.kurniawan981@kemenimipas.go.id'},
    {'nama': 'DANI MAIDA ANDIKA', 'email': 'dani.maida.andika94@kemenimipas.go.id'},
    {'nama': 'DANI MALIK', 'email': 'dani.malik01@kemenimipas.go.id'},
    {'nama': 'DANI MUHAMAD YACHYA', 'email': 'dani.muhamad.yachya77@kemenimipas.go.id'},
    {'nama': 'DANI MULIAWATI IRIANA SUTARYANTO', 'email': 'dani.muliawati@kemenimipas.go.id'},
    {'nama': 'DANI NURCAHYADI', 'email': 'dani.nurcahyadi03@kemenimipas.go.id'},
    {'nama': 'DANI PRAKASA', 'email': 'dani.prakasa@kemenimipas.go.id'},
    {'nama': 'DANI PRAMUDYA SAPUTRA', 'email': 'dani.pramudya.saputra02@kemenimipas.go.id'},
    {'nama': 'DANI PRASETYA HADI', 'email': 'dani.prasetya@kemenimipas.go.id'},
    {'nama': 'DANI PRASTIYO', 'email': 'dani.prastiyo98@kemenimipas.go.id'},
    {'nama': 'DANI RACHMAT SANTOSO', 'email': 'dani.rachmat.santoso99@kemenimipas.go.id'},
    {'nama': 'DANI RAMADHANI', 'email': 'dani.ramadhani99@kemenimipas.go.id'},
    {'nama': 'DANI RAMDANI', 'email': 'dani.ramdani94@kemenimipas.go.id'},
    {'nama': 'DANI RENWARIN', 'email': 'dani.renwarin90@kemenimipas.go.id'},
    {'nama': 'DANI RIDWAN', 'email': 'dani.ridwan79@kemenimipas.go.id'},
    {'nama': 'DANI SETIA', 'email': 'dani.setia79@kemenimipas.go.id'},
    {'nama': 'DANI SETIAJI', 'email': 'dani.setiaji@kemenimipas.go.id'},
    {'nama': 'DANI SUKARTONO NABABAN', 'email': 'dani.sukartono@kemenimipas.go.id'},
    {'nama': 'DANI WINATA ABDUL ROHIM', 'email': 'dani.winata.abdul.rohim92@kemenimipas.go.id'},
    {'nama': 'DANI YEKTI RAHAJENG', 'email': 'dani.yekti@kemenimipas.go.id'},
    {'nama': 'DANIA AKHMAD', 'email': 'dania.akhmad89@kemenimipas.go.id'},
    {'nama': 'DANIAL SAHIB', 'email': 'danial.sahib92@kemenimipas.go.id'},
    {'nama': 'DANIAR NEYRA DESTYA', 'email': 'daniar.neyra@kemenimipas.go.id'},
    {'nama': 'DANIEL AGUS PURWANTO', 'email': 'daniel.agus.purwanto97@kemenimipas.go.id'},
    {'nama': 'DANIEL AGUSTINUS', 'email': 'Daniel.Agustinus@kemenimipas.go.id'},
    {'nama': 'DANIEL ALDIANTA', 'email': 'daniel.aldianta01@kemenimipas.go.id'},
    {'nama': 'DANIEL ANANDA ARDIANSYAH', 'email': 'daniel.ananda.ardiansyah01@kemenimipas.go.id'},
    {'nama': 'DANIEL ANGGI SITORUS', 'email': 'daniel.anggi.sitorus03@kemenimipas.go.id'},
    {'nama': 'DANIEL ANUGERAH PASARIBU', 'email': 'daniel.anugerah@kemenimipas.go.id'},
    {'nama': 'DANIEL ARIS MARULI TUA PASARIBU', 'email': 'daniel.aris.maruli.tua.pasaribu90@kemenimipas.go.id'},
    {'nama': 'DANIEL ARUAN', 'email': 'daniel.aruan80@kemenimipas.go.id'},
    {'nama': 'DANIEL ASMON, SH', 'email': 'daniel.asmon@kemenimipas.go.id'},
    {'nama': 'DANIEL B. J. KREY', 'email': 'daniel.b.j.krey99@kemenimipas.go.id'},
    {'nama': 'DANIEL BAGAS SETYAWAN', 'email': 'daniel.bagas.setyawan92@kemenimipas.go.id'},
    {'nama': 'DANIEL BAKTIAR SITUMORANG', 'email': 'daniel.baktiar.situmorang98@kemenimipas.go.id'},
    {'nama': 'DANIEL BERKAT DAMAI NDRAHA', 'email': 'daniel.berkat@kemenimipas.go.id'},
    {'nama': 'DANIEL BERNANRIVO GONZALES', 'email': 'daniel.bernanrivo.gonzales94@kemenimipas.go.id'},
    {'nama': 'DANIEL BONARA', 'email': 'daniel.bonara71@kemenimipas.go.id'},
    {'nama': 'DANIEL CHARLES', 'email': 'daniel.charles@kemenimipas.go.id'},
    {'nama': 'DANIEL CHRISMANTO SIMATUPANG', 'email': 'daniel.chrismanto@kemenimipas.go.id'},
    {'nama': 'DANIEL CHRISTIAN RICARDO SINAGA', 'email': 'daniel.christian.ricardo.sinaga03@kemenimipas.go.id'},
    {'nama': 'DANIEL CITA WARISMAN NADEAK, S.H', 'email': 'daniel.cita.warisman.nadeak90@kemenimipas.go.id'},
    {'nama': 'DANIEL CRISTOPER SUHARTO', 'email': 'daniel.cristoper.suharto05@kemenimipas.go.id'},
    {'nama': 'DANIEL DEGAI', 'email': 'daniel.degai86@kemenimipas.go.id'},
    {'nama': 'DANIEL DEO KANDA SITUMORANG', 'email': 'daniel.deo.kanda.situmorang00@kemenimipas.go.id'},
    {'nama': 'DANIEL DRIKTUS TARIDISAN', 'email': 'daniel.driktus@kemenimipas.go.id'},
    {'nama': 'DANIEL DWI PUTRA MANIK', 'email': 'daniel.dwi.putra.manik01@kemenimipas.go.id'},
    {'nama': 'DANIEL FERNANDO GULTOM', 'email': 'daniel.fernando.gultom01@kemenimipas.go.id'},
    {'nama': 'DANIEL FERNANDO HUTAPEA', 'email': 'daniel.fernando.hutapea93@kemenimipas.go.id'},
    {'nama': 'DANIEL FERRY SETYAWAN', 'email': 'daniel.ferry.setyawan89@kemenimipas.go.id'},
    {'nama': 'DANIEL FREDERIK MINGGUS MAKANUAY', 'email': 'daniel.frederik.minggus.makanuay99@kemenimipas.go.id'},
    {'nama': 'DANIEL GANINTA SITEPU', 'email': 'daniel.ganinta.sitepu73@kemenimipas.go.id'},
    {'nama': 'DANIEL GILBERTH WAMBRAUW', 'email': 'daniel.gilberth.wambrauw99@kemenimipas.go.id'},
    {'nama': 'DANIEL GINTING', 'email': 'daniel.ginting94@kemenimipas.go.id'},
    {'nama': 'DANIEL IMANUEL MERE', 'email': 'daniel.imanuel.mere00@kemenimipas.go.id'},
    {'nama': 'DANIEL ITAAR', 'email': 'daniel.itaar@kemenimipas.go.id'},
    {'nama': 'DANIEL JAWAK', 'email': 'daniel.jawak03@kemenimipas.go.id'},
    {'nama': 'DANIEL JHON W SIHOMBING', 'email': 'Daniel.Jhon@kemenimipas.go.id'},
    {'nama': 'DANIEL JOSES SAHESE', 'email': 'daniel.joses.sahese00@kemenimipas.go.id'},
    {'nama': 'DANIEL JUNIVER SIAHAAN', 'email': 'daniel.juniver@kemenimipas.go.id'},
    {'nama': 'DANIEL KEVIN PAKPAHAN', 'email': 'daniel.kevin.pakpahan98@kemenimipas.go.id'},
    {'nama': 'DANIEL KOLLOH', 'email': 'daniel.kolloh85@kemenimipas.go.id'},
    {'nama': 'DANIEL KRISTIANTO', 'email': 'daniel.kristianto@kemenimipas.go.id'},
    {'nama': 'DANIEL KRISTIANTO', 'email': 'daniel.kristianto84@kemenimipas.go.id'},
    {'nama': 'DANIEL LELEWA', 'email': 'daniel.lelewa@kemenimipas.go.id'},
    {'nama': 'DANIEL LEONARDO SURBAKTI', 'email': 'daniel.leonardo.surbakti98@kemenimipas.go.id'},
    {'nama': 'DANIEL MAMBAYA', 'email': 'daniel.mambaya@kemenimipas.go.id'},
    {'nama': 'DANIEL MANALU', 'email': 'daniel.manalu97@kemenimipas.go.id'},
    {'nama': 'DANIEL MANAN KASTANYA', 'email': 'daniel.manan@kemenimipas.go.id'},
    {'nama': 'DANIEL SP MARBUN', 'email': 'daniel.marbun@kemenimipas.go.id'},
    {'nama': 'DANIEL MARCHUS PANJAITAN', 'email': 'daniel.marchus.panjaitan98@kemenimipas.go.id'},
    {'nama': 'DANIEL MARGONO SIRAIT', 'email': 'daniel.margono.sirait94@kemenimipas.go.id'},
    {'nama': 'DANIEL MARPAUNG', 'email': 'daniel.marpaung92@kemenimipas.go.id'},
    {'nama': 'DANIEL MARSAHALA SILITONGA', 'email': 'daniel.marsahala.silitonga02@kemenimipas.go.id'},
    {'nama': 'DANIEL MARTIN SINAGA', 'email': 'daniel.martin.sinaga92@kemenimipas.go.id'},
    {'nama': 'DANIEL MAUWA', 'email': 'Daniel.mauwa@kemenimipas.go.id'},
    {'nama': 'DANIEL MURA', 'email': 'daniel.mura@kemenimipas.go.id'},
    {'nama': 'DANIEL NAIBAHO', 'email': 'daniel.naibaho02@kemenimipas.go.id'},
    {'nama': 'DANIEL NIKSON WAYOI', 'email': 'daniel.nikson.wayoi99@kemenimipas.go.id'},
    {'nama': 'DANIEL NOVALDO', 'email': 'daniel.novaldo01@kemenimipas.go.id'},
    {'nama': 'DANIEL OKTOVIANUS MANO', 'email': 'daniel.oktovianus.mano94@kemenimipas.go.id'},
    {'nama': 'DANIEL OLOAN PUTRA SIMAMORA', 'email': 'daniel.oloan@kemenimipas.go.id'},
    {'nama': 'DANIEL PABUNTANG', 'email': 'daniel.pabuntang80@kemenimipas.go.id'},
    {'nama': 'DANIEL PAKA', 'email': 'daniel.paka96@kemenimipas.go.id'},
    {'nama': 'DANIEL PANCA OKTOBENY', 'email': 'daniel.panca.oktobeny92@kemenimipas.go.id'},
    {'nama': 'DANIEL PANGIHUTAN', 'email': 'daniel.pangihutan98@kemenimipas.go.id'},
    {'nama': 'DANIEL PARASIAN PAKPAHAN', 'email': 'daniel.parasian@kemenimipas.go.id'},
    {'nama': 'DANIEL PARULIAN MARTIN LUMBANTOBING', 'email': 'daniel.parulian.martin.lumbantobing02@kemenimipas.go.id'},
    {'nama': 'Daniel Paul Renhard ', 'email': 'daniel.paul.renhard03@kemenimipas.go.id'},
    {'nama': 'DANIEL PAULUS CARLO BARBIER', 'email': 'daniel.paulus@kemenimipas.go.id'},
    {'nama': 'DANIEL PERDAMENTA SEMBIRING', 'email': 'daniel.perdamenta.sembiring01@kemenimipas.go.id'},
    {'nama': 'DANIEL PRAWINANDA', 'email': 'daniel.prawinanda99@kemenimipas.go.id'},
    {'nama': 'DANIEL PUTRA', 'email': 'daniel.putra@kemenimipas.go.id'},
    {'nama': 'DANIEL RAHMADANI', 'email': 'daniel.rahmadani86@kemenimipas.go.id'},
    {'nama': 'DANIEL RICHARDO SIMANJUNTAK', 'email': 'daniel.richardo.simanjuntak99@kemenimipas.go.id'},
    {'nama': 'DANIEL RIZKYAWAN', 'email': 'daniel.rizkyawan01@kemenimipas.go.id'},
    {'nama': 'DANIEL ROBERTO ANIE', 'email': 'daniel.roberto@kemenimipas.go.id'},
    {'nama': 'DANIEL RONALDO', 'email': 'daniel.ronaldo@kemenimipas.go.id'},
    {'nama': 'DANIEL RUDOLF SORONTOU', 'email': 'daniel.rudolf@kemenimipas.go.id'},
    {'nama': 'DANIEL SAPUTRA SITORUS', 'email': 'daniel.saputra.sitorus96@kemenimipas.go.id'},
    {'nama': 'DANIEL SARAGIH', 'email': 'daniel.saragih96@kemenimipas.go.id'},
    {'nama': 'DANIEL SEHAT SIPAYUNG', 'email': 'daniel.sehat.sipayung06@kemenimipas.go.id'},
    {'nama': 'DANIEL SERAN', 'email': 'daniel.seran86@kemenimipas.go.id'},
    {'nama': 'DANIEL SIANTURI', 'email': 'daniel.sianturi87@kemenimipas.go.id'},
    {'nama': 'DANIEL SITINDAON S.H.', 'email': 'daniel.sitindaon@kemenimipas.go.id'},
    {'nama': 'DANIEL STEFANUS JHONI POYK', 'email': 'daniel.stefanus.jhoni.poyk77@kemenimipas.go.id'},
    {'nama': 'DANIEL SURBAKTI, S.H.', 'email': 'daniel.surbakti88@kemenimipas.go.id'},
    {'nama': 'DANIEL SUTANTO PUTRA', 'email': 'daniel.sutanto@kemenimipas.go.id'},
    {'nama': 'DANIEL SYALOOM LUAS SILITONGA', 'email': 'daniel.syaloom.luas.silitonga03@kemenimipas.go.id'},
    {'nama': 'DANIEL TAMPUBOLON', 'email': 'daniel.tampubolon96@kemenimipas.go.id'},
    {'nama': 'DANIEL TEDY PATTUDJU', 'email': 'daniel.tedy.pattudju85@kemenimipas.go.id'},
    {'nama': 'DANIEL TUA REYVALDO SIAHAAN', 'email': 'daniel.tua@kemenimipas.go.id'},
    {'nama': 'DANIEL VINCENT', 'email': 'daniel.vincent92@kemenimipas.go.id'},
    {'nama': 'DANIEL VOLMER DOLOKSARIBU', 'email': 'daniel.volmer@kemenimipas.go.id'},
    {'nama': 'DANIEL WAMBRAUW', 'email': 'Daniel.Wambrauw@kemenimipas.go.id'},
    {'nama': 'DANIEL ZENO ALRIANTONO', 'email': 'daniel.zeno.alriantono00@kemenimipas.go.id'},
    {'nama': 'DANIEL', 'email': 'daniel02@kemenimipas.go.id'},
    {'nama': 'DANIELD JAKOBSON SIMANJUNTAK', 'email': 'danield.jakobson@kemenimipas.go.id'},
    {'nama': 'DANIEL HASIBUAN', 'email': 'danielhasibuan@kemenimipas.go.id'},
    {'nama': 'DANIELI MENDROFA, S.Tr.Im.', 'email': 'danieli.mendrofa00@kemenimipas.go.id'},
    {'nama': 'DANIELTA WINNER BARUS', 'email': 'danielta.winner.barus01@kemenimipas.go.id'},
    {'nama': 'DANI HIDAYAT LUBIS', 'email': 'danihidayatlubis@kemenimipas.go.id'},
    {'nama': 'DANIK PURBAYA', 'email': 'danik.purbaya@kemenimipas.go.id'},
    {'nama': 'DANIK SRI WARDANI', 'email': 'danik.sri.wardani91@kemenimipas.go.id'},
    {'nama': 'DANIL DANIAL', 'email': 'danil.danial@kemenimipas.go.id'},
    {'nama': 'DANIL FERDIANSYAH, S.H', 'email': 'danil.ferdiansyah@kemenimipas.go.id'},
    {'nama': 'M DANIL KUSNANDI', 'email': 'danil.kusnandi@kemenimipas.go.id'},
    {'nama': 'DANIL MANGKAHUANA', 'email': 'danil.mangkahuana90@kemenimipas.go.id'},
    {'nama': 'DANIL MUSAKKIR', 'email': 'danil.musakkir@kemenimipas.go.id'},
    {'nama': 'DANIL NUGROHO', 'email': 'danil.nugroho86@kemenimipas.go.id'},
    {'nama': 'DANIL RACHMAN', 'email': 'danil.rachman@kemenimipas.go.id'},
    {'nama': 'DANIL SEPTIA KASMI', 'email': 'danil.septia.kasmi94@kemenimipas.go.id'},
    {'nama': 'DANIL SEPTIAN PUTRA', 'email': 'danil.septian@kemenimipas.go.id'},
    {'nama': 'DANIL YULIANA', 'email': 'danil.yuliana@kemenimipas.go.id'},
    {'nama': 'DANILO GERAL LAWA', 'email': 'danilo.geral.lawa97@kemenimipas.go.id'},
    {'nama': 'DANILSON', 'email': 'danilson89@kemenimipas.go.id'},
    {'nama': 'Daning Eka Pratiwi', 'email': 'daning.eka.pratiwi96@kemenimipas.go.id'},
    {'nama': 'DANIS PASKAH', 'email': 'danis.paskah86@kemenimipas.go.id'},
    {'nama': 'DANIWIHARYA IDRIS', 'email': 'daniwiharya.idris@kemenimipas.go.id'},
    {'nama': 'DANNAR FARDIAN AFFANDI', 'email': 'dannar.fardian.affandi96@kemenimipas.go.id'},
    {'nama': 'DANNI FERDIANSYAH PRASETYA', 'email': 'danni.ferdiansyah@kemenimipas.go.id'},
    {'nama': 'DANNI RONALDO SIMAMORA', 'email': 'danni.ronaldo@kemenimipas.go.id'},
    {'nama': 'DANNI SASTRIATI SIHOMBING', 'email': 'danni.sastriati.sihombing92@kemenimipas.go.id'},
    {'nama': 'DANNU PRIYANTO', 'email': 'dannu.priyanto@kemenimipas.go.id'},
    {'nama': 'DANNY ARIANA', 'email': 'danny.ariana@kemenimipas.go.id'},
    {'nama': 'DANNY BAHAR', 'email': 'danny.bahar@kemenimipas.go.id'},
    {'nama': 'DANNY DWI KURNIANTO', 'email': 'danny.dwi.kurnianto93@kemenimipas.go.id'},
    {'nama': 'DANNY EKA SAPUTRA', 'email': 'danny.eka.saputra90@kemenimipas.go.id'},
    {'nama': 'DANNY FERIANTO', 'email': 'danny.ferianto81@kemenimipas.go.id'},
    {'nama': 'DANNY PERMANA TARIGAN', 'email': 'danny.permana@kemenimipas.go.id'},
    {'nama': 'DANNY SATYA BRATA', 'email': 'danny.satya@kemenimipas.go.id'},
    {'nama': 'DANNY TRISTIANTO', 'email': 'danny.tristianto93@kemenimipas.go.id'},
    {'nama': 'DANNY YUDHA PRATAMA', 'email': 'danny.yudha.pratama91@kemenimipas.go.id'},
    {'nama': 'DANNYEL', 'email': 'dannyel99@kemenimipas.go.id'},
    {'nama': 'DANNY INDRA MARTOHAP MANULLANG', 'email': 'dannyindra.martohapmanullang@kemenimipas.go.id'},
    {'nama': 'DANO FAUJAN SYAIFUDIN', 'email': 'dano.faujan.syaifudin05@kemenimipas.go.id'},
    {'nama': 'DANRES SIBURIAN', 'email': 'danres.siburian@kemenimipas.go.id'},
    {'nama': 'DANTE HAEKAL ARDIYANTO', 'email': 'dante.haekal.ardiyanto04@kemenimipas.go.id'},
    {'nama': 'DANTI NURSAMSI', 'email': 'danti.nursamsi91@kemenimipas.go.id'},
    {'nama': 'DANU ANGGA SASONO', 'email': 'danu.angga.sasono84@kemenimipas.go.id'},
    {'nama': 'DANU ARDIAN SAPUTRA', 'email': 'danu.ardian@kemenimipas.go.id'},
    {'nama': 'DANU ARDIYANTO', 'email': 'danu.ardiyanto89@kemenimipas.go.id'},
    {'nama': 'DANU ARI WIBOWO', 'email': 'danu.ari.wibowo92@kemenimipas.go.id'},
    {'nama': 'DANU DEWANTORO', 'email': 'danu.dewantoro92@kemenimipas.go.id'},
    {'nama': 'DANU DWI PAMUNGKAS, S.I.Kom', 'email': 'danu.dwi@kemenimipas.go.id'},
    {'nama': 'DANU EKA WARDANA', 'email': 'danu.eka@kemenimipas.go.id'},
    {'nama': 'DANU FAJAR KURNIAWAN', 'email': 'danu.fajar@kemenimipas.go.id'},
    {'nama': 'DANU FIRMANSYAH', 'email': 'danu.firmansyah04@kemenimipas.go.id'},
    {'nama': 'DANU IHSAN ADLIYAN SUPRASNA', 'email': 'danu.ihsan.adliyan.suprasna99@kemenimipas.go.id'},
    {'nama': 'DANU MARDAYANSYAH', 'email': 'danu.mardayansyah04@kemenimipas.go.id'},
    {'nama': 'DANU NUR FAZRI', 'email': 'danu.nur.fazri94@kemenimipas.go.id'},
    {'nama': 'DANU PRAMUSINTA', 'email': 'Danu.pramusinta@kemenimipas.go.id'},
    {'nama': 'DANU PRASMUDIA REBOWO', 'email': 'danu.prasmudia.rebowo04@kemenimipas.go.id'},
    {'nama': 'DANU PRAWITA', 'email': 'danu.prawita@kemenimipas.go.id'},
    {'nama': 'DANU SATRIO HARYANTO', 'email': 'danu.satrio@kemenimipas.go.id'},
    {'nama': 'DANU SERMUMES', 'email': 'danu.sermumes94@kemenimipas.go.id'},
    {'nama': 'DANU SUHADA', 'email': 'danu.suhada98@kemenimipas.go.id'},
    {'nama': 'DANU TRI SETYAWAN', 'email': 'danu.tri.setyawan96@kemenimipas.go.id'},
    {'nama': 'DANU UJI WASONO', 'email': 'danu.uji.wasono83@kemenimipas.go.id'},
    {'nama': 'DANU UMBORO', 'email': 'danu.umboro81@kemenimipas.go.id'},
    {'nama': 'DANUAR RIZKI PRAYUDA', 'email': 'danuar.rizki.prayuda99@kemenimipas.go.id'},
    {'nama': 'DANUR TRI GONGGO', 'email': 'danur.tri.gonggo99@kemenimipas.go.id'},
    {'nama': 'DANVY DIANA NURFILAH RAHMAN', 'email': 'danvy.diana@kemenimipas.go.id'},
    {'nama': 'DANY ANDRIANTO', 'email': 'dany.andrianto90@kemenimipas.go.id'},
    {'nama': 'DANY ASTRIANTO', 'email': 'dany.astrianto@kemenimipas.go.id'},
    {'nama': 'DANY DWI WANTORO', 'email': 'dany.dwi@kemenimipas.go.id'},
    {'nama': 'DANY FADILAH RAMDHANY, S.H', 'email': 'dany.fadilah@kemenimipas.go.id'},
    {'nama': 'DANY FERDIYANTO', 'email': 'dany.ferdiyanto85@kemenimipas.go.id'},
    {'nama': 'DANY FRITSIAN RADJAB', 'email': 'dany.fritsian@kemenimipas.go.id'},
    {'nama': 'DANY HILMI AMRULLAH', 'email': 'dany.hilmi.amrullah98@kemenimipas.go.id'},
    {'nama': 'DANY INDRIANTO', 'email': 'dany.indrianto@kemenimipas.go.id'},
    {'nama': 'DANY IRAWAN', 'email': 'dany.irawan91@kemenimipas.go.id'},
    {'nama': 'DANY LUZA PRIHATMAJA', 'email': 'dany.luza@kemenimipas.go.id'},
    {'nama': 'DANY MARSA SAL SABILA', 'email': 'dany.marsa.sal.sabila01@kemenimipas.go.id'},
    {'nama': 'DANY PRIHADI', 'email': 'dany.prihadi00@kemenimipas.go.id'},
    {'nama': 'DANY RAHMAN', 'email': 'dany.rahman@kemenimipas.go.id'},
    {'nama': 'DANY RIZKI SETIAWAN', 'email': 'dany.rizki.setiawan94@kemenimipas.go.id'},
    {'nama': 'DANY SETIAWAN', 'email': 'dany.setiawan@kemenimipas.go.id'},
    {'nama': 'DANY TRISUNU', 'email': 'Dany.Trisunu@kemenimipas.go.id'},
    {'nama': 'DAONI SINAGA, A.Md', 'email': 'daoni.sinaga@kemenimipas.go.id'},
    {'nama': 'DAPEN HC UTAMA', 'email': 'dapen.hc.utama00@kemenimipas.go.id'},
    {'nama': 'DAPENDRA SAPUTRA', 'email': 'dapendra.saputra92@kemenimipas.go.id'},
    {'nama': 'DAPIT TAUFIQ GINTING', 'email': 'dapit.taufiq@kemenimipas.go.id'},
    {'nama': 'DAPOT PARULIAN SITIO', 'email': 'dapot.parulian@kemenimipas.go.id'},
    {'nama': 'DAPRIL', 'email': 'dapril96@kemenimipas.go.id'},
    {'nama': 'DARA GAUTAMA MEILINA', 'email': 'dara.gautama.meilina00@kemenimipas.go.id'},
    {'nama': 'DARA ISLAMI, S.E', 'email': 'dara.islami@kemenimipas.go.id'},
    {'nama': 'DARA MERITIKA', 'email': 'dara.meritika@kemenimipas.go.id'},
    {'nama': 'DARA PUSPITASARI', 'email': 'dara.puspitasari@kemenimipas.go.id'},
    {'nama': 'DARASHIVA MAHARANI', 'email': 'darashiva.maharani99@kemenimipas.go.id'},
    {'nama': 'DARDAK', 'email': 'dardak69@kemenimipas.go.id'},
    {'nama': 'DARHAM', 'email': 'darham94@kemenimipas.go.id'},
    {'nama': 'DARI AULIA QITAL', 'email': 'dari.qital@kemenimipas.go.id'},
    {'nama': 'DARIA SUHARYONO', 'email': 'daria.suharyono@kemenimipas.go.id'},
    {'nama': 'DARIL SAHENDRA', 'email': 'daril.sahendra01@kemenimipas.go.id'}
]
